### ISSUE TITLE
Move all ships onto portal to jump

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#101]
Players want the feeling of moving everything into one spot, a portal.
We should use this as an opportunity to add more gameplay.

Yes. This is now becoming pikmin.

In pikimin you want to move all your units back into your ship for safety.

We can apply that idea.

Ships left behind are destroyed by the enemy.

https://youtu.be/ORAmdm_te5M

**Comment by josefnpat** [comment]
relate sto #57

**Comment by josefnpat** [comment]
Closing since SP is slated for removal
