### ISSUE TITLE
tutorial doesn't explain mining / refining well enough

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#112]

**Comment by softsound** [comment]
Show players asteroid - say man it would be cool if we could use that resource - be like oh let's build a miner so we can use it - then be like oh we have ore now, let's make it a use-able material build a refiner.

Say asteroids give more material than scraps, that is why the process is worth it.

Also build wall/field of asteroid and be like we can't see or move further until we clear the way or go around. That works too.

**Comment by josefnpat** [comment]
This is really broad. Can you be more specific?

>Show players asteroid - say man it would be cool if we could use that resource - be like oh let's build a miner so we can use it - then be like oh we have ore now, let's make it a use-able material build a refiner.

How do I "show a player an asteroid"? Do you mean as an icon?

>Say asteroids give more material than scraps, that is why the 2 step process is worth it.

But this isn't true. It's worth it because they're extra resources lying around.

>When we add gas the refiner will be more useful as we can have it convert any raw resource.

This belongs on a different ticket ...

>Make scrap more rare and harder to find so players feel more of a reward when they find it, because it saves them time. 

But the purpose of scrap is for [level balance](https://docs.google.com/spreadsheets/d/1LbTb6jixVxiZjQqVmQys-TgjbNuugZvI0wV-RiO8fRw/edit#gid=0).

> Also miner(s) & refiner should always cost less then savager.

This belongs on it's own ticket as well...

**I really don't know what you want here. Can you give me game ready help and objective text?**

This is what the tutorial currently has:

```lua
  t:add{
    objtext = "We have detected asteroids in this system. We should use the Drydock to build some Mining Rigs to mine them.",
    helptext = "Select the command ship, and use the Build Drydock action if you haven't already. Select the Drydock, and use the Build Mining Rig action. Select the Mining Rig, and right mouse click on an Asteroid.",
    helpguides = {"object_command","object_drydock","object_mining","object_asteroid"},
    complete = function()
      local ship = libs.tutorial.wait.select_single_object("mining")
      return ship and ship.target_object and ship.target_object.type == "asteroid"
    end,
  }

  t:add{
    objtext = "We have some ore now, but we can't refine it without a Refinery. Build one and inform it to to convert Ore to Material. ",
    helptext = "Select the command ship, and use the Build Drydock action if you haven't already. Select the Drydock ship, and use the Build Refinery action. Select the Refinery ship, toggle the \"Refine Ore\" action.",
    helpguides = {"object_command","object_drydock","object_refinery","action_refine"},
    complete = function()
      local ship = libs.tutorial.wait.select_single_object("refinery")
      return ship and ship.refine
    end,
  }
```

**Comment by josefnpat** [comment]
Closing since SP is slated for removal
