### ISSUE TITLE
Make command ship more noticible

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#130]

**Comment by softsound** [comment]
Temp
![commandship0](https://cloud.githubusercontent.com/assets/1772703/26518448/6995e678-4276-11e7-861f-cb7a3bf4ef46.png)

**Comment by softsound** [comment]
fix

![commandship0](https://cloud.githubusercontent.com/assets/1772703/26518454/9b57aeb2-4276-11e7-8b33-5e206ca8fb63.png)

**Comment by josefnpat** [comment]
![command_new](https://cloud.githubusercontent.com/assets/646162/26523931/8c4a6662-42e9-11e7-8bd8-72b3e2fddb86.png)

**Comment by softsound** [comment]
![command0](https://cloud.githubusercontent.com/assets/1772703/26526075/01033468-4333-11e7-8061-64f47fedf727.png)

**Comment by josefnpat** [comment]
b32d62d5973abd4f4450d62266992069e711cf86
90ff51f8512de737eb119683359c353fe62e8a40
