### ISSUE TITLE
Custom Mouse Cursor

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#143]
Remove if you don't like this idea

**Comment by softsound** [comment]
I don't think this is important enough for this milestone.

**Comment by softsound** [comment]
![mouse cursor](https://cloud.githubusercontent.com/assets/1772703/24926428/2473e046-1ec1-11e7-94f8-cacf566fa922.png)

**Comment by softsound** [comment]
![mouse cursor](https://cloud.githubusercontent.com/assets/1772703/24926464/42c32ea8-1ec1-11e7-9d8c-7f6518b38a87.png)

**Comment by josefnpat** [comment]
Can we get more of a pointer than a drag-drop-select cursor?

![image](https://cloud.githubusercontent.com/assets/646162/24930871/abdd0dfa-1ed0-11e7-800d-c1043ebbceb1.png)

![image](https://cloud.githubusercontent.com/assets/646162/24930875/b03bb950-1ed0-11e7-849f-c87d5927f68e.png)
![image](https://cloud.githubusercontent.com/assets/646162/24930879/b4ed2be6-1ed0-11e7-8873-fa07013c0530.png)

**Comment by josefnpat** [comment]
![cursor](https://cloud.githubusercontent.com/assets/646162/24966116/b0063438-1f6b-11e7-8123-61cfa5a9e060.png)

You should be able to replace `src/assets/cursor.png` now.

The center of the image is actual location of the mouse (regardless of image size)

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/27870741-4e43680c-6169-11e7-916f-bbc31d79fab3.png)
