### ISSUE TITLE
Blog Entry

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#146]
We need to post a blog entry every week. Every week we need someone to step up and commit to writing something fun.

**Comment by softsound** [comment]
I don't know about fun, but I can probably write stuff, though, I might want people to review before I post it lol

**Comment by josefnpat** [comment]
I will be happy to review it ;)

**Comment by softsound** [comment]
Maybe once a month now lol

**Comment by snowschu** [comment]
Closing this ticket. 

Reasons:
Short: The original reason for this ticket is no longer relevant to the current state of the project.

Long: While having an on-going dev blog is great for development tracking and gaining interest in a game, this ends up falling on the team lead/project manager to push these out, as they will be the ones with the most collective knowledge of whats going in in the project.

With RCS, we've had an ebb and flow of developmental progress through out the project. People have come and gone and some of us have taken on other projects. 

As we near the end of the project, we have been and will continue make blog posts (right now we're using itch.io) on relevant project updates but not as this ticket originally stated: `We need to post a blog entry every week. Every week we need someone to step up and commit to writing something fun.`

I will also note that social media platforms, such as twitter and facebook, will be more friendly for quick updates than a blog post.
