### ISSUE TITLE
Doubleclick only selects ships on screen

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#147]

**Comment by josefnpat** [comment]
I would like some feedback on this!

**Comment by snowschu** [comment]
If i'm reading it correctly, you're asking if only the ships _in view_ (on the screen) will be selected with the double-click feature?

Yes. This is a great idea. I have found it frustrating when I've double clicked the ships and have had ships 'recalled' from across the map. T^T

That being said, it would be nice to have option to recall all the ships on the map (all of the one type of ship thats available on the map, i mean).  Could be in settings (_what do you want double click to do?_) or a keyboard option, or the lovely "trip click" :P

**Comment by softsound** [comment]
Agreed with @snowschu

**Comment by josefnpat** [comment]
// Update is called once per frame
