### ISSUE TITLE
Clean up Menu

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#150]
Ashley says it "feels odd".

suggestions:

* Recenter menu
* Left align text

**Comment by softsound** [comment]
I personally love the lol menu's and interface, I've tried to steal design ideas from them. Everything seems clear and simple.

**Comment by softsound** [comment]
There is nothing wrong with what we have as long we keep the text short and easy to read.

![image](https://cloud.githubusercontent.com/assets/1772703/24977307/342275da-1f92-11e7-8039-17ccbba2fe37.png)

**Comment by josefnpat** [comment]
align logo to mid right

**Comment by josefnpat** [comment]
move menu to right

**Comment by josefnpat** [comment]
036d03c9e9729d5ae3e1d630b8817d9fdb641ba7
