### ISSUE TITLE
Survey presented on death or escape for game demo

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#154]
Trying to get more people to take survey.

**Comment by josefnpat** [comment]
needs more info

**Comment by softsound** [comment]
I don't think the survey should run every game, just add a side blinking button for the survey or something.

...Actually a "news channel" like in lol would be kinda cool in the menu. Let people know about what updates we have made. Ask for them to take the survey and give us input and add a button for them to post our game on social media. It doesn't have to be big.


Also I think the survey would be better if we used it when we demo'd the game.

**Comment by josefnpat** [comment]
ashley will mock this up

**Comment by josefnpat** [comment]
This either needs to be put in the backlog or split up into actionable tickets

**Comment by softsound** [comment]
Redesign main menu to have news channel and give feedback button.

**Comment by josefnpat** [comment]
This is annoying, put feedback as menu item.
