### ISSUE TITLE
Company website requests

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#159]
Maybe we could put everything in one key location for contact info, media templates, press kit and marketing stuff?? Like everything we don't want on GitHub. 

I would say to use Google docs but I'd prefer to keep all this separate as it will get mixed up in my docs. 

Not sure on solution, but I want company and project stuff all in one spot. Having stuff emailed or messaged or put on GitHub and what not makes me disorganized as I have to look for info in too many locations. 

Maybe MSS could just have a side on the site where we can login and view or update/download this stuff IDK. 

MSS also needs to be revamped and to start focusing on how it wants to feel as a brand, we need to figure out what our brand wants to say, what type of people we want to play our games.

**Comment by josefnpat** [comment]
make private wiki on MSS
