### ISSUE TITLE
Level 2 is too slow

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#161]
Most people get puzzled by the amount of steps and no one got past level 2 but it might have also been the high competition where we were hosting the demo. People wanted to play something more fun and social...

**Comment by softsound** [comment]
Recommend event or mission in level 2?

**Comment by josefnpat** [comment]
* Maybe more tutorial would help?
* Optional objective?
* Spawn enemies when jump drive is ready?

**Comment by softsound** [comment]
![image](https://cloud.githubusercontent.com/assets/1772703/25553821/369e0cea-2c83-11e7-8b32-8c6b88d3633f.png)

Figuring out the sweet spot for entertainment is the tough thing. I think all those things would help.

**Comment by josefnpat** [comment]
redetermine now that there are level spawns

**Comment by josefnpat** [comment]
Figure out why too slow (or if!)
