### ISSUE TITLE
Figure out competitors

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#173]
We need to know who we are going up against, having a list of 10 competitors would be handy.

**Comment by josefnpat** [comment]
http://store.steampowered.com/app/371010/Nomad_Fleet/
http://store.steampowered.com/app/335830/Distant_Star_Revenant_Fleet/
http://store.steampowered.com/app/396480/Battlevoid_Harbinger/
http://store.steampowered.com/app/204530/Infested_Planet/

**Comment by josefnpat** [comment]
http://store.steampowered.com/app/578670/Conquest_Frontier_Wars/
http://store.steampowered.com/app/212680/FTL_Faster_Than_Light/

**Comment by josefnpat** [comment]
Endless Space
Star Drive
Star Control
battlevoid sector siege

**Comment by josefnpat** [comment]
[Document is now here](https://docs.google.com/spreadsheets/d/1Ifka7cwuenAKiSNZQqODM0sGmnMDBXPzcvYS8LQT8-o/edit?usp=sharing).

Added to wiki
