### ISSUE TITLE
Add ship encyclopedia

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#178]
Add an encyclopedia at the main menu to show off different discovered ships

**Comment by josefnpat** [comment]
Also show all enemy ship types you've defeated

**Comment by josefnpat** [comment]
Also add Lore

**Comment by softsound** [comment]
Yes

**Comment by josefnpat** [comment]
flesh out more

**Comment by josefnpat** [comment]
solved by research gamestate
