### ISSUE TITLE
Add level node map

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#179]
Add a map that would show players how they are progressing

![image](https://cloud.githubusercontent.com/assets/646162/26536228/897539e6-43fa-11e7-8011-efbab5c89c2b.png)

![image](https://cloud.githubusercontent.com/assets/646162/26536233/925fb694-43fa-11e7-886b-209c0317d750.png)

**Comment by softsound** [comment]
Hmmm. Good idea.
