### ISSUE TITLE
Ship Idea: Satellite Relay

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#187]
Make a ship that creates satellites that maintain vision

**Comment by josefnpat** [comment]
What if we could make this so enemies go after these units first? Or wander to them first?

Maybe we could also "deploy decoy"

**Comment by softsound** [comment]
satellites -

- give light
- get rid of clouds
- could build wall of 'em
- could where out after time...
- enemies might go after them
- could increase chance of research points/data pods spawning

**Comment by josefnpat** [comment]
a05b466b48c6015695cf33295251c5e89445306f current implementation - not convinced by it yet

**Comment by josefnpat** [comment]
Please provide feedback if you think the satellite from the radar array is good

**Comment by softsound** [comment]
I find myself using them, but having more features then a basic torch is good. May be more useful in open world/creative modes.

**Comment by josefnpat** [comment]
@softsound do we still need this ticket?

**Comment by snowschu** [comment]
The Radar Array building the Satellite is a good idea, imo.  It it adds a little more use to the array and make it more valuable.

I would like to see some improvements/adjustments made possibly.  Make the arrays cost more to produce and lower the HP/armor/health of the arrays to make them easier to take down (stealthy means more squishy).

Also, would it be weird to allow for a pinging feature...somewhere? Could be any ship but it would be neat to be able to ping and see where the Satellites have been dropped ( by any one).

**Comment by josefnpat** [comment]
@snowschu re:
> I would like to see some improvements/adjustments made possibly. Make the arrays cost more to produce and lower the HP/armor/health of the arrays to make them easier to take down (stealthy means more squishy).

Do you think radar arrays are too strong currently?

> Also, would it be weird to allow for a pinging feature...somewhere? Could be any ship but it would be neat to be able to ping and see where the Satellites have been dropped ( by any one).

Not sure what you mean by ping. In single player, I still need to port warning notifications on the minimap. Is that what you're talking about?

**Comment by snowschu** [comment]
@josefnpat [re](https://github.com/josefnpat/roguecraft-squadron/issues/187#issuecomment-397788513):

I will review your current updates and get back to you on it.

**Comment by softsound** [comment]
I think we still need this ticket as a design ticket to flesh out the torches, make them more functional. I believe I've offered suggestions. @josefnpat 

satellites -

- get rid of clouds
- could build wall of 'em
- could wear out after time...
- enemies might go after them
- could increase chance of research points/data pods spawning nearby?

Do we want any of this features? I think adding any of them could be cool.

**Comment by snowschu** [comment]
@josefnpat @softsound is this ticket still relevant to our current milestone? I think we can close this for now and reopen it in the future if we choose to refine how the satellite's work.

**Comment by josefnpat** [comment]
This was a part of the "Temp" milestone.
