### ISSUE TITLE
Button Pins

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#188]
For RCS or MSS. Maybe both?

Info/Contact: SnowSchu

**Comment by josefnpat** [comment]
![button-template-225](https://cloud.githubusercontent.com/assets/646162/26741939/150f1d60-47a1-11e7-9a0d-636dcaa9ca7e.png)

Here is the template.

These two worked really nicely;

![lp-avatar-classic](https://cloud.githubusercontent.com/assets/646162/26741947/1de67082-47a1-11e7-9142-c60d642d44f0.png)
![button-template-225-mss](https://cloud.githubusercontent.com/assets/646162/26741950/1ed6e0bc-47a1-11e7-8510-0c36ae3c12e3.png)

**Comment by josefnpat** [comment]
will attach a photo when i get a chance

**Comment by softsound** [comment]
Team pins have been created.
