### ISSUE TITLE
Clean Up Magic Numbers

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#195]
Magic Numbers found in `Mission.lua:self.camera.[vertical|horizontal]_mouse_move`

```
> 1920/x = 30/16.875

  ((1920 / x) = (30 / 16.875)) = (x = 1080)
```

Seems like it was designed to make 1920x1080 resolutions feel good. Need to clean that up now that resolution is no longer fixed.

**Comment by softsound** [comment]
I've found .15 to work fine for both, just 60% of the screen is used for triggering scroll. of course my screens are different so I'm not sure how well that works on other sizes.
