### ISSUE TITLE
Add effects to collect/gather operations

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#2]
Add smoke to mining and salvaging

**Comment by josefnpat** [comment]
requires assets before I can implement.
Attach assets here then assign to me

**Comment by softsound** [comment]
Test assets will come back to.
![puff1](https://cloud.githubusercontent.com/assets/1772703/24932734/7d29f100-1ed8-11e7-9386-8f37c1ada7e1.png)

![puff2](https://cloud.githubusercontent.com/assets/1772703/24932738/83d1ac1e-1ed8-11e7-98c4-bd18da0ac07f.png)

![spray](https://cloud.githubusercontent.com/assets/1772703/24932742/895ce518-1ed8-11e7-898b-024fec43c357.png)

**Comment by josefnpat** [comment]
Depends on #19

**Comment by softsound** [comment]
test assets

![bluecloud3](https://user-images.githubusercontent.com/1772703/37165408-2d4951fa-22c2-11e8-8e22-db95d699096d.png)
![bluecloud4](https://user-images.githubusercontent.com/1772703/37165409-2d66c3fc-22c2-11e8-8efc-f1c662768b17.png)
![bluecloud1](https://user-images.githubusercontent.com/1772703/37165410-2d809f34-22c2-11e8-8322-008b3addaaa7.png)
![bluecloud2](https://user-images.githubusercontent.com/1772703/37165411-2d9a4f38-22c2-11e8-95f3-70aac4aa9a69.png)

![cloud1](https://user-images.githubusercontent.com/1772703/37165421-33db53c4-22c2-11e8-9565-e2a6b80b0b11.png)
![cloud2](https://user-images.githubusercontent.com/1772703/37165422-33f23ddc-22c2-11e8-9e9a-0c757efeeac8.png)
![cloud3](https://user-images.githubusercontent.com/1772703/37165428-38cc0ab8-22c2-11e8-941b-83f3353bed1f.png)
![cloud4](https://user-images.githubusercontent.com/1772703/37165429-38e90a96-22c2-11e8-8500-16061e482ec8.png)

**Comment by josefnpat** [comment]
![ore](https://user-images.githubusercontent.com/646162/37381077-5b9fd740-2709-11e8-815e-c18084f9d6ff.gif)
![refine](https://user-images.githubusercontent.com/646162/37381079-5c9030c8-2709-11e8-8386-6005fa711d13.gif)
![dust](https://user-images.githubusercontent.com/646162/37381082-5dec7ed6-2709-11e8-97ea-4b98e0a244f8.gif)
