### ISSUE TITLE
GamePress

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#207]
http://www.gamespress.com/

![image](https://user-images.githubusercontent.com/646162/27711901-43c8be00-5cea-11e7-83ec-d3e4490c2f40.png)

**Comment by softsound** [comment]
This will be moved into a presskit feature request and closed.

**Comment by josefnpat** [comment]
@softsound the GamePress page has not been made (and therefore is not a "repeatable" thing for demo events). Unless this is a duplicate ticket, it needs to stay open.
