### ISSUE TITLE
Convey Panic Better

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#215]
Inform players when a wave hits, when there ships are destroyed or attacked and when they should panic.

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/27766018-2a506c62-5e88-11e7-8767-3a35dc45547c.png)

**Comment by josefnpat** [comment]
hit me up when assets are ready

**Comment by softsound** [comment]
![question](https://user-images.githubusercontent.com/1772703/27841479-543b0d20-60c7-11e7-9468-7850543d294d.png)
Question

![alertmessage](https://user-images.githubusercontent.com/1772703/27841481-5d3d7192-60c7-11e7-9134-6f1c4c88b4c5.png)
Alert

![warning](https://user-images.githubusercontent.com/1772703/27841485-657d7078-60c7-11e7-864a-fa64d1aa2d43.png)
Danger

**Comment by josefnpat** [comment]
Resolved in SP
