### ISSUE TITLE
Create graphical UI

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#24]
Talked to @softsound about this

- [ ] @softsound creates mockups
- [ ] @josefnpat creates UI interfaces and adds bloom
- [ ] @softsound designs individual sprite components
- [ ] @josefnpat implements said designs

**Comment by josefnpat** [comment]
Talked to @softsound about this

- [ ] @softsound creates mockups
- [ ] @josefnpat creates UI interfaces and adds bloom
- [ ] @softsound designs individual sprite components
- [ ] @josefnpat implements said designs

**Comment by softsound** [comment]
![map_bg](https://cloud.githubusercontent.com/assets/1772703/24737933/d33bfe7e-1a57-11e7-9efb-e465c7ce629d.png)

**Comment by softsound** [comment]
![window](https://cloud.githubusercontent.com/assets/1772703/24737943/dbb2c470-1a57-11e7-88eb-d99b1b0ca8a6.png)

**Comment by softsound** [comment]
![icon_bg](https://cloud.githubusercontent.com/assets/1772703/24737954/f4d9fa40-1a57-11e7-8ae7-76bac880dc7c.png)

**Comment by josefnpat** [comment]
Reassigning to @softsound so she can confirm it's what she wants

**Comment by softsound** [comment]
![window](https://cloud.githubusercontent.com/assets/1772703/24739558/27bd123a-1a62-11e7-93ef-d167c36213f9.png) removed blue

**Comment by softsound** [comment]
![icon_bg](https://cloud.githubusercontent.com/assets/1772703/24739777/5060476a-1a63-11e7-9243-f7cc8d27eccb.png) added blue to help with balance
