### ISSUE TITLE
Keep distance from enemy *will test*

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#241]
Do not fly straight into enemies face and start shooting like an inch away, at least try to maintain some distance.

**Comment by josefnpat** [comment]
What units do this?

**Comment by softsound** [comment]
related to other ticket about enemy distance can't find number but it was assigned to you.

**Comment by softsound** [comment]
#255

**Comment by josefnpat** [comment]
Please explain why or what this ticket is, or close it. We don't need duplicates.

**Comment by josefnpat** [comment]
"The point of this ticket is that some ships got too close to the other ships and they would not shoot before they were right next to the other ship"
