### ISSUE TITLE
Don't assume player will always have focus on game

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#251]
e.g. VN, splash, etc

**Comment by Nixola** [comment]
May I suggest adding a setting in the option, letting the user choose whether to autopause on focus loss? (And/or try using love.window.isVisible instead of hasFocus, but I'm unable to test that)

**Comment by josefnpat** [comment]
I believe this ticket is originally a part of the old system that paused the game when it lost focus.

This is no longer the case for the deployable part of the game.
