### ISSUE TITLE
Enemy AI wander can't be interrupted?

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#255]
>Enemy AI can't cancel it's patrol until it's reached it's destination which means you can roll up on an enemy as it's just kinda moving about and kill it before it moves it's 3 feet or whatever and it won't even think to fire back

**Comment by softsound** [comment]
Please confirm

**Comment by softsound** [comment]
Still an issue sometimes

**Comment by josefnpat** [comment]
don't assign this to me unless there's repro

**Comment by josefnpat** [comment]
"I think it's fine." ~ @softsound
