### ISSUE TITLE
Gate & Key System change levels

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#260]
Find a key to load unlock the gate to portal. Portal still must charge after it has been activated. A small light on the portal and the portal itself should change to reflect it's ready for use. Players can move ships through portal to next level. 

Extra ideas:
Damaged portals will bring damaged ships & or destroy some ships in the next level.

The correct key must be used with the gate, sometimes enemies drop fake keys. Some areas may only have key pieces which need to repaired and restored to create a full key.

**Comment by josefnpat** [comment]
Closing since SP is slated for removal
