### ISSUE TITLE
Levels may spawn "lost" or "damaged" ships. *Character/story tie-in*

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#261]
These ships are ships not yet researched. Sometimes story characters will be on these ships and thank you for your help.

Excuse to make more characters and story lol.

**Comment by josefnpat** [comment]
Please put this in the backlog or make this into an actionable ticket

**Comment by josefnpat** [comment]
Have levels spawn neutral ships for players to take over

**Comment by josefnpat** [comment]
a5199b56132038041ffd504758cc5c68a0d9ba4f
