### ISSUE TITLE
Cursor Action

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#271]
Have the cursor reflect the action of the selected ship. 

If an _offensive ship_ is selected and the _player hovers over the enemy_ change the cursor to _cross-hairs_.

So if x ship is selected 
then if y action is an action that can be performed 
show a cursor change to reflect that.

This should remove more unnecessary UI items too. 

Assets will be added to this ticket when done.

*side note* Would be super awesome if color showed action type - red attack, yellow collect, green build, blue recover...

This ticket will reference ticket #273 

This will help with [ticket 185 ](https://github.com/josefnpat/roguecraft-squadron/issues/185) and also [ticket 240](https://github.com/josefnpat/roguecraft-squadron/issues/240) may also affect [ticket 218](https://github.com/josefnpat/roguecraft-squadron/issues/218)

**Comment by softsound** [comment]
For this milestone this ticket would be good if we could get these actions finished.

Ship attack icon -
Selecting an offensive ship then hovering over an enemy brings up cross-hairs

Ship collect icon -
Selecting a salvager ship then hovering over scrap brings up a shovel icon

Ship mine icon
Selecting a miner ship then hovering over an asteroid brings up drill icon

_if time allows_ 

ship follow icon
selecting a ship then hovering over another player ship brings up follow arrow icon

**Comment by josefnpat** [comment]
I've gone through the ships, here are the actions that we have:

1. Move (All ships with move on nothing)
2. Attack (All ships with shoot on enemy)
3. Guard/Follow (All ships on ships)
4. Takeover (All ships with takeover on enemy/neutral ships)
5. Crew Gather (Habitat on Neutral with crew)
6. Ore Gather (Mining Rig on Neutral with ore)
7. Scrap Gather (Salvager on Neutral with scrap)

**Comment by josefnpat** [comment]
Closed by a00fdbfdf58e273fc0dde0502ee35c316fdb869c
