### ISSUE TITLE
Minelayer Type Ship Assets

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#272]
Bomber type ship for enemy and player assets will go here.

**Comment by josefnpat** [comment]
https://en.wikipedia.org/wiki/Minelayer

**Comment by josefnpat** [comment]
Only need it for the player

**Comment by josefnpat** [comment]
![bomberr](https://user-images.githubusercontent.com/646162/33414771-54471510-d558-11e7-8bd3-9a7750afc7d7.png)

**Comment by softsound** [comment]
Asset completed. Rework can be another ticket so I'm closing.

**Comment by josefnpat** [comment]
@softsound please link to ticket before closing

**Comment by josefnpat** [comment]
#442
