### ISSUE TITLE
Cursor asset recolors

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#278]
All cursors
_default_

**crosshair**
![crosshairblue](https://user-images.githubusercontent.com/1772703/33415164-6b3cd3a2-d55a-11e7-8514-d84ae9586b15.png)

**fist**
![fist](https://user-images.githubusercontent.com/1772703/33415228-cb497ae8-d55a-11e7-8f0a-15bfbe014bba.png)

**follow**
![follow1](https://user-images.githubusercontent.com/1772703/33415186-8f93bff4-d55a-11e7-9c82-7201b7bc290c.png)

**move here**
![movehere2](https://user-images.githubusercontent.com/1772703/33415446-3a8759ec-d55c-11e7-89e0-b21e590ed835.png)

**ore**
![ore](https://user-images.githubusercontent.com/1772703/33415387-c5e515d4-d55b-11e7-95e2-50477f9c011e.png)

**person**
![person](https://user-images.githubusercontent.com/1772703/33415418-0869e402-d55c-11e7-9137-536738a2f370.png)

**salvage**
![salvage_](https://user-images.githubusercontent.com/1772703/33415263-f605cc82-d55a-11e7-8c98-fafdf9ea7960.png)

_yellow_
![moveherey](https://user-images.githubusercontent.com/1772703/33415643-6d4328c4-d55d-11e7-8ba9-cdfa1b9ebe57.png)

![followy](https://user-images.githubusercontent.com/1772703/33415662-92e0016a-d55d-11e7-856a-882caa2a3626.png)

![fisty](https://user-images.githubusercontent.com/1772703/33415677-aa45d8a2-d55d-11e7-9366-fd20425f72f8.png)

![salvage_y](https://user-images.githubusercontent.com/1772703/33415688-c5b19a40-d55d-11e7-8d22-e60ee7938df3.png)

![orey](https://user-images.githubusercontent.com/1772703/33415698-e4a77a96-d55d-11e7-863f-1323247637af.png)

![persony](https://user-images.githubusercontent.com/1772703/33415705-fb589d74-d55d-11e7-8266-bd2a78db2af2.png)

![crosshairminiy](https://user-images.githubusercontent.com/1772703/33415722-21c9aa5c-d55e-11e7-81a5-c395fb8eba56.png)

_green_
![crosshairminig](https://user-images.githubusercontent.com/1772703/33415746-62ac1fa0-d55e-11e7-94b7-f1a06cca2f93.png)

![movehereg](https://user-images.githubusercontent.com/1772703/33415764-881f79bc-d55e-11e7-8450-8a189cbf6272.png)

![followg](https://user-images.githubusercontent.com/1772703/33415777-a81d4d98-d55e-11e7-98f1-142c0f868070.png)

![fistg](https://user-images.githubusercontent.com/1772703/33415803-bed42d4a-d55e-11e7-97cc-8295c2b85518.png)

![salvage_g](https://user-images.githubusercontent.com/1772703/33415820-d6026414-d55e-11e7-81f9-d46b951ac657.png)

![oreg](https://user-images.githubusercontent.com/1772703/33415846-ef3b383e-d55e-11e7-83cf-9d9210741039.png)

![persong](https://user-images.githubusercontent.com/1772703/33415858-074c0746-d55f-11e7-9033-0a56fe99db90.png)

_red_
![personr](https://user-images.githubusercontent.com/1772703/33415889-4df1e83c-d55f-11e7-873d-e3d5d3bb2788.png)

![orer](https://user-images.githubusercontent.com/1772703/33415905-6b9b45ae-d55f-11e7-8cea-b66b04f8bb6f.png)

![salvage_r](https://user-images.githubusercontent.com/1772703/33415932-81a67904-d55f-11e7-8215-3839f8766185.png)

![fistr](https://user-images.githubusercontent.com/1772703/33415955-9e3b40c2-d55f-11e7-8f25-4bdf4f1798d4.png)

![followr](https://user-images.githubusercontent.com/1772703/33415979-c004773c-d55f-11e7-8061-dc547420ddbf.png)

![crosshairminir](https://user-images.githubusercontent.com/1772703/33415994-da5ad6ee-d55f-11e7-9f46-aca4b79b4135.png)

**Comment by josefnpat** [comment]
Please put this in the backlog or make this into an actionable ticket

**Comment by softsound** [comment]
Style seems out of place. Closing ticket.
