### ISSUE TITLE
Create overview menu screen

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#282]
_This is used to give the player more control, and give them a sense of progression._

This menu should be very easy to open and close, ideally with 1 shortcut, and 1 mouse click on the icon.

# Overview will show:

**Ship Inventory** 
A screen to show many and what types of ships you have. Ideally, you could also select a group here or select a ship and find them on the map or on screen, it would be nice for people who lose their ships to have easy access to them or be able issue commands from this screen (IE return to center of screen).
This is also very useful when players are not sure how many of x unit has been built.

**Action Log** 
A log to show the creation and destruction of units, so players realize what they have lost. This is important because _events happen both off screen or on screen and some events may be hidden from view_ from the cloud update, as they build more units it will be progressively harder to see what happened to their ships. Without a method to enable them more control, players may grow frustrated.

**Commander Training & Missions**
This is where tutorials can be unlocked, as well as missions, completing this events will result in "science points (SP)" though I think command points(CP) makes more sense. These points can be used to further upgrade your tech tree and customize your game.

**Command Tree**
This tree gives you more options to upgrade and request improvements across the board while playing. For some ship upgrades though they will need to dock at a station to make improvements.

*Death gives you knowledge points (KP) which apply to the knowledge tree, so during and after every game you gain a sense of progression. Much like lol has item trees in game and rune trees outside game.

**Comment by josefnpat** [comment]
This either needs to be put into the backlog or made into actionable tickets
