### ISSUE TITLE
Make UI Style & Color Consistent

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#283]
It will be soft, bubbly, less in your face.

Example
![image](https://user-images.githubusercontent.com/1772703/34457463-977453b2-ed76-11e7-814f-eacf51cd2133.png)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/35661024-23d2a602-06d5-11e8-9f6e-3073f113b639.png)

**Comment by josefnpat** [comment]
This is very out of date.
