### ISSUE TITLE
(3) Rework Menus

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#287]
Rework the menus so they don't look so awful, and they can work better.

**Comment by josefnpat** [comment]
Relates to #269 #196

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/36885357-1087f370-1dac-11e8-814e-908e0ba1db14.png)

first step is to deal with this

**Comment by josefnpat** [comment]
@softsound Should we be hiding the game UI when the menu is up?

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/36951034-2d1d04f2-1fc4-11e8-861e-d021759f78c9.png)
![image](https://user-images.githubusercontent.com/646162/36951036-35acf190-1fc4-11e8-953d-f852acbd4fc5.png)
![image](https://user-images.githubusercontent.com/646162/36951039-409c6996-1fc4-11e8-9964-b5489080225f.png)


I think this is acceptable, at least for the milestone. Fight me.

**Comment by josefnpat** [comment]
Tell me if this is acceptable for the milestone. @softsound
