### ISSUE TITLE
(5) Rework fonts

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#288]
Rework fonts so they are not in front of things that are so busy. Consider:
1. Add dropshadow
2. Add tooltip backgrounds
3. Reduce clutter of frames

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/36838478-dfb55596-1d04-11e8-86d2-d1f6c3cb4e85.png)
![image](https://user-images.githubusercontent.com/646162/36838615-44b0b5da-1d05-11e8-80aa-6bec1bbe66a6.png)
![image](https://user-images.githubusercontent.com/646162/36838621-48dc2f0e-1d05-11e8-8ded-7db40a1de563.png)

**Comment by josefnpat** [comment]
@softsound @softsound tell me what you guys thing. Can i close this ticket, or is there something else we can do?

**Comment by josefnpat** [comment]
@softsound Here is the corner piece if you want to change it:
https://github.com/josefnpat/roguecraft-squadron/blob/master/src/assets/hud/tooltip_edge.png


We can change the RGBA on the corner and the background.

**Comment by softsound** [comment]
I think it looks good and better off simple without the flair. I think a better font would make it more readable.

These fonts had high readability:
http://atipofoundry.com/fonts/calendas-plus (I like this one for personal storytelling text)
https://www.behance.net/gallery/29964853/Recia-Typeface (This one is more generic feeling) 

Alas they require special licensing for games, even the pay what you what version.

Verdana, Arial and Courier are recommended for most readable fonts on average.

**Comment by josefnpat** [comment]
Would love some font feedback from @snowschu. Considering we just overhauled the entire UI, it might be time for a new font.

**Comment by snowschu** [comment]
[Monstserrat](https://fonts.google.com/specimen/Montserrat) is solid. I currently use it in my streams. Very readable.

[Open Sans](https://fonts.google.com/specimen/Open+Sans), [Roboto](https://fonts.google.com/specimen/Roboto), would also be great choices for body text (ie general text in the game).

My concern with using [Calendas Plus](http://atipofoundry.com/fonts/calendas-plus) only for the VN portion is that it separates itself from the rest of the game. It has a very classical book feel where we have a reasonably "hard core" space adventure going on in the game portion. Your suggestion of [Merriweather](https://fonts.google.com/specimen/Merriweather) would be a good candidate, but I don't particularity agree it should be used.  

If there's time @softsound, make a couple mockups.

**Comment by snowschu** [comment]
Another option for SXSW Milestone, the current font, [Yantramanav](https://fonts.google.com/specimen/Yantramanav), would be fine with a weight change. I suggest trying Medium (500) or Regular (400).

**Comment by josefnpat** [comment]
@snowschu I'll make the mockups by just testing them in game!

What is the license on Calendas Plus?

**Comment by snowschu** [comment]
@josefnpat the [site says](http://atipofoundry.com/license) we need to email them to use in a game.

**Comment by josefnpat** [comment]
Yantram medium:
![image](https://user-images.githubusercontent.com/646162/36955297-362eb8a0-1fed-11e8-9077-0d106e83ce06.png)

**Comment by josefnpat** [comment]
Yantram regular
![image](https://user-images.githubusercontent.com/646162/36955332-663a374a-1fed-11e8-807d-1d71a8e26129.png)

**Comment by josefnpat** [comment]
Merriweather Regular
![image](https://user-images.githubusercontent.com/646162/36955348-907549aa-1fed-11e8-9bd8-db23d100b8f1.png)

**Comment by josefnpat** [comment]
Roboto Regular
![image](https://user-images.githubusercontent.com/646162/36955372-b6ec1514-1fed-11e8-84a7-2f3b92e7f44b.png)

**Comment by josefnpat** [comment]
Open Sans Regular
![image](https://user-images.githubusercontent.com/646162/36955399-e0192526-1fed-11e8-8d69-68a9c87a7154.png)

**Comment by josefnpat** [comment]
ping @snowschu @softsound

**Comment by josefnpat** [comment]
Current: yamtram Black
![image](https://user-images.githubusercontent.com/646162/36955415-f8ee4b58-1fed-11e8-978a-3b4c20ee30ba.png)

**Comment by josefnpat** [comment]
I think @snowschu is right; yamtram medium feels very good.

**Comment by snowschu** [comment]
@josefnpat i believe @softsound was recommending [Merriweather](https://github.com/josefnpat/roguecraft-squadron/issues/288#issuecomment-370295250) for the VN portion of the game.  I don't recommend this (i mentioned back [here](https://github.com/josefnpat/roguecraft-squadron/issues/288#issuecomment-370288420)), but it's something we could look into after SXSW.

**Comment by snowschu** [comment]
I'm really liking [Yantramanav Regular](https://github.com/josefnpat/roguecraft-squadron/issues/288#issuecomment-370295101). The [Medium](https://github.com/josefnpat/roguecraft-squadron/issues/288#issuecomment-370294960) is nice but I'm still having some trouble focusing with it. [Open Sans](https://github.com/josefnpat/roguecraft-squadron/issues/288#issuecomment-370295575) is also a solid alternative. It's a bit wider and easy on the eyes.

**Comment by josefnpat** [comment]
Montserrat-Regular:
![image](https://user-images.githubusercontent.com/646162/36955702-9fe26a7e-1fef-11e8-9ee7-e1c4d19c4d98.png)
