### ISSUE TITLE
(4) Tutorial Rework/Cleanup

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#289]
Either clean up or redo the tutorial.

A rework design will not be implemented until it is agreed upon.

**Comment by josefnpat** [comment]
Relates to #252 #237 #217 #204 #192 #181 #135 #112 #96 #54

**Comment by softsound** [comment]
Please link to tutorial text asset.

**Comment by josefnpat** [comment]
https://github.com/josefnpat/roguecraft-squadron/blob/master/src/assets/loc/en.po

**Comment by softsound** [comment]
**Please remove:**

line 685
- msgid "vn.adj.8"
msgstr "Acquire resources to prepare for battle. Select the [Drydock] and Construct a [Mining Rig] to mine ore from a nearby [Asteroid]. Construct a [Refinery] to process ore into materials."

line 703
msgid "vn.com.9"
msgstr "Looks like they’re catching on. I’m glad there are some more [Asteroids] in this system to take advantage of."

line 706
msgid "vn.tip.3"
msgstr "Every ship has a [Salvage] and [Repair] action."

**Please change:**

line 687
- msgid "vn.tip.1"
msgstr "Select your ship with the left mouse button. Right mouse click to move selected ships. Use the icons [under the side panel] to perform actions. Move your mouse to the edge of the screen, use the arrow keys, or left click on the minimap to move your camera."

line 697
-msgid "vn.com.8"
msgstr "Well, that’s just dandy. I guess I better use some of those materials I processed to make a [Fighter] or two, and get rid of them."

line 799 
-msgid "tutorial.help.7"
msgstr "Select the command ship, and use the \"Build Salvager\" action in the [under the side panel]."

msgid "tutorial.obj.10"
msgstr "Build habitat ships to add crew. You'll need people to fly your ships. \n When you believe our fleet is ready, inform the Jumpgate Generator to jump to the next system."

line 826
-msgid "tutorial.obj.12"
msgstr "We have detected asteroids in this system. Later on we should use the Drydock to build some Mining Rigs to mine them."

line 829
msgid "tutorial.help.12"
msgstr "The command ship can later build Drydock stations. These Drydocks can build Mining Rigs.\n The Mining Rig works the same as the salvager, so you will need to right mouse click on an Asteroid to start mining it later on."

**Comment by softsound** [comment]
_I think when you buy new upgrades the tutorial for that item should be unlocked._

The UI screen has an Objectives icon represented by a Star, that when clicked on will open will have a    tab for unlocked tutorials. Here the player can review them as needed.

**Comment by josefnpat** [comment]
Closing since SP is slated for removal
