### ISSUE TITLE
(6) Rework Resource Display

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#290]
Rework the resource display.

Consider bars, icons, etc.

A design will not be implemented until it is agreed upon.

**Comment by softsound** [comment]
Current idea
![image](https://user-images.githubusercontent.com/1772703/37266771-8bbeb034-258a-11e8-985e-08ee5c292111.png)

**Comment by josefnpat** [comment]
We haven't had food for months. We're missing minerals. I am using the food icon for minerals.

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/37379017-a6d733b6-26ff-11e8-9f7b-b1045148e525.png)

Use this for materials.
