### ISSUE TITLE
OBS Recording Configuration Test

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#293]
Set up and test OBS recording on steam machines

**Comment by josefnpat** [comment]
Relates to #190

**Comment by snowschu** [comment]
I'll need access to the Demo machine. Still coordinating with @softsound to get the machine.


**_Plan:_**
To record the public playing the demo, to gage how they react to the game. Especially with the updates we'll be making for SXSW 2018.

The recording won't include audio or webcam video of any of the participants.

The recording -will- include the following:

- Game Capture
- Keyboard and Mouse click capture
- *Timestamp (This is extra. Using a timestamp and taking notes on when we discuss the game with people can be useful.)

Ideally, I'd like to have a 2 monitor set up: One for the player and one to see OBS (behind the table). I don't see this happening but something I'd like to keep in mind. This is plausible with a laptop with second monitor set up.

_**Risks or Conflicts:**_
- OBS will be on an on-going recording. There won't be time to start and stop the recording. This could be an issue if the HDD cant handle saving a recording that large.
     _Possible Solution: We can set OBS to start/stop recording with a Hot Key. We'd just need to make sure it's not a key that someone would accidentally press._ 
- The recording with OBS could cause the game to lag. This will be part of the test when I get the machine.
