### ISSUE TITLE
Marketing Materials

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#294]
Think up some more marketing materials.

Cards? Flyers? Buttons? A flag? i don't know.

**Comment by josefnpat** [comment]
Relates to #188 #146 #87 #86 #83 #59

**Comment by snowschu** [comment]
I need the files from previous material made by @softsound. For reference on what was used and possible recycling.

**Comment by snowschu** [comment]
Need to come up with an Elevator Pitch for the game.

**Comment by snowschu** [comment]
One thing we'll want to focus on is getting people to keep up with us and that we can use them to continue play testing our game, as well as spreading the word (via Social Media and Lets Plays).

These are something I'm looking to deal with for SXSW (they aren't in priority order):
- Newsletter
      This would need to be a MSS issue, rather than specifically a RCS issue.
      We'd need to discuss what type of content would go into the newsletters, and what we plan to offer people for signing up. I have some ideas for this, but this can be discussed later.
- Business Cards
      Several options for this.
      - We can have specific cards, tailored to each of us (so people remember who they talked to)
      - Generic card. With RCS on one side and MSS on the other
      - RCS card with a link to a download (like you have now). Would also include QRcode.

I've left buttons out, as much as I would like to make some. I don't believe RCS is at the stage for that kind of marketing. If we want some made, I'd push for MSS buttons more than RCS buttons.

These are somethings I'd like us to consider after SXSW:
- Discord and Reddit
      These are another way we can get people to stay in touch with us. I am unsure if its too early to include a Reddit, as we'd need people to moderate it, but something to keep in mind. And we have the Discord, which is currently being used as a dev depot.
- Table Banner
      This would be used for demoing. I don't believe we need this right now, but its something to keep in mind as we continue to develop RCS. 
- Entering RCS into contests
      This would be a great opportunity to get more exposure on RCS. Hopefully landing some awards.

**Comment by josefnpat** [comment]
![flyer_hooper](https://user-images.githubusercontent.com/646162/36828185-d9465740-1cdd-11e8-8074-9c5a6de8cd73.png)

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/36828333-bb017516-1cde-11e8-9ee6-a3a20a6c88a9.png)

**Comment by snowschu** [comment]
If you're looking to give away [x] free copies at SXSW, I will need to get a list generated of those URLs so I can print them.

Currently, I'm thinkin' of printing the URLs on labels and sticking them to the business cards.

**Comment by snowschu** [comment]
@josefnpat @softsound 
What are your feelings on the game being labeled with "Early Access" or "In Development" or "Beta" on Marketing materials? 

This question isn't about "yes, we need this" or "no, we don't need this." This question is about your feelings and opinions about these words. You may say that you like or dislike, but please explain why. 

I feel that its important to let people know we're still working on this and that its not the final product. I don't know where it's going to go, how big it'll be on the material, or even if I'm putting it on there at all. Please feel free to suggest other words.

**Comment by josefnpat** [comment]
We currently have this in the game:

`"msgstr "DISCLAIMER:\nRogueCraft Squadron is still in active development and may not represent the final product."`

I think it's fair to call it "In Development"

**Comment by snowschu** [comment]
@josefnpat This doesn't answer my question of how you feel about having post cards, business cards, or other marketing material printed/advertised, stating that the game is "in development". I did state Marketing materials in my post and I was aware that it is in the game itself.

"I don't care" or "It's not an issue me, go for it" are acceptable answers.

**Comment by josefnpat** [comment]
@snowschu Yeah, let's do it; name a budget!

**Comment by snowschu** [comment]
![businesscard front and back](https://user-images.githubusercontent.com/34079393/37260678-0b86cd46-2564-11e8-8afc-b59be81a2c08.png)

This is just a generic card we can use at the booth. I'm looking to print out the "free copy" URL's on return address labels (still looking. Will pick up locally). I am also going to print the discord URL similarly to the free copy. #WeclomeToTheClub kind of feel.

I will suggest we bring your personal cards to the show.

**Comment by josefnpat** [comment]
not sure if it's here, but I would love to have a hard copy paper for people to sign up for the mailing list. Please ensure that this list has the required fields that mailchimp requires.

**Comment by snowschu** [comment]
Update:
Business Cards may be delayed in delivery. As a back up: I will make some cards at home to use for day one. #StaplesOrBust Obviously I'll know more about where its at tomorrow (Wednesday).

One flyer for table will be done by tomorrow. You'll get a screenshot when its near complete and you'll be able to give feedback before I print it.

**Comment by josefnpat** [comment]
If I am unavailable, use best judgement <3
