### ISSUE TITLE
Review and update survey

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#295]
http://roguecraftsquadron.com/feedback

**Comment by josefnpat** [comment]
Relates to #80

**Comment by josefnpat** [comment]
Be sure to ask if you like the music!

**Comment by snowschu** [comment]
Updated survey: https://docs.google.com/forms/d/e/1FAIpQLSfDOsoMBiRSCNxZ_q7UIDTF9HAg3Xak5P3b9cAliZmsmFFgtw/viewform

Form includes email question first. None of questions are mandatory. This will take the pressure off of 'needing' to do the whole form.

Low tech solution:
I'm currently going to print out at least 10 surveys (one survey came out to 3 pages) and one sheet for email sign up.
