### ISSUE TITLE
Update Credits

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#303]
Add @snowschu to credits.

Before I can do this, I need to know:

1) What name you would like (e.g. Josef Patoprsty)
2) What social name you would like (e.g. @josefnpat)
3) What position you would like to be marked down as (e.g. Lead Developer)

Once you figure out these three, please reassign ticket to me.

**Comment by snowschu** [comment]
1: Ashley Schuster
2: SnowSchu _(I dont know if this is suppose to be linked to anything in particular. [@ArtSchu](https://www.twitter.com/artschu) is twitter but everywhere else I'm SnowSchu)_
3: Marketing and Testing

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/37381170-bc990b34-2709-11e8-8725-7a03ad4d830d.png)
