### ISSUE TITLE
Developing a Game Pitch 

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#304]
@josefnpat @softsound 
We need to come up with unified game pitch for RCS. Just a simple script that we all can follow when we approach people about the game. It also might not hurt if we think of answers to possible questions people might have while they play.

Note: We can save this for a standup meeting, if that would be more constructive.

**Comment by snowschu** [comment]
_(Taken from RCS video script and modified)_

Elevator pitch: 
RogueCraft Squadron is a futuristic spaceship strategy game with roguelike elements.

Target Audience: 
People who like RTS games and RogueLikes

Highlights of the game:
Collect materials, build ships, and research upgrades to grow a diverse group of space vessels, each having their own specialty, all while surviving against unwieldy enemies. And remember, death is not the end.

Things we’re working on:
Such as Story and Random Events, and looking to make it more open world.

**Comment by snowschu** [comment]
Pitch hasn't really changed that much. Even with the pivot to MP.

**Comment by josefnpat** [comment]
Please either:

1) Document this somewhere, make reference to it here, and then close the ticket
2) Update the current pitch or identify the current game pitch is up to date, and remove it from the milestone
