### ISSUE TITLE
Game Icon

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#308]
Right now I am just using the radar ship, but an official icon for the game would be awesome.

**Comment by softsound** [comment]
Would be better after reramp so we know what direction to go in. ETC

![image](https://user-images.githubusercontent.com/1772703/37136384-06d35382-2267-11e8-8982-10e8a6f778cc.png)

![image](https://user-images.githubusercontent.com/1772703/37136390-0ed100ca-2267-11e8-9635-0c744d121872.png)

![image](https://user-images.githubusercontent.com/1772703/37136439-5447137e-2267-11e8-88cf-f29a1d527c10.png)

**Comment by josefnpat** [comment]
@softsound can I get the RCS but with the black hole on the metal plate? I like dat - let's make it big so we can use it in other assets.

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/37187872-fa9aac36-2311-11e8-9710-a7c9aea4a302.png)

**Comment by josefnpat** [comment]
The first one is best, but use the darker edge, and pull out the RCS to the edges of the circle.

**Comment by snowschu** [comment]
ref. [this post](https://github.com/josefnpat/roguecraft-squadron/issues/308#issuecomment-371696403)
@softsound 
For brand constancy, I'd like to see a version where you use the ['metallic' plate](https://user-images.githubusercontent.com/1772703/37136789-ae6eafdc-2268-11e8-8625-a33079813220.png) with the RCS.

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/47099131-3ec61c00-d1fa-11e8-815d-cd11fe6809da.png)
?

I don't think the metal plate looks as good..

**Comment by softsound** [comment]
Okay well, erm, here are more options

![image](https://user-images.githubusercontent.com/1772703/47109088-f23b0a80-d212-11e8-8ec2-96895f79df9b.png)

**Comment by josefnpat** [comment]
I actually kind of like the balance of this one:

![image](https://user-images.githubusercontent.com/646162/47116852-6f24af00-d228-11e8-97c4-271643384eca.png)

@snowschu what do you think?

**Comment by josefnpat** [comment]
@softsound thinking it over a bit, I think we should go with this one. Can you make a 64x64 scaled up and cleaned up version of it as well?

**Comment by softsound** [comment]
I can try

**Comment by josefnpat** [comment]
Please try and keep it the same ship - scale it up and clean it up.

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/47122215-7e612800-d23b-11e8-9324-3d61be26cdd3.png)

**Comment by josefnpat** [comment]
Can you please make them transparent or something? The white background looks really bad.

**Comment by softsound** [comment]
Oh I thought they were transparent, and yeah I can fix that one up second.

**Comment by josefnpat** [comment]
![screen shot 2018-12-25 at 1 29 38 pm](https://user-images.githubusercontent.com/646162/50422266-5b5d8080-0849-11e9-9243-fc712224e557.png)

We need a high res version of this icon :(

**Comment by josefnpat** [comment]
I will attempt to make a 3d model and make a vector icon out of that

**Comment by softsound** [comment]
Here are some vectors to work with if you want to play around some ideas.
[someVectors.zip](https://github.com/josefnpat/roguecraft-squadron/files/2726003/someVectors.zip)

**Comment by josefnpat** [comment]
[rcs.svg.zip](https://github.com/josefnpat/roguecraft-squadron/files/2761796/rcs.svg.zip)
![rcs_512](https://user-images.githubusercontent.com/646162/51215157-ab2de580-18e5-11e9-8d67-e8498cb6ef48.png)
![rcs_256](https://user-images.githubusercontent.com/646162/51215161-acf7a900-18e5-11e9-880b-3a420529cf15.png)
![rcs_128](https://user-images.githubusercontent.com/646162/51215163-ae28d600-18e5-11e9-8c6c-fce05fbe0f1e.png)
![rcs_64](https://user-images.githubusercontent.com/646162/51215164-af5a0300-18e5-11e9-8da2-d7710f72cffd.png)
![rcs_32](https://user-images.githubusercontent.com/646162/51215167-b08b3000-18e5-11e9-92bb-f54fa9f49392.png)

**Comment by softsound** [comment]
[iconDesign2.zip](https://github.com/josefnpat/roguecraft-squadron/files/2765982/iconDesign2.zip)
![image](https://user-images.githubusercontent.com/1772703/51277280-c4459d80-199c-11e9-999d-ee6ef52379b5.png)
