### ISSUE TITLE
Add in mining/scrap collecting clouds

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#309]
Just test assets for now. Hope to update more later...

![bluecloud1](https://user-images.githubusercontent.com/1772703/37135884-eb2a2644-2264-11e8-9be8-65ac4f978ae7.png)

![bluecloud2](https://user-images.githubusercontent.com/1772703/37135886-ef8c76ce-2264-11e8-99b8-6b374ac02fa0.png)

![bluecloud3](https://user-images.githubusercontent.com/1772703/37135890-f2411546-2264-11e8-9021-d285e803361f.png)

![bluecloud4](https://user-images.githubusercontent.com/1772703/37135891-f5531068-2264-11e8-9e0f-3f08ab44748e.png)

![cloud1](https://user-images.githubusercontent.com/1772703/37135902-fb28f96c-2264-11e8-9c74-e387584d3f97.png)

![cloud2](https://user-images.githubusercontent.com/1772703/37135908-fdc927a0-2264-11e8-8ebb-a2db232154f6.png)

![cloud3](https://user-images.githubusercontent.com/1772703/37135922-0a84ffaa-2265-11e8-9535-f0e7df28fb34.png)

![cloud4](https://user-images.githubusercontent.com/1772703/37135930-0e70c234-2265-11e8-9651-6b561ee371de.png)

**Comment by josefnpat** [comment]
Please move these assets to #2, this ticket is a duplicate.
