### ISSUE TITLE
Redo Icons

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#31]
What sizes should we redo them at?

Some folks complain that 32x32 is too small.

**Comment by josefnpat** [comment]
Ship icons are now auto generated

![image](https://cloud.githubusercontent.com/assets/646162/24902110/c5170af8-1e6e-11e7-8f12-007927e7aced.png)

Game will now require `make love` to run.

15fad12eb1efd206445c99d63fbdcfded89f16c9

**Comment by josefnpat** [comment]
North Austin Gamers say icons are too small

**Comment by softsound** [comment]
Creating New Icons (This ticket will continue to be updated):
 
Collect
[image](https://user-images.githubusercontent.com/1772703/26999747-eae4b8c6-4d66-11e7-9817-bf25fe3e62ce.png)

Build
![image](https://user-images.githubusercontent.com/1772703/26999752-13e5e808-4d67-11e7-9b5b-0c282164ac91.png)

**Comment by josefnpat** [comment]
Very nice! I like this version the best: 
![image](https://user-images.githubusercontent.com/646162/27003942-683e0e6c-4dc6-11e7-87de-71072ce91fc9.png)

Make sure you keep the originals w/ transparency so we can push them all in the game!

**Comment by softsound** [comment]
Yeah just gave them a purple background because transparency is hard to see with white.
![collecticon](https://user-images.githubusercontent.com/1772703/27004421-8f21086a-4dce-11e7-8e9d-1db846702e8b.png)

**Comment by softsound** [comment]
I will update the above shortly.

![image](https://user-images.githubusercontent.com/1772703/27250007-66d65ff2-52e9-11e7-85b3-4bbeea9a7bb5.png)

Icons can divided into different groups. These icons are for single actions (this combat ship attacks the enemy) and group actions (all combat ships attack the enemy).

The click is the animation for click/hover.

**Comment by josefnpat** [comment]
Icons look strange at 64x64. Let's move this out of the sprint so we can get this right.

![image](https://user-images.githubusercontent.com/646162/27841098-216cd624-60c4-11e7-8af9-1de94c4096e1.png)
![image](https://user-images.githubusercontent.com/646162/27841101-2397e722-60c4-11e7-9eed-ec9cfe33e4d2.png)
![image](https://user-images.githubusercontent.com/646162/27841102-25accfbe-60c4-11e7-8e59-482d92470f5f.png)

To change the icon size to 64x64:

from `libs/window.lua`:
```patch
-  self.icon_size = init.icon_size or 32
+  self.icon_size = init.icon_size or 64
```

from `states/mission.lua`:
```patch
 function mission:iconSize()
-  return 32
+  return 64
 end
```

**Comment by softsound** [comment]
Hmm, use the regular tooltip for icons, fits better. 

Hmm. It would be nice if when you hovered over an icon it grew bigger or a larger version appeared over it. I will think more on this ticket.

**Comment by josefnpat** [comment]
Now that actions are all auto or mouse based, this ticket doesn't really make sense any more. Closing it.
