### ISSUE TITLE
slighted player from jump ship

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#310]
"Once my jumpgate ship died, I was disappointed to learn that I had no capability to build another one. I spent the next ten minutes scouring the map for a way to proceed and felt slighted as a player."

Remove jump ship - put jump controls on main ship. 

Honestly, makes more sense anyway. How did the main ship get there without jumping? This should remove confusion.

**Comment by josefnpat** [comment]
Closing since SP is slated for removal.
