### ISSUE TITLE
Make devlog easy to find

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#311]
Add our devlog and our youtube channel to the main website.

DevLog: https://josefnpat.itch.io/roguecraft-squadron/devlog
YouTube: https://www.youtube.com/channel/UCu7KmGfrFprPWAkKdGJOiTw

**Comment by snowschu** [comment]
Ref back chat conversation:

Itch.io text >to> Download 
DebBlog >relinked to> itch.io devlog
