### ISSUE TITLE
Recreate demo video (3.5)

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#312]
Recreate the demo/trailer.

Script: https://docs.google.com/document/d/128WJ_f0Oi4HjrWZXQYbZQ38EzJmmmqpuMH2lm8U30NQ/edit?usp=sharing

Reference: https://www.youtube.com/watch?v=IMLxxkWiuaU

Will probably want to use elliot's music. That will come later this week, so this ticket will be blocked by that.

**Comment by snowschu** [comment]
Update from March 24th with new milestone.

Will need to determine which build we're going to use for the demo: SXSW Build or new multiplayer build.

**Comment by softsound** [comment]
Did we ever get music?

**Comment by softsound** [comment]
Also referencing older ticket in the hopes we can close it. #59

**Comment by snowschu** [comment]
Summary of meeting:
We have two types of videos we'll want to have:
- Demo video (which we've had): This is a longer video, showing off the gameplay, mechanics, and a bit of story.
- Trailer: This is a shorter video (roughly 30s - 1min30s) that is shows the highlights of the game in quick succession and "pumping up" the user.

Once we have more of the updated/revamped MP fleshed out, I'll start working on the demo.

edit: Ref #59 as a duplicate.  This comment has been reposted from #59. #59 will be closed.

**Comment by josefnpat** [comment]
Please identify what tickets are blocking this!

If it's a general "there's too many" we need to identify the minimum tickets I can close that we can make it happen, or at least prepare a workflow so we can "drop updated footage in"

This applies to #453 as well

**Comment by josefnpat** [comment]
Mixed Music: https://drive.google.com/drive/folders/1dXHSmnuTyd0bAG5H4-q1p_fOC4-Qk3Ee?usp=sharing

**Comment by josefnpat** [comment]
Logo:
![image](https://user-images.githubusercontent.com/646162/51630746-928a8480-1f10-11e9-9b44-952b2a8b6418.png)

Please make sure it's scaled pixel perfect.

**Comment by josefnpat** [comment]
https://github.com/josefnpat/roguecraft-squadron/blob/master/dev/logo/logo.png

**Comment by josefnpat** [comment]
https://docs.google.com/document/d/1mMEdgc99vARCwImSFg4-0Heuko8fMeYm8ZWBm1nNa-I/edit

**Comment by josefnpat** [comment]
Check folder from guy
