### ISSUE TITLE
Add jump UI

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#314]

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/37265207-de63f732-257f-11e8-8cc2-59186c9825b7.png)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/37266098-f1391f44-2585-11e8-81f2-039d6719ec15.png)

Ideally would have jump button, green when ready, red when not.

![image](https://user-images.githubusercontent.com/1772703/37266123-3c305378-2586-11e8-8a5e-2ab126c201dc.png)

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/37326490-5daad43a-2660-11e8-984c-c1b7d7ec1626.png)

**Comment by snowschu** [comment]
Ref [this:](https://github.com/josefnpat/roguecraft-squadron/issues/314#issuecomment-372192568)

is the jump button suppose to be next to the bar? if so, i like it.

**Comment by josefnpat** [comment]
I could do that. The problem is that the rest of the icons wouldn't do anything. Isn't that a problem from a UI/UX perspective?

**Comment by softsound** [comment]
Just leave what you have, it will confuse players until the UI is changed later.

**Comment by josefnpat** [comment]
Closing for milestone
