### ISSUE TITLE
Action UI

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#315]
Move actions to left side in column

**Comment by softsound** [comment]
Like so

![image](https://user-images.githubusercontent.com/1772703/37266287-3fb74c6c-2587-11e8-8ed7-05ad2b5e3a23.png)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/37315455-d1f8306e-2627-11e8-8445-381850b238e2.png)

**Comment by josefnpat** [comment]
The action section has been added to MP. This is not needed as SP will be removed.
