### ISSUE TITLE
Buy new demo gear

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#316]
Get cheap:

* 2x matching headphones
* 2x matching mice
* 2x matching mousepads (Micepads?)

**Comment by josefnpat** [comment]
If anyone is at or near a five-below, I'd be happy to reimburse them.

**Comment by softsound** [comment]
2x new computers lol.

**Comment by josefnpat** [comment]
Thank you @softsound

**Comment by snowschu** [comment]
Confirmed that we got the items 2x( Headphones, Mouse, Mousepads)?
