### ISSUE TITLE
Generic UI Overview

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#317]
Catch all ticket for UI.

Current UI Goal for SXSW:

![image](https://user-images.githubusercontent.com/1772703/37266574-196ca348-2589-11e8-81d4-72bcad2cfc82.png)

Will add icons & such if you need them in comment below.

**Comment by softsound** [comment]
![gearoutline](https://user-images.githubusercontent.com/1772703/37266704-18be209c-258a-11e8-964f-0cfcab6bb76f.png)
![messageoutline](https://user-images.githubusercontent.com/1772703/37266705-18d115f8-258a-11e8-82fd-c05154b8f1d2.png)
![staroutline](https://user-images.githubusercontent.com/1772703/37266706-18e30be6-258a-11e8-9671-877e5e2bc3a5.png)
![personoutline](https://user-images.githubusercontent.com/1772703/37266707-18f58172-258a-11e8-8849-7b24ef2f0123.png)
![oreoutline](https://user-images.githubusercontent.com/1772703/37266708-190fe684-258a-11e8-8491-7f38673cc6d4.png)
![energyoutline](https://user-images.githubusercontent.com/1772703/37266709-19215a90-258a-11e8-9ed1-8541d0e975ab.png)
![foodoutline](https://user-images.githubusercontent.com/1772703/37266710-19338242-258a-11e8-95b8-a8a2c01724fe.png)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/37378935-3e42286a-26ff-11e8-8841-34f724891957.png)

**Comment by josefnpat** [comment]
see #409
