### ISSUE TITLE
Create minerals icon

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#319]
see comment on #290 

32x32

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/37379071-e730e7ae-26ff-11e8-954b-24dc10fb3202.png)

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/37379174-5a62294a-2700-11e8-863a-16b9d12d1f91.png)

Please provide transparent image

**Comment by softsound** [comment]
![scrapicon](https://user-images.githubusercontent.com/1772703/37379338-1e9da500-2701-11e8-8e64-afb083203975.png)

try that

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/37379484-a47555ec-2701-11e8-81f2-f387d5c4a8c4.png)
Thank you!
