### ISSUE TITLE
Bug: Game won't load on Mac OS X

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#324]
Running on Mac OS X High Sierra (10.13.5)
Game downloaded from itch.io browser and itch.io client
version 459[git:4f2ac6]
Game unzips into a .app (no folder, just the .app)

Game freezes on launch

_Game does load on Mac OS X Yosemite 10.10.5_

Possible issue: Current security updates for 10.13.5 could be causing conflicts with non-apple-vetted applications. Needs more testing.

**Comment by josefnpat** [comment]
@snowschu can you show a screenshot of it frozen?

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/37386085-d06afe90-2724-11e8-9d76-674e2b53ce0d.png)


seems to lock up - might be graphics driver problem - check out macs

**Comment by snowschu** [comment]
Log: Force Quitting the problem, terminal reported:  Killed 9

**Comment by snowschu** [comment]
Setting this into Backlog. Game currently loads fine on Mac OS.

**Comment by josefnpat** [comment]
May relate to #384

**Comment by josefnpat** [comment]
`@🇩🇪 ๖ۣۜMarty#5595 ` reports that it locks up in this fashion on macOS 10.13.6.
Workaround: extract the contents of the .love file, and it runs.

**Comment by josefnpat** [comment]
Runs on macOS 10.10.5 - seems to lock up for a bit on launch, no GL context
