### ISSUE TITLE
Contact Musician

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#329]
See if they'll commit for more music. Possibly a full soundtrack.

Also possibly sfx

**Comment by josefnpat** [comment]
We current have a track by [Elliot Krasny](https://twitter.com/ElliotKrasny). I will contact him to see if he wants to make more music and/or sound effects.

**Comment by josefnpat** [comment]
Elliot has gone dark - switching over to Ran Schonewille
