### ISSUE TITLE
New background

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#332]
Make a new background

**Comment by snowschu** [comment]
I believe this conversation was about the game background being updated.

**Comment by josefnpat** [comment]
@softsound says this is for the starfield

**Comment by softsound** [comment]
? starfield

Okay well I can do both.
Here is background
[stars2_front.zip](https://github.com/josefnpat/roguecraft-squadron/files/2371865/stars2_front.zip)

Here are stars
[starPack2_front.zip](https://github.com/josefnpat/roguecraft-squadron/files/2371869/starPack2_front.zip)

Pick your favorite image from these zips each is 2048x2048 if you need them bigger please tell me.

**Comment by josefnpat** [comment]
Please leave open so I can implement it.

**Comment by josefnpat** [comment]
please add 4096x4096

**Comment by softsound** [comment]
Seamless background
![seamlesspurple](https://user-images.githubusercontent.com/1772703/45462412-4eb78100-b6cd-11e8-9db9-a35ee1deac46.png)

regular
![purplepack_back](https://user-images.githubusercontent.com/1772703/45462441-6b53b900-b6cd-11e8-94b9-d6ee857c5760.png)

**Comment by softsound** [comment]
Stars
![starwithcolor](https://user-images.githubusercontent.com/1772703/45464339-c8536d00-b6d5-11e8-9e0e-0809876cd52c.png)

what that would look like.
![image](https://user-images.githubusercontent.com/1772703/45464353-dacda680-b6d5-11e8-974a-e88bdb31a1f6.png)

**Comment by josefnpat** [comment]
bg awesome

redo stars (two layers, one big stars, one small stars)
