### ISSUE TITLE
Update Website Contents (2)

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#335]
Update website(s)

Why plural? Because we have a RCS and an MSS site. Both could use a "_spring cleaning_"

Tagging @josefnpat since he has the keys to the websites.

**Comment by softsound** [comment]
I will reference here other website related tickets.

#159 
#87

**Comment by softsound** [comment]
I suggest redoing RCS with a one page/landing page html5 template. Lots of free ones out there.

[](https://themewagon.com/free-html-landing-page-templates-responsive-multiverse/)

**Comment by josefnpat** [comment]
This ticket is blocked by #86

**Comment by softsound** [comment]
Presskit is ready just need video now

**Comment by softsound** [comment]
Slowly getting there https://softsound.github.io/Portfilo/#portfolio

**Comment by softsound** [comment]
Website content is done. Closing this ticket.
