### ISSUE TITLE
set up ssl on website correctly

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#339]
![image](https://user-images.githubusercontent.com/646162/37880920-76e4e694-3055-11e8-9c40-e2f55741fc83.png)

**Comment by snowschu** [comment]
Please set this up asap, @josefnpat. The longer we wait to fix this, the more instances that users will think we're being sketchy >.<

**Comment by josefnpat** [comment]
please enjoy

![image](https://user-images.githubusercontent.com/646162/45391677-8a791a80-b5e9-11e8-9609-ec776b207588.png)

**Comment by josefnpat** [comment]
https://certbot.eff.org/lets-encrypt/ubuntuother-apache
