### ISSUE TITLE
Mailchimp - Use User Accounts

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#341]
Our MailChimp account is requesting security to be added to the account. While we -can- add it, the account is under @josefnpat's name. We should be using user accounts so we don't have to go through a security check every time. #SmarterNotHarder

Here's the link discussing Multiple user accounts: https://mailchimp.com/features/multi-user-accounts/

**Comment by josefnpat** [comment]
Doien, thanks!

**Comment by snowschu** [comment]
@josefnpat wrong account. set mail chimp up with ash.schuster [at] gmail [dot] com
