### ISSUE TITLE
Demo video does not loop

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#346]
Demo will run once then stop running. Some of said it works more often on one machine than the other.

**Comment by josefnpat** [comment]
I really need to fix this!

**Comment by josefnpat** [comment]
Ended up being an encoding issue. Love likes this:

`ffmpeg -i input.ogv -codec:v libtheora -qscale:v 10 -codec:a libvorbis -qscale:a 5 output.ogv`
