### ISSUE TITLE
Hide Resources From Mini Map?

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#355]
Also written as "Map hide resources"?

**Comment by josefnpat** [comment]
959e1b2d4401f6298fb4aabfe6c3d2a7541b3bae
d38a88b1a21a5113e4ddf040870209a2e3983de2
6c3dcf539e37be9e4ac23da8421815ca75108550
c80d9d114bf8fcbbac69bb3ca48358499c05abbf
