### ISSUE TITLE
Singleplayer (SP) bug - game crash on game startup in debug / cheater mode

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#365]
v475[git:2c5287b]
Process:

- Launch game
- Toggle `debug` and Enable `Cheat Mode` in the debug menu
- Start game -> easy mode
- Disclaimer loads
- Crash screen

![untitled](https://user-images.githubusercontent.com/34079393/40693758-ce2edd54-637e-11e8-9557-02665de0f454.png)

**Comment by josefnpat** [comment]
Cannot reproduce, please expand repro steps

**Comment by josefnpat** [comment]
Close tickets that you cannot repro unless there's another stage to the workflow.
