### ISSUE TITLE
Menu (Title screen) - Exiting issue

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#366]
No option to cancel the exiting process.

Currently we only have the survey option (yes to survey or no to survey) and no way for the player to opt-out of exiting the game and continue playing.

Solutions:
Add a `Cancel` button on the same line as `Sure!` and `No Thanks`.
-or- add a close button in the upper left or upper right corner of the popup window.

v475 [git: 2c5287b]

**Comment by josefnpat** [comment]
This will be resolved by #154
