### ISSUE TITLE
UI/UX: In-Game Screenshot functionality

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#367]
Ability to take a screenshot while in-game, without the use of 3rd party software. (or the non-useful `print screen` button).

Games on steam have the option to take a screenshot (usually with f12) and some games just have a configurable button that allows players to take a screenshot of the game, which saves to the game folder.

Not every player or playtester will have software that takes screenshots quickly and easily. This would be most useful to players, which would allow them to share moments from the game easily and when they report issues, and it would be useful to us, for playtesting and bug reporting. Having to open up  `snipping tool` or other software (on windows) is very time consuming.

Please consider adding this feature.

**Comment by softsound** [comment]
I second this request

**Comment by josefnpat** [comment]
Do we need this in for the release milestone? @snowschu @softsound

**Comment by snowschu** [comment]
Early Access release would be preferred. If the point of EA is meant to give us time to refine our game for Full Release, then something like this can help players gives us issues reports and general feedback. 

This also removes issues that the player could have if their current screen capturing isn't working with the game (examples: OBS can't see it, printscreen is borked, cant use snipping tool while ingame, etc).

If something like this will take longer than 1-2hrs, then please make this a priority for posts Early Access Release.

**Comment by josefnpat** [comment]
Sounds good, it'll be in.

**Comment by josefnpat** [comment]
I have added it in, mapped to F12.
