### ISSUE TITLE
Add research

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#378]
In reference to #79 

Todo:

- [x] Hook up `_unlock_[type]`
- [x] Hook up `damage`
- [ ] Look through `tree.json` for usable upgrades
- [x] Add disabled state on buttons for max
- [ ] Test on Newark server
- [x] Remove `potato`
- [x] Add UI for opening/closing research
- [x] Make sure research points gets updated
- [x] Determine way to give user research points

**Comment by snowschu** [comment]
_This comment will be updated with check marks and additional comments if needed._
- [ ] * ensure all build-able ships have a unlock cost
- [ ] * test demo with build modes
- [ ] * test release with build modes
- [ ] * test demo with research normal
- [ ] * test release with research normal
- [ ] * ensure that ships unlock when researched,
- [ ] * ensure that ships are not unlocked when not researched
- [ ] * test research for pacing / feel
