### ISSUE TITLE
Select all military/civilian units

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#390]

**Comment by josefnpat** [comment]
This has been requested twice from @VividReality - should this go into the release milestone?

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/47058532-13f0af00-d18b-11e8-9dd1-b2d0f3ccf211.png)

**Comment by snowschu** [comment]
Not needed for Early Access release. 

Revisit for Full Release.

**Comment by softsound** [comment]
I've wanted this for a very long time as a QOL thing. I want this in early access if you can put it in. This has been many menu designs since the beginning of the game.

**Comment by josefnpat** [comment]
By adding it to the steam release, you are committing us to it: not "revisit[ing] for full release"
