### ISSUE TITLE
Make new explosion assets

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#401]

**Comment by josefnpat** [comment]
http://explosiongenerator.com/

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/45403001-19a02580-b61e-11e8-9f79-c403bfe8e7cb.png)
[smoke1.zip](https://github.com/josefnpat/roguecraft-squadron/files/2373601/smoke1.zip)

![image](https://user-images.githubusercontent.com/1772703/45403023-33416d00-b61e-11e8-89df-46b2a84154ee.png)
[smackSmoke.zip](https://github.com/josefnpat/roguecraft-squadron/files/2373604/smackSmoke.zip)

**Comment by josefnpat** [comment]
Check video I sent to you - tell me if you like it.

**Comment by softsound** [comment]
Use these explosions and replace all old explosions.

[CorrectExplosions.zip](https://github.com/josefnpat/roguecraft-squadron/files/2380493/CorrectExplosions.zip)
