### ISSUE TITLE
Design server config screen

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#402]
Possible Features:

* Let players choose their team
* Let players add enemy/ally AI
* Set map size
* Set starting resources
* Set map resource density
* Set unit limit
* Set invasion mode

**Comment by josefnpat** [comment]
Starcraft: Brood War:
* Find servers: 
![image](https://user-images.githubusercontent.com/646162/41517029-cdb9952c-727d-11e8-8464-26a2832ca2fd.png)

* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41516991-a2172376-727d-11e8-844c-60ca5341525d.png)

**Comment by josefnpat** [comment]
Starcraft II:

* Connect to server: 
![image](https://user-images.githubusercontent.com/646162/41517037-d8fd98fc-727d-11e8-9d93-ffb73822da81.png)
* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517045-e4db1564-727d-11e8-941e-9bbb86eadf5a.png)

**Comment by josefnpat** [comment]
Conquest: Frontier Wars:

* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517069-0079e6ec-727e-11e8-95e6-c51a67f59545.png)

**Comment by josefnpat** [comment]
Warcraft II

* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517088-14328a36-727e-11e8-87c1-4de564d082aa.png)

**Comment by josefnpat** [comment]
Warcraft III:

* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517099-204fb8fc-727e-11e8-9e9f-d067b483558e.png)

**Comment by josefnpat** [comment]
Diablo II

* Connected to server ![image](https://user-images.githubusercontent.com/646162/41517156-65c01aee-727e-11e8-9f58-1e252f321c03.png)

**Comment by josefnpat** [comment]
League of Legends

* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517176-90d0a104-727e-11e8-807e-42d2509207ee.png)

**Comment by josefnpat** [comment]
Fortnite:

* Find server:
![image](https://user-images.githubusercontent.com/646162/41517228-ea903dd0-727e-11e8-8569-798236465f40.png)
* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517236-f2f7907c-727e-11e8-8f4c-6f84d2ca820e.png)

**Comment by josefnpat** [comment]
Surviv.io

* Connect to server: 
![image](https://user-images.githubusercontent.com/646162/41517266-2aed8662-727f-11e8-80ab-0a81ff523072.png)

**Comment by josefnpat** [comment]
Rise of Nations:

* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517278-501ae74a-727f-11e8-98bf-141075d88229.png)

**Comment by josefnpat** [comment]
Borderlands 2

* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517316-9d760e8e-727f-11e8-8248-7177012a46d9.png)

**Comment by josefnpat** [comment]
Guns of Icarus

* Connect to server: 
![image](https://user-images.githubusercontent.com/646162/41517341-d28f455e-727f-11e8-8952-cca8f4ea1cc0.png)

* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517347-d9445678-727f-11e8-8918-fadc8280935a.png)

**Comment by josefnpat** [comment]
Left for dead 2:

* Connect to server: 
![image](https://user-images.githubusercontent.com/646162/41517388-2e6f993c-7280-11e8-928a-82dc3ebcf024.png)
* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517391-372f6084-7280-11e8-84dc-1973dec7cbe1.png)

**Comment by josefnpat** [comment]
DOTA2:

* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517421-78803aea-7280-11e8-9b94-b482d72b3d47.png)

**Comment by snowschu** [comment]
Jack box games
- lobby
![lobby](https://user-images.githubusercontent.com/34079393/41517438-8c2b836a-7280-11e8-9d4f-c6ffd99e06f2.png)

-Connected to server/room
![download1](https://user-images.githubusercontent.com/34079393/41517443-93be8082-7280-11e8-952d-a4da4d6b347b.jpg)
![download](https://user-images.githubusercontent.com/34079393/41517445-9566190e-7280-11e8-80bf-1f5899f6ee46.jpg)

**Comment by josefnpat** [comment]
HALO1:

* connect to server: 
![image](https://user-images.githubusercontent.com/646162/41517453-a971c7f4-7280-11e8-8904-c880b72db4d5.png)

**Comment by josefnpat** [comment]
HALO 2

* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517498-f9d9c520-7280-11e8-8711-528f1b10c444.png)

**Comment by josefnpat** [comment]
HALO 3

* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517505-087d651e-7281-11e8-8932-143a994fec97.png)

**Comment by josefnpat** [comment]
World of Tanks:

* Connected to server: 
![image](https://user-images.githubusercontent.com/646162/41517533-483f0eaa-7281-11e8-8284-0f9c00bee3d9.png)

**Comment by josefnpat** [comment]
Connect to server: 
![image](https://user-images.githubusercontent.com/646162/41518226-a8921e14-7286-11e8-87b6-769b83d92217.png)

**Comment by softsound** [comment]
https://github.com/josefnpat/roguecraft-squadron/issues/415 combine ticket

**Comment by softsound** [comment]
Reasons against more than 5 players.

1) Each player makes the game longer, unless we don't have the resources to support them.
2) This isn't a fast paced party game, and there isn't enough strategy to support long term game, we don't have any real meta. The game is basically collect resources, kill the other person.
(Now if we have bonus for support such as defense boosts, faster reaction time, easier to store resources  and Research Bonuses or bonuses for sabotage such as resource stealing, hidden spies, traps, or stealing ships that could make the game more fun longer term. But as it stands, the game is too straightfoward and if someone becomes really powerful there is no way to turn the tide.)
3) This was never meant to be an MMO and it could become numerously more complex with every player added. 
4) There is no way to specialize, no lanes that someone could be good at, we don't have tanks or healers, or trap wielders. Specializing allows everyone to participate more in game because they have defined role they can fill. 


Reasons for having more than 5 players (Probably up to 10 players for reasons stated above)
1) Not a lot of games on the market offer larger group lan game play. Could be a selling point.
2) Could have a 5 person team vs another 5 person team to have everyone play together (still run into role issue)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/41747665-66930730-7574-11e8-98f6-8b2fbf79c39a.png)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/41888555-b30fb7f2-78cb-11e8-994c-7606c75969fe.png)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/45992882-9e913300-c051-11e8-94ec-732cef815913.png)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/47117513-3554a800-d22a-11e8-90fe-ac995a93e564.png)

**Comment by softsound** [comment]
Please review and offer feedback on this design.

**Comment by josefnpat** [comment]
This is a good start

* Please document what the undeveloped buttons do (e.g. Quick Game)
* Please tell me what is a variable. 
* Please tell me why everything is purple

**Comment by softsound** [comment]
Removed purple, tried to have the icons look sorta different colors.

Quick Game -> Demo mode 

![Uploading image.png…]()

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/47118617-6aaec500-d22d-11e8-8426-da4013867d60.png)

**Comment by josefnpat** [comment]
I need to know How they are variable.

Also, how is Add AI variable?

**Comment by softsound** [comment]
Oops you are right about the Add & Remove button, same with the lobby.

Ideas for team shapes:
![image](https://user-images.githubusercontent.com/1772703/47120703-448d2300-d235-11e8-8d50-bc32c065ee72.png)
