### ISSUE TITLE
Map movement: Edge detection

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#403]
The screen/map moves when you move the mouse to the edge of the screen (or WASD, but this is specifically for mouse use).  Can we adjust the point where the screen/map begins to move?   I feel like its too close to the Resource and Ship Building GUI.

**Comment by josefnpat** [comment]
Open `src\libs\camera_edge.lua` and edit these two lines:

```lua
camera_edge.vertical_mouse_move = 1/16.875
camera_edge.horizontal_mouse_move = 1/30
```

Tell me if you can get a better number.

This ticket is related to #405 - and may not be needed once it's fixed.
