### ISSUE TITLE
Figure out pricepoint.

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#411]
Current notes:

* It's always easier to go down than up.
* focus on consumer type (quantity vs quality)
* Consider A/B testing
* Have multiple options (bundles, add OST, etc)

[Competition spreadsheet](https://docs.google.com/spreadsheets/d/1Ifka7cwuenAKiSNZQqODM0sGmnMDBXPzcvYS8LQT8-o/edit?usp=sharing)

**Comment by snowschu** [comment]
Brief summary of an in person discussion:
Once we're closer to a beta release of the game, we'll have a better idea of what we'll want to charge for the game.

In the mean time, we'll continue researching.

**Comment by josefnpat** [comment]
Using 14.99 USD - please reopen ticket if this needs to be further discussed.
