### ISSUE TITLE
Demoing layout and design: lighting

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#412]
Look into some simple, portable light sources for when we demo games. This can be used beyond RCS.

Reasoning: The booths we had at SXSW and DH with IDGA had been a little darker than I would have liked. I think we should have some type of set up for when we encounter spaces like this.

Below are a couple affordable lighting options
- [IKEA: LED clamp spotlight](https://www.ikea.com/us/en/catalog/products/70386305/)
- [IKEA: LED 4 piece slight strip set](https://www.ikea.com/us/en/catalog/products/50192365/)
- [AMIR: TV LED light Strip](https://www.amazon.com/dp/B073NXF8B7/ref=cm_sw_r_oth_tai_i_TbfiBbKH6AG7S) _this one is cool because you can cut the strip down to fit your needs._
- [Lucky Wave: Ocean Wave projector](https://www.amazon.com/Projector-Romantic-Changing-Decorations-Projection/dp/B01D790XFC/ref=sr_1_15_a_it?ie=UTF8&qid=1528845982&sr=8-15&keywords=colored+lights) _Has a variety of colors. Could work as a backdrop projection_

_Some of these are USB, of which we can get a USB wall pug and use it in the power strip._

Feel free to post some other products or ideas below.
(Assigning @josefnpat to this as well, since it's more than likely that he'll be the one buying one of these.)

**Comment by josefnpat** [comment]
Thank you very much - i intend to go to ikea soon!

**Comment by snowschu** [comment]
![img_9655](https://user-images.githubusercontent.com/34079393/46835769-c59b7480-cd74-11e8-9510-8cd744d0190a.JPG)

Complete
