### ISSUE TITLE
Design alliance menu

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#415]

**Comment by softsound** [comment]
referenced in ticket #402

**Comment by softsound** [comment]
General UI layout

![image](https://user-images.githubusercontent.com/1772703/41636210-a87f51b6-7412-11e8-8c9f-cf0d16130b54.png)

**Comment by josefnpat** [comment]
I did this half awake

![image](https://user-images.githubusercontent.com/646162/46457722-fe39bd80-c778-11e8-9c26-a24bf7feec40.png)

6aa7ef939574636c872150970e639272455bb685
5c0bec0f9afe0295feb38af1fb5541b94dcf3658
