### ISSUE TITLE
Redesign Main Menu

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#417]
Have it be more eye catching with more ships and animation.
Have it have news/newsletter places we will showing off game, updates etc, and feedback button.
#194 
#40 
#154

**Comment by josefnpat** [comment]
@softsound is this in the backlog or in the milestone? please explain.

**Comment by snowschu** [comment]
I'm not particularly fond of references that can date* the game. I would encourage that we keep the menu simple with update notes, feedback link, website, and social media links.


* what does "date the game" mean? It means that it can make the game feel out of place or old when it hasn't updated (in any form) for a long period of time.

**Comment by softsound** [comment]
I think updates notes would be good, better then news, so I'll keep that in mind with the design.

**Comment by softsound** [comment]
RCS title menu should have be floating above a video of the gameplay. This will draw people in and we no longer need a demo video, people will also stop complaining about the main menu. I think 2-3 demo videos are good like in octopath.

[example](https://youtu.be/LHr8ct5_hgg?t=1m20s)

**Comment by softsound** [comment]
Demo Version (Note the grayed out buttons)
![image](https://user-images.githubusercontent.com/1772703/45986437-1ef36c00-c031-11e8-8db5-6d20faf1be6b.png)

Regular Version
![image](https://user-images.githubusercontent.com/1772703/45986526-a9d46680-c031-11e8-8ba1-1e3e20fc1ef0.png)

**Comment by softsound** [comment]
Here this is more realistic...
![image](https://user-images.githubusercontent.com/1772703/46125701-ec43a200-c1ef-11e8-87c8-0a9b664c4a5a.png)

And demo mode has single player mode grayed out.
![image](https://user-images.githubusercontent.com/1772703/46125745-1bf2aa00-c1f0-11e8-8699-e3fc8abbbec0.png)

**Comment by josefnpat** [comment]
Please make this into an actionable ticket.

**Comment by softsound** [comment]
Okay... Actions

- [ ] Add video to background of main menu

- [ ] Redo tooltips

- [ ]  Gray out buttons for demo mode

**Comment by josefnpat** [comment]
This ticket is salvageable.
