### ISSUE TITLE
New versions of game resets settings

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#429]
### OS:
Win10

### Version:
662

### Repro:

1. Download deps with `make deps`
2. Make 662 build with `make build_win64`
3. Checkout an older version (e.g 661) `git checkout bc21dc54bda597adcdc39830d6a9cbabbcf12d6f`
4. Make build 661 with `make build_win64`
5. Exract contents of both zip files in `builds` folder
7. Repeat following for both versions of game:
  a. Run and quit version from exe to build settings file. (e.g. `RogueCraftSquadron_v662-[031c7b5].exe`)
  b. Run version from exe
  c.  Enable debug mode
  d. Select Debug menu option
  e. Open save directory
  f. Take note of directory settings file is being saved to

### Expected:

RCS uses the same folder for save data. E.g.: `C:\Users\nothanks\AppData\Roaming\RogueCraftSquadron`

### Result:

RCS uses a folder name with the version in it, thus creating a new save folder. E.g.: `C:\Users\nothanks\AppData\Roaming\RogueCraftSquadron_v661-[bc21dc5]`

![image](https://user-images.githubusercontent.com/646162/42130911-28f58be0-7cb9-11e8-8f0c-a880e011d82b.png)
****

I suspect that the identity is not being set correctly. https://love2d.org/wiki/love.filesystem.setIdentity

**Comment by snowschu** [comment]
@josefnpat could you write out the repro for this? I haven't noticed any of my settings resetting and would like to see if I'm missing something in this bug.

**Comment by josefnpat** [comment]
@snowschu no problem

**Comment by josefnpat** [comment]
8cf096a
