### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#43]
* JR
* Other Meetups
* Replay System with open testing?

**Comment by softsound** [comment]
**Austin Mobile & Indie Game Dev** might be able to demo there

**Comment by softsound** [comment]
Also http://juegosrancheros.com/residencies/

**Comment by softsound** [comment]
**AustinGeeksAndGamers**
https://www.facebook.com/groups/AustinGeeksAndGamers/

**Comment by softsound** [comment]
**North Austin Game Night** They do a lot of game demos it seems, but are not very active. Like an event every month or two.

**Comment by softsound** [comment]
**IGDA Austin** hosts a lot of game demo stuff
