### ISSUE TITLE
Attack Area

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#433]
Players should be able to press a key, and have units attack units in an area, thus interrupting movement.

At this point, it's such a big UX problem, I'm considering it a bug.

**Comment by snowschu** [comment]
@josefnpat please add description to this bug. Thanks!

**Comment by josefnpat** [comment]
@snowschu done!

**Comment by josefnpat** [comment]
Should be done with 73ca57252356e8df64cc18d3bbb321ac86c2b9ac

Not sure how I feel with the UX.

basically, the "is interruptable" flag is being set when the ship moves. Please test UX on both collect ships (habitat/mining/scrapper) and military units. (you will need to multiple players)

**Comment by snowschu** [comment]
as of V864 [DC09851]
Attack Area - This function works as expected. 

One thing I'm noticing when I use it with civilian ships (like scrapper and habitat), the distance at which they detect their....function(? )(scrapper gets scrap, habitat goes to the stations, etc). Even though I have 'vision' and i'm somewhat close, they don't seem to notice it and will just sit there. (This is with the interruptable flag, I mean).

This is also inconsistent with individual ships. (Confusing)

[_Linking a video to reference what I'm noticing._](https://drive.google.com/file/d/17_YETwuJXzx1PEcKMkyXpaLbXgtU4KRz/view?usp=sharing)

Even if there's a good reason for them to go for the scrap and not going for scrap. I think that the civilian ships -should- move to their target, even if they cant collect anything. (UX). We're trying to teach the player that the 'green mist' is when the ship is working.

**Comment by josefnpat** [comment]
> One thing I'm noticing when I use it with civilian ships [..], the distance at which they detect their target [..].

I don't understand this sentence.

> Even though I have 'vision' and I'm somewhat close, they don't seem to notice it and will just sit there. 

On the contrary, it seems to be working precisely.

Here you have five ships selected. You tell it to move to the lower left of the screen, and then each ship looks for scrap. The only one in the 512px rage of scrap is the damaged scrapper, so it goes on it's merry way. You then use interruptible move, and all the ships that do not have scrap in range follow your command, whereas the ship that does have scrap in range, continues on it's way. Then finally, you issue an order to move, and they all respect that.

![rcs_intattack2](https://user-images.githubusercontent.com/646162/48577526-fd9a5800-e8dc-11e8-9709-840344b70561.gif)

> This is also inconsistent with individual ships. (Confusing)

You spend two minutes in this video, but don't explain how it's inconsistent or confusing.

>  I think that the civilian ships -should- move to their target, even if they cant collect anything. We're trying to teach the player that the 'green mist' is when the ship is working.

Are you saying we should remove auto-collect?

**Comment by snowschu** [comment]
My issue is that of the 5 scrappers, only one of them moved to begin collecting. If I told the group to move and be interrupted, why isn't the whole group going?

> Are you saying we should remove auto-collect?

No. Based on the screen grab you took. Me (the player) would expect that the 'group of scrappers' to go to collect the scrap.

Of the rest of the video, me (the player) would expect the 'group of scrappers' to "go to" the scrap, and wait there until more storage was available. When more storage is available, the scrappers would begin to collect right away.

**Comment by josefnpat** [comment]
> My issue is that of the 5 scrappers, only one of them moved to begin collecting. If I told the group to move and be interrupted, why isn't the whole group going?

I understand, but that is the nature of the interruptible flag. It's not checking the area of your selection, it's checking for each ship.

How can we communicate that better? Adding a "selection check" feature would be very very tricky, as autocollect is handled on the server side.

**Comment by snowschu** [comment]
If we aren't able to fix it (due to time or it would break the game for a long time), then we should clarify something about the "Range at which each ship see its target".

We have a visual for military ships for their shooting range. Can we implement something that shows the visual range of civilian ships that gather?

![battlestar-shootingrange](https://user-images.githubusercontent.com/34079393/48663359-c8187a80-ea54-11e8-9912-897ddca4a445.png)

Instead of edges (right angles) and lines, we have rounded corners and dots (which would differentiate it)?

**Comment by josefnpat** [comment]
Hmm - that could work. I'll let this settle in the back of my mind and look into it when we do user testing.
