### ISSUE TITLE
Typing in chat box also uses in-game keyboard commands

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#438]
Currently, the only issues are with `Spacebar` and `acute` activating while typing. Pressing `Delete`, however, has no results (while in the chat box).

[I will update with a proper repro and reference images at a later time. too tired]

**Comment by josefnpat** [comment]
Thanks for finding these!

TIL: the `acute` is technically [a character for accents in characters](http://sites.psu.edu/symbolcodes/windows/codealt/).

The `acute` is technically a subcharacter of the `grave accent`. In this paradigm, we use the terminology `backquote`, `backtick` or `grave`.

https://en.wikipedia.org/wiki/Grave_accent#Use_in_programming
