### ISSUE TITLE
Turret Assets

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#446]
Please make turrets
![1](https://user-images.githubusercontent.com/646162/42242795-c3c730b6-7ed4-11e8-86c5-1f58f8613d55.png)
![1](https://user-images.githubusercontent.com/646162/42242805-c754dea4-7ed4-11e8-801f-9aad791bf176.png)

**Comment by softsound** [comment]
some options
![turret_](https://user-images.githubusercontent.com/1772703/42251087-d0ffb49e-7efa-11e8-9802-f25425f67a20.png)
![turret2_](https://user-images.githubusercontent.com/1772703/42251088-d11620da-7efa-11e8-8a31-3dd182c8f2f3.png)
![turret3stand_](https://user-images.githubusercontent.com/1772703/42251089-d12bee9c-7efa-11e8-85ff-8eaee943054b.png)

**Comment by josefnpat** [comment]
![rcs_turret](https://user-images.githubusercontent.com/646162/42264613-c88a907c-7f36-11e8-904f-5b7a368f0023.gif)

**Comment by softsound** [comment]
![plainbase](https://user-images.githubusercontent.com/1772703/42719852-5caf78e6-86e2-11e8-8249-620b04ad8c07.png)

**Comment by josefnpat** [comment]
![rcs_small_turret](https://user-images.githubusercontent.com/646162/42732246-7a7fe66a-87e3-11e8-9b37-2e51f97f64f2.gif)
