### ISSUE TITLE
Remove white edges from ships

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#448]
A lot of the assets have this white edge.

Command:
![image](https://user-images.githubusercontent.com/646162/42251484-53571d72-7efd-11e8-98af-bb6cc57224a0.png)

Scrapper:
![image](https://user-images.githubusercontent.com/646162/42251494-65692db6-7efd-11e8-8bdb-a87a7052fc59.png)

**Comment by softsound** [comment]
Not fixing. This is due to lighting. All assets have this but the command ship because I was trying a different style for that ship.

**Comment by josefnpat** [comment]
No idea why this is happening. If there's an easy fix, we can make it happen. I have to look into this.

**Comment by josefnpat** [comment]
@softsound will review all ships in case there is a serious offender

**Comment by softsound** [comment]
not fixing, more so with hybrid ships now, too many styles going on.
