### ISSUE TITLE
Add Station Variations

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#45]
Station, multiple variations - this is a non-moving object that can be "mined" for crew. I imagine it would provide everything a civilian population would desire, including tennis courts!

**Comment by softsound** [comment]
![stationsquare_r2](https://cloud.githubusercontent.com/assets/1772703/25162370/c34e5054-2487-11e7-8d7a-6ced3aa109e2.png)

![stationsquare_e](https://cloud.githubusercontent.com/assets/1772703/25162390/ee2a6650-2487-11e7-8a72-c2b5cdde0e75.png)
empty

**Comment by softsound** [comment]
![starchain_r](https://cloud.githubusercontent.com/assets/1772703/25162424/30a7c306-2488-11e7-8c91-a82e81e749cf.png)

![starchain_e](https://cloud.githubusercontent.com/assets/1772703/25162426/3354b1d6-2488-11e7-81f5-4892a82f3686.png)
empty

**Comment by softsound** [comment]
![stationr31](https://cloud.githubusercontent.com/assets/1772703/25162974/571bd186-248c-11e7-8b37-b2fb1b634e50.png)

![statione](https://cloud.githubusercontent.com/assets/1772703/25162985/5e09f11c-248c-11e7-9120-005c1ec3a090.png)
empty

**Comment by softsound** [comment]
![tinystation_r](https://cloud.githubusercontent.com/assets/1772703/25163178/f6be4d94-248d-11e7-8c49-89076dc2f49a.png)
I imagined this rotating quickly...

![tinystation_e](https://cloud.githubusercontent.com/assets/1772703/25163187/046b53a6-248e-11e7-9ede-840f859d1ad1.png)

**Comment by softsound** [comment]
It's not a bad idea to group stations close together and add slight color changes...

**Comment by josefnpat** [comment]
Closes #21

**Comment by josefnpat** [comment]
Make bigger stations

**Comment by josefnpat** [comment]
instead of ships confusingly going dark, can we have the lights from the engines and windows go out?
