### ISSUE TITLE
Scout Ship not building

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#451]
_Operating System_
Windows 7 (64bit)

_Version_
client/GAME    v667[a92375b]
server/RELEASE v475[2c5287b]

_Repro_
Select Command ship and build Scout.

_Expected_
Command ship shows build animation and 2 scout ships are built.

_Result_
No scout ship is created. No build animation and no materials are subtracted.

_Additional notes:_ 
_(The moments between making the scrapper and making the habitat are when there was an attempt at making a scout. There is no visual context that anything is actually happening. Only audio.)_
![rcsv667-bug-scoutship not building01](https://user-images.githubusercontent.com/34079393/42352816-610bdf1c-8082-11e8-83d5-249b8ac32412.gif)

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/42353130-3b704cb4-8084-11e8-91c8-aab9239aeda4.png)

I cannot repro on my machine.

>Only audio.

What audio

**Comment by josefnpat** [comment]
Client mismatch of server vs client: 
![image](https://user-images.githubusercontent.com/646162/42353190-9bd8ad62-8084-11e8-9c41-77c02219b039.png)

Bumping #151
