### ISSUE TITLE
Repair Ship

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#452]
What would be nice is a ship that could repair other ships

**Comment by softsound** [comment]
![medicalship_](https://user-images.githubusercontent.com/1772703/42728217-37e667ce-877b-11e8-90e6-8e8ccdba3b0c.png)
![repairship_](https://user-images.githubusercontent.com/1772703/42728218-3b533996-877b-11e8-887b-95cb04ed1d0c.png)

I realized I was trying to make a 'doctor' ship, but what we wanted was something industrial.

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/42731874-e47beca6-87db-11e8-9dbe-ba109a8980d4.png)

**Comment by josefnpat** [comment]
b994146571011b5962346ad9ef652ba325779177
