### ISSUE TITLE
Update screenshots for RCS

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#453]
IDK might be a good idea.

**Comment by josefnpat** [comment]
If we have new shots, attach them here, and I'll update the current website, unless we redo the website before that.

**Comment by snowschu** [comment]
Once we have enemy AI, there will be new screen shots and the demo video can start rolling.

**Comment by josefnpat** [comment]
See #312 for block label info

**Comment by snowschu** [comment]
[Game Screenshots.zip](https://github.com/josefnpat/roguecraft-squadron/files/2786042/Game.Screenshots.zip)

**Comment by softsound** [comment]
I have updated screenshots.
[GameScreenshots.zip](https://github.com/josefnpat/roguecraft-squadron/files/2799709/GameScreenshots.zip)
