### ISSUE TITLE
Resource gathering ships no longer auto collecting

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#456]
_Operating System_
Windows 7 (64bit)

_Version_
client/GAME v685[5aaf0c8]
server/RELEASE v475[2c5287b]

_Repro_
- Begin a `Host Game`
- Press `Start` (you should be the only one in it)
- Starter ships load in (Command ship, scapper, habitat)

_Expected_
Scrapper and Habitat move and begin collecting materials on their own.

_Result_
Scrapper and Habitats are stationary and need to be told what to collect.

_Additional notes:_
- Building extra scrappers and habitats does not cause them begin auto collecting.
- The mining rig also does not auto collect upon building.

![rcsv685-bug-scrapperhabitatissue-01](https://user-images.githubusercontent.com/34079393/42739867-b3f2eab0-8864-11e8-9c47-a73531a3653a.gif)

**Comment by snowschu** [comment]
Operating System
Windows 7 (64bit)

Version
client/GAME v686[0158c10]
server/RELEASE v475[2c5287b]


Update seems to have fixed it.

Additional notes:
- Both the habitat and scrapper seem to idle sometimes. (Not resuming collecting) I will make a ticket if this persists

**Comment by josefnpat** [comment]
Habitat, Scrapper and Mining ship all have a range at which they will attempt to collect materials. This is as intended. Please ensure that this is not the problem.
