### ISSUE TITLE
Determine if we still need newsletter

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#463]
[email octopus](https://emailoctopus.com)
[mail chimp](https://mailchimp.com/)

I'm paying for the ability to send out newsletters, do we still want this ability? (Paying for the P.O box $20 sub every 3 months) If so what is blocking the newsletters, how can we speed up the process with our marketing campaign?

[Tips on running a campaign](https://optinmonster.com/how-to-run-a-successful-email-marketing-campaign/)

Do we have a list of subscribers or is that still on me? I can work on it later.

- Have we welcomed anyone for joining our list? 
- Mentioned events we would be at?
- Perhaps introduced team members to the public or done other interviews/shout outs with/to local developers.
- Announced upcoming game features?
- Sent out survey results so others understand where the game is going &/or thanked people for feedback...
- Offered advice on getting into game development (streaming, programming, art whatever)

[What email marketing can do](https://optinmonster.com/is-email-marketing-dead-heres-what-the-statistics-show/)

[Our latest survey looks super awesome by the way.](https://docs.google.com/forms/d/e/1FAIpQLSfDOsoMBiRSCNxZ_q7UIDTF9HAg3Xak5P3b9cAliZmsmFFgtw/viewform)

ticket #333, #348

**Comment by josefnpat** [comment]
We agree we do.
