### ISSUE TITLE
Battle doesn't begin where player ships are located

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#465]
_Operating System_
Windows 7 (64bit)

_Version_
client/GAME v712[4d6158f]
server/RELEASE v475[2c5287b]

_Repro_
1. Multiplayer -> Host Game
2. Add AI (limit not an issue with this bug)
3. Start Battle

_Expected_
Game begins and you see your squad of ships.

_Result_
Game begins in darkness. You must click on minimap to focus on your squad.
![rcsv685-bug-notfocused01](https://user-images.githubusercontent.com/34079393/44823542-b5fe0d00-abc6-11e8-8892-9c4d4cf14b88.gif)

_Additional Notes:_
- It is not indicated on the minimap where you begin. 
- This is not an issue if you host a game with just yourself (one player).

**Comment by josefnpat** [comment]
Basically, it would center it on the current position of the camera. Not sure how it ever really worked at all...
