### ISSUE TITLE
Add overlay on pause/menu state (2)

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#468]
![image](https://user-images.githubusercontent.com/646162/45061004-21812800-b068-11e8-883e-3ac2336cb4c4.png)

Offer help etc

**Comment by softsound** [comment]
What I need to do:

- [ ] Get all controls written down

- [ ] Get UI finalized this round

- [ ] Rearrange Menu so overlay makes sense

- [ ] Layout controls in a useful fashion.

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/45317720-6db4e800-b500-11e8-9c71-b5fae85130fe.png)
Menu update in progress

**Comment by softsound** [comment]
[generalKeyboardNMouse.zip](https://github.com/josefnpat/roguecraft-squadron/files/2381074/generalKeyboardNMouse.zip)

**Comment by softsound** [comment]
New assets

[tutorialFull.zip](https://github.com/josefnpat/roguecraft-squadron/files/2766617/tutorialFull.zip)


![image](https://user-images.githubusercontent.com/1772703/51286850-5dcf7800-19ba-11e9-965e-a2c9c1227db1.png)

**Comment by softsound** [comment]
concept

![image](https://user-images.githubusercontent.com/1772703/51288490-16e58080-19c2-11e9-8b48-c8af1da22412.png)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/51354195-73a37280-1a78-11e9-9208-92d15b10dfbc.png)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/51354833-8dde5000-1a7a-11e9-8da7-248e071954e5.png)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/51354900-ce3dce00-1a7a-11e9-8743-a57c64a797c4.png)

**Comment by softsound** [comment]
Still off balance but I think they should be top right aligned.

**Comment by softsound** [comment]
Just in case this helps... You also have the assets zip above for better assets.
![image](https://user-images.githubusercontent.com/1772703/51725183-8690e680-2026-11e9-916b-27481520b718.png)

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/51806725-07c4c500-2243-11e9-871f-b7f96b74c453.png)
