### ISSUE TITLE
Make a demo splash

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#482]
Use the feature from #472 so that the whole game is not accessible.

Design a screen that informs the player that:

1) You are playing a demo
2) You are missing out on all these awesome features
3) Identify where buttons should be and what they should say!

Assinging to @snowschu  for 1280x720 image/video to get people to buy game

**Comment by josefnpat** [comment]
a15d69d9ab24e1fe0f166086981b55e759fc373f

**Comment by josefnpat** [comment]
The code is in place to build and detect demo vs release.

Just need content as mentioned in this ticket.

**Comment by josefnpat** [comment]
A demo version has been confirmed and released. Now waiting for new assets to be able to close this ticket.

**Comment by softsound** [comment]
Differences between demo and full game right now-

more customizing, ships and free game-modes to come.

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/52610087-406cbd00-2e45-11e9-8f1b-76342a310974.png)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/52610174-a6594480-2e45-11e9-8048-0a03d973a4dc.png)

I think we should have a buy now button that goes to steam.

**Comment by softsound** [comment]
Okay, the placeholder is in. This ticket can be reopened when new art is done. 

![image](https://user-images.githubusercontent.com/1772703/52908452-bacd8080-323b-11e9-9111-a8778cf78f6c.png)

**Comment by snowschu** [comment]
[demo-end-1280x720.zip](https://github.com/josefnpat/roguecraft-squadron/files/2877759/demo-end-1280x720.zip)
[demo-end-1920x1080.zip](https://github.com/josefnpat/roguecraft-squadron/files/2877760/demo-end-1920x1080.zip)

**Comment by snowschu** [comment]
[demo-end-1280x720.zip](https://github.com/josefnpat/roguecraft-squadron/files/2877783/demo-end-1280x720.zip)
[demo-end-1920x1080.zip](https://github.com/josefnpat/roguecraft-squadron/files/2877784/demo-end-1920x1080.zip)

**Comment by josefnpat** [comment]
Identify what needs to be done on this ticket to continue.

**Comment by josefnpat** [comment]
Figure out what needs to be done this sprint, then move to next sprint.
