### ISSUE TITLE
Game Bar interferes with main menu screen

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#488]
_Operating System_
Windows 10 (Enterprise)

_Version_
client v727[e9e9232]
server v475[2c5287b]

_Repro_
1. Launch Game
2. Use mouse click on `Options` in the Main Menu screen.

_Expected_
Clicking on `Options` brings you to the Options Menu screen.

_Result_
`Options` is unclickable. 
_Noting that the mouse changes from the 'in game' mouse icon to the 'default' windows mouse icon_

_Additional Notes_
- Alt-tabbing brings a temporary workaround 
- Only happens in Windows 10
- Only happens at the launch of the game and in Fullscreen
- Taking a screenshot of this issue is difficult 

![2018_09_09_19_16_47_roguecraft_squadron](https://user-images.githubusercontent.com/34079393/45270858-760d1480-b467-11e8-9d33-c611cfe240cd.png)
![2018_09_09_19_21_27_roguecraft_squadron](https://user-images.githubusercontent.com/34079393/45270860-79080500-b467-11e8-8acb-30c5128e5703.png)

**Comment by snowschu** [comment]
Game Bar location when launching the game
![2018_09_09_19_13_49_roguecraft_squadron](https://user-images.githubusercontent.com/34079393/45270875-9a68f100-b467-11e8-8be1-ce8a8d48e8dc.png)

**Comment by snowschu** [comment]
_Solution_
Disabling the Game Bar fixes this issue.

_[Settings -> Gaming]_
![2018_09_09_19_22_59_settings](https://user-images.githubusercontent.com/34079393/45270886-c2f0eb00-b467-11e8-97d3-f80c9b8a1fe8.png)

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/45271730-a0ae9b80-b46e-11e8-8944-086b32ca1427.png)
Makes me think there might be no clean solution.
