### ISSUE TITLE
Ticket Template

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#492]
Using templates can help make sure a lot of the basic questions are answered on a ticket before it is deemed acceptable and something that can be finished before the due date.

For clarity: A waterfall ticket is a sequential, linear process of items being finished in a certain order. No phase begins until the prior phase is complete. For example, you need to create characters before you start animating them.

**1) Do multiple people need to touch this ticket before the due date?**

 I.E. Design needs to done, then given to programmer
 
A) If this is a waterfall ticket, write down dates each person will get the assets on or before the end of sprint.
B) If this requires multiple input write down days people will agree to review or check on the ticket.

**2) How many estimated assets will be required to finish this ticket?**

A) If this is a waterfall ticket mark the order the assets will be created. i.e. design idea needed before assets are started.
B) If less then 10 assets write them down and break them up further if needed.
C) If more then 10 assets this should either be broken up into another ticket or the assets should be extremely related and an estimated time for each asset should be noted and understood for the time frame. The keynote is to write what assets will be needed and understand the time constraints.

**3) Does this ticket depend on another ticket?**

A) If this a waterfall ticket, make the order and due dates the tickets will be finished in.
B) If this based on an older ticket, make sure that past ticket is clear and still related.

**4) Can I walk through what I will do first on the ticket?**

A) If you are struggling, the ticket needs more input and clarity.
B) If you are not sure what to do after the first step, try to break down the ticket further (i.e. more clarity) 

**5) What will this ticket look like finished? What does it need to be complete?**

A) Can list assets, number of reviews, voting, ready to test, etc.
B) Do you need all the assets listed or will just a few do?

**6) Can I test this ticket?**

A) List a way to test if it complete or if it applies.
B) Does the design seem functional? Do the crop marks look correct? Is it running as expected?

**7) What is the simplest way to get this ticket done?**

Feel free to add to this, these are just questions I need to ask myself more often.

------------------------------------------------------------------------------------
How to choose the best idea, rate each idea like so: 
coolness (1/10)
practicality (1/10)
effectiveness (1/10)

How can we make it more practical, effective or cool so this idea scores higher?

**Comment by softsound** [comment]
This is in part because I have to make sure I get my tickets done very early in the sprint so I can hand them off to the programmer half way before sprint is over to allow time to implement.

**Comment by josefnpat** [comment]
@softsound please move this to the wiki

**Comment by josefnpat** [comment]
@softsound please move this to the wiki

**Comment by josefnpat** [comment]
@softsound  please move this to the wiki

**Comment by softsound** [comment]
Moved to wiki

**Comment by josefnpat** [comment]
https://github.com/josefnpat/roguecraft-squadron/wiki/Ticket-guide
