### ISSUE TITLE
Make tickets

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#498]
Notes, please remind me to make into tickets.

3) Camera lock should be an option (especially when trying to take screenshots)

4) Video tutorials are the easiest way to demo how to play the game. But screenshots are next best thing, we can go octopath and just lay them over the screen. I would like a review/help button that goes through them again.

5) Ship trails next sprint please! Building effects next sprint too. 

6) When resource is full, related ships turn gray and stop moving. Noticeable icon should appear on resource bar and tooltip over the ship should say resource full, build more cargo or use resources.

7) Gray out buttons in demo mode users cannot use and make them not clickable. Single player for example.

**Comment by softsound** [comment]
Done
