### ISSUE TITLE
Make Steps for using Terminal on Mac OS for QA and Playtesting

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#499]
Part one: Setup steps
Part two: Most used commands

**Comment by josefnpat** [comment]
Please review the following wiki page, and tell me what exactly you would like added to it:

https://github.com/josefnpat/roguecraft-squadron/wiki/Run-from-source

**Comment by snowschu** [comment]
i have no idea how to deal with this.

All i know to do is:

- launch `terminal`
- `ls`
- `repos`
- `roguecraft-squadron`
- `git pull`
- `make run`

**Comment by josefnpat** [comment]
No idea!
