### ISSUE TITLE
Add a button for the Menu (Multiple screens)

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#500]
We currently only have 1 way to access the menu, which is through the keybinding of `esc`.
It's not immediately inherent that you need to press `esc` to access the menu. Most experienced gamers will know to test out `esc` when attempting to figure it out, but we shouldn't rely on that.

I propose we put a Menu button in either top corners of the screen. It'll be the most likely place people would look for a menu, and we already have them conditioned which the location of the UI.

[edit: I did mention other screens in the title. Ideally the menu access should be consistent across multiple screens but I think we can be flexible.  We currently only have need for this on two screens: Lobby and Game screens.]

**Comment by josefnpat** [comment]
I think this is reasonable. Assigning to @snowschu so that this can become an actionable ticket.

**Comment by snowschu** [comment]
![escape button location](https://user-images.githubusercontent.com/34079393/48567534-d9ca1880-e8c2-11e8-9d58-a39fa0c908e6.png)

button added. closing ticket
