### ISSUE TITLE
Options Menu - Preset Window sizes

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#501]
Players can arbitrarily resize the game screen using the mouse while the game is in Windowed mode, but I think it would improve UX if we included some presets for players to choose from.

Examples of common presets in 16:9:
1280x720
1600x900
1920x1080
2560x1440 (not as common, but used for 27" monitors)

**Comment by josefnpat** [comment]
![rcs_res](https://user-images.githubusercontent.com/646162/46953050-4945b180-d052-11e8-9c86-ba968c378e35.gif)
