### ISSUE TITLE
Change ships based on resources

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#505]
When resource is full, related ships turn gray and stop moving. Noticeable icon should appear on resource bar and tooltip over the ship should say resource full, build more cargo or use resources.

**Comment by softsound** [comment]
Actually I think having the full meter change a different color might be enough.

**Comment by josefnpat** [comment]
This means that every ship that has the gather_[type] would grey out at the same time, right?

> Actually I think having the full resource meter change a different color might be enough.
I believe it already does that.

**Comment by softsound** [comment]
I think is good enough for now. I'm closing it.
