### ISSUE TITLE
Gray out buttons in demo mode

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#506]
Gray out buttons in demo mode users cannot use and make them not clickable. Single player for example.

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/46596763-3c015380-caa3-11e8-8b19-4b26766e78d5.png)

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/46629812-ba8fdc80-cb07-11e8-957d-4dba15e9d61c.png)
