### ISSUE TITLE
Set up alien race that works with AI

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#520]
Ensure they inherit the current structure for a WC1 style game

![image](https://user-images.githubusercontent.com/646162/45620069-24edb980-ba41-11e8-89f4-81af1f58b1d6.png)

Actionable steps 
- [x] Create an asset list of ships
- [x] Figure out missing ships
- [x] decide what can be reused
- [x] Create missing ships
- [x] Put missing ships in a zip and attach to this ticket

- [x] Add alien
- [x] Add dojeer
- [ ] Add dojeer names

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/48658014-3ed75880-ea00-11e8-8155-c3d1b2800394.png)

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/48658020-57e00980-ea00-11e8-80f8-08309e808e72.png)

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/48658041-94ac0080-ea00-11e8-9c1f-3366e9a7a6a2.png)

**Comment by softsound** [comment]
https://github.com/josefnpat/roguecraft-squadron/tree/master/src/assets/mp_objects

**Comment by softsound** [comment]
Side note - dojeer = enemy

**Comment by softsound** [comment]
Start of asset list https://docs.google.com/spreadsheets/d/1otRe8Hlf3k4RxwzUNpd2hRYuN96tAC0rZSxm7SzY-48/edit?usp=sharing

**Comment by softsound** [comment]
[Fin.zip](https://github.com/josefnpat/roguecraft-squadron/files/2752810/Fin.zip)

**Comment by softsound** [comment]
![scout3_](https://user-images.githubusercontent.com/1772703/51081845-69bbf100-16bf-11e9-8d54-0b306b8e9144.png)

Made scout easier to see

**Comment by softsound** [comment]
[Fin _fix.zip](https://github.com/josefnpat/roguecraft-squadron/files/2752819/Fin._fix.zip)
