### ISSUE TITLE
multiplayer screen catchy background video

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#528]
Add something catchy to multiplayer screen, like video background or something.

**Comment by snowschu** [comment]
From what I remember, the lobby is actually the game instance, before its populated. To put in a video or an animated background would require these two things to be separated, yes?

cc @josefnpat

**Comment by softsound** [comment]
I don't think we need a video, once we add the ability to wait for other players and gray out buttons on the main menu it will keep players from wandering through the UI too much. The main reason for the video is sometimes we would set up the MP for players and keep it there because little kids would accidentally start randomly clicking stuff and never saw the main screen.

**Comment by josefnpat** [comment]
For accuracy's sake, yes they are the same state but that does not stop a video from being played.
