### ISSUE TITLE
Map bug 

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#530]
![image](https://user-images.githubusercontent.com/1772703/45662285-de42a280-bac6-11e8-97d3-dab4f7a3b4c3.png)
If you move enemies outside of map you get this error, and you can pull the camera to that spot with space but it gets stuck in no where land.

**Comment by josefnpat** [comment]
I cannot repro this ticket as I have no idea what "move enemies outside of map" means.

I have commited a possible fix, but if it happens again, will be able to remove possible fix and do correct fix.
