### ISSUE TITLE
Game controls

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#534]
LMB to select
RMB to move selected if ship
Hold and drag LMB to create selection box, everything in box will be selected
Double click on one unit to select all of same type.
Use Ctrl + Num to on selected ships to assign a control group.
Use the assigned control group by hitting the number key assigned.
WASD/arrow keys to move camera.
Move mouse to edge of screen to move camera. 
Shift key has ships attack closest enemy unit.
Delete key can be used to destroy ships.
Alt key shows ship hp.

Please keep this updated.

This can be referenced in tutorial & overlay.

**Comment by josefnpat** [comment]
move to wiki
