### ISSUE TITLE
Keyboard shortcuts for building ships

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#539]
Building ships need to have keyboard blindings attached to them.

_Ideas_
a) Anything that can be built has a unique keybinding attached to it (ex: Scrapper = s, habitat = h, etc etc)

b) The build section has numbers or letters associated with it (ex: Command ship has 5 slots and is associated keys are 1-5, drydock has 8 slots and is associated with keys 1-8)

**Comment by josefnpat** [comment]
d2870018bc4e97f06aa853c28bd136a1b4e0cc2d

I have gone DOTA2 style: build ships with: `zxcvbn`

Please test UX and tell me if it's good enough for power users

**Comment by snowschu** [comment]
Tested a little bit.
Found it organically as I had not reviewed this ticket before updating the game and playing around.

It feels natural. I think the only thing holding it back is a little more visual UX. Would it be complicated if we were to add the corresponding key to the tooltip in the build section? 

![allpurposercs](https://user-images.githubusercontent.com/34079393/48568711-991fce80-e8c5-11e8-9667-9fff14286ec2.png)

I'm not sure how you have this built, but I could see a conflict with this request with the starting build ship being different between ships (scrapper for civilian and command ships, satellite for the radar array, etc).

**Comment by josefnpat** [comment]
Good idea! I've made a ticket.

If you feel this ticket is done, please close it.

Feel free to expand on #624 with ideas on how to implement this!

**Comment by snowschu** [comment]
Closing issue. Request has been fulfilled. #624 will expand and build upon this ticket.
