### ISSUE TITLE
In Game Tutorial

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#54]
Use this in place of all the garbage text that folks have to memorize.

**Comment by softsound** [comment]
I think the first demo should have players learn in this order. 


- [ ] Select Command Ship 
"After the ship systems have shutdown, we do not know if can still take command of the ship, try and take command now"

- [ ] Move ship
"Command is working, some systems are running, try and test if we can move"

- [ ] Repair
"We can restore more system functions with repair, we have enough materials, we should repair right away "

- [ ] Investigate environment 
"Systems are back online, but resources are low, we will need to find more materials."

- [ ] Build salvager 
"We will need to build a ship to salvage that scrap"

- [ ] Use salvager to collect
"Salvager is build, sent it to collect the scrap, it will be transferred to our command ship as it collects it."

- [ ] find jump block
"Good we have materials we can get out of this sector now, look our jump ship has been storing energy and is almost ready, but something is blocking the energy"

- [ ] Destroy jump block
"We need to destroy that block so we can move to the next sector. We have enough materials to build a ship to handle that"

- [ ] jump to next sector
"The energy is free and we are clear to jump, before we go do you want to collect more resources and upgrade, research or build more ships? We never know what''s on the other side, best go prepared."

end tutorial level 1

**Comment by softsound** [comment]
I think that after level 1 you just unlock the tutorial as you go, it's no longer tied to levels but progress.

- [ ] Research
"Our ships seem able to upgrade further, if we set up a lab we will be to research this further"

- [ ] Radar
"This systems seems much darker and dangerous compared to other systems, maybe we should build better radar."

etc

**Comment by josefnpat** [comment]
## Notes

* **Minimize text**
* Don't front load
* Distribute tutorial throughout gameplay
* Tutorials should be skippable or shouldn't interrupt play
* [Teach, Comfort], [Excite, Respect]
* User Test A Lot
* Keep space safe
* Make the goals into puzzles (Don't use arrows, etc)
* Camera
  * Move the camera
  * Use the minimap to move the camera

## User types

Our tutorial needs to work for:

1. Visual Learners (Text overlay, visual line guides and success visual)
2. Aural Learners (Voiceovers and Success Sound Effect)
3. Kinetic Learners (Require user to do actions)

It needs to allow for users who enjoy:

1. Explorative Acquisition (People who learn by taking risks)
2. Modeling Acquisition (People who want to know how things work before they try)

## Things we want to teach in game:

Required (Exposition):

* Click on things with your mouse
* You may skip the tutorial by building a jumpship and jumping to the next system.

Note: The text here has the puzzle, and the answer to the puzzle is in brackets. Perhaps we can show the answer to the puzzle after 10 seconds?

### Level 1:

"Greetings commander. I would like to test our basic systems. If you prefer not to, you may jump to the next system right away."

Basic:

* Select Ship
  * requires one ship

"During stasis, many systems have deteriorated. Please confirm that the command ship is still operational. [Use the left mouse button to select the command ship]"

* Move Ship
  * requires one ship

"Our information systems seem to be operational. Please confirm that our command ship is under your control. [Use the right mouse button to move the ship anywhere.]"

- Using Actions (Repair Ship)
  - requires a damaged ship

"Our command ship has been damaged from our long travel. I suggest we tell the crew to repair it. [Select the command ship, and toggle the "Repair" action.]"

* Identifying Objects
  - requires one foreign object
* Moving the map
* Identify Scrap
  - requires scrap

"In order to survive, we will need to collect resources. We should search this system for something to gather. [Move around the map with by moving your mouse to the edge of the screen, or using WASD/Arrow Keys. Find scrap.]"

* Build Ship
  * requires a command ship

"Excellent. We found some scrap. We should use our command ship to build a salvager to gather it. [Select the command ship, and use the "Build Salvager" action in the upper right corner]"

* Use Salvager to Collect
  - requires a salvager and scrap

"Now that we have a salvager under our command, have it collect material from the scrap. [Select the salvager, and have it target the scrap]"

* Build a fighter ship
  * requires a command ship

"Now that we have materials, we should build some ships to protect our squadron [Select the command ship, and build a Fighter]"

* Jump To Next Sector & Charging System
  * requires a jump ship

"When you believe our fleet is ready, inform the Jump Calibrator to jump to the next system. [Select the Jump Calibrator, and use the Jump action]"

Advanced:

### Level 2:

"We have detected enemy ships. We need to use our newly made 

* You can kill enemy ships
  * requires an enemy

""

* Not all ships shoot
  - requires a ship that can shoot and one that cannot
* Your ships can die
  - requires a disposable ship
* Mining/Refining System
  - building mining rigs
    - requires a ship that can build a mining rig
  - building refining ship
    - requires a ship that can build a refinery
  - collecting ore
    - requires a ship that can gather ore, and an asteroid
  - enabling refinery to refine ore
    - requires a refinery and some ore
* Jump Scramblers
  - requires a jump scrambler and a ship to destroy it

### Level 3:

* Advanced Fog of War
  - requires a radar ship
* Use MiniMap to find Jump scrambler
  * requires a radar ship and a jump scrambler
* How black holes work
  - requires a blackhole and a disposable ship

### Level 4

* Auto-Collection
  * requires two gather ships
* Salvage
  * requires a disposable ship

### Level 5:

* Upgrade
  * requires a ship with an upgrade
* Takeover
  * requires a troopship

**Comment by josefnpat** [comment]
![box](https://cloud.githubusercontent.com/assets/646162/24487770/9ce175b4-14d7-11e7-9944-ab00a891bf9c.png)

**Comment by josefnpat** [comment]
add a note about spacebar?

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/46807944-c3172b80-cd30-11e8-8069-ef5469119dd0.png)

**Comment by josefnpat** [comment]
This is a very old ticket. This applies to the old mission system. We will use the #376 ticket instead.
