### ISSUE TITLE
UX: Menus and Lobby - Numbers only go in one direction when clicked

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#543]
Anything that is adjustable in the menu or lobby only goes in one direction (ascending) although it loops around.

_Suggestion_
Let players use LMB for descending (numbers going lower) and RMB for ascending (numbers going higher). It can still loop around, if needed.

**Comment by josefnpat** [comment]
c91868ac3de8d6c6dd3a8650a1b54cc9f2818a4f

**Comment by josefnpat** [comment]
c91868ac3de8d6c6dd3a8650a1b54cc9f2818a4f

**Comment by josefnpat** [comment]
Unless there's other places a stepper would be good, I think this is good for release.
