### ISSUE TITLE
Stars look like dust

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#547]
Consider toning down parallax as well.

**Comment by softsound** [comment]
sizes for stars:1024, 2048, 9096

**Comment by softsound** [comment]
Can't have size 4096 causes scale issues.

**Comment by softsound** [comment]
1024
![1024stars](https://user-images.githubusercontent.com/1772703/46264618-90756380-c4e4-11e8-8d44-5567fbaf2139.png)
2048
![2048stars](https://user-images.githubusercontent.com/1772703/46264619-90756380-c4e4-11e8-9285-6bae00160517.png)
4096
![4096stars](https://user-images.githubusercontent.com/1772703/46264632-a7b45100-c4e4-11e8-98d7-7795547abebc.png)

**Comment by josefnpat** [comment]
@softsound I can't use the second ones - they have a black background

**Comment by softsound** [comment]
Let's just go with the older stars for now. There is no easy fix for this.

**Comment by softsound** [comment]
Actionable steps use old stars for now.

**Comment by softsound** [comment]
4k
stars 1
![starsl1](https://user-images.githubusercontent.com/1772703/47409423-4caefc00-d728-11e8-9f67-a3388e22a691.png)
stars 2
![starsl2](https://user-images.githubusercontent.com/1772703/47409443-533d7380-d728-11e8-9b9f-413ecfec1dfe.png)

**Comment by softsound** [comment]
You will notice the 4k will still flicker on stars that are 1 pix, but stars that are 2-3 pixels look massive.
![image](https://user-images.githubusercontent.com/1772703/47410941-e9739880-d72c-11e8-91b9-72094968fa02.png)

**Comment by softsound** [comment]
[stars.zip](https://github.com/josefnpat/roguecraft-squadron/files/2513377/stars.zip)

Well... Can't really fix flickering because upscaling stars looks funky. I guess later on I can work in 8k then downscale to 4k and see if it fixes it.
