### ISSUE TITLE
General Art Rules

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#551]
*The reason I'm creating this over a wiki page is you have to host each image on a wiki and can't just drag and drop them unto the ticket, also I have to spend time formatting whereas on a ticket it keeps your formatting.*

**Current game resolution**
1280 x 750
![image](https://user-images.githubusercontent.com/1772703/45969887-b1c4e400-bffa-11e8-91f5-182c357cc8f8.png)

![image](https://user-images.githubusercontent.com/1772703/45973151-42072700-c003-11e8-8fa6-fec1a0608c0d.png)

**UI**
Buttons at generally 64x64
Long buttons are at 64x 128

**Ships**  
32x32
64x64
128x128
256x256 (to be added king size)

**Backgrounds** _what sizes should these be?_
4096x4096 stars
4096x4096 colored nebula's

**Comment by josefnpat** [comment]
Screen is *1280x720*

Please make this into a wiki page. Upload images to imgur if you have to
