### ISSUE TITLE
Player can make control groups with enemy ships 

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#552]
_This might actually be a feature rather than a bug, but it's good to know._

_System_
Windows 7 (64bit)

_Version_
Game/Client: v754 [bf7da40]
Release/Server: v475 [2c5287b] 

_Repro_
1) Begin game as normal (include a second human player or an AI player)
2) Locate enemy on the map. Select enemy ship(s)*
3) Create a control group

_Expected_
Unable to create a control group.

_Result_
Control group is made and available for recall and focus.

_Additional notes_
You can recall and focus, but you can't give them commands.

_*You are unable to make a group selection of the enemy ships, but you can make a signal selection._

**Comment by josefnpat** [comment]
Thanks for triaging this. Bug confirmed.
