### ISSUE TITLE
No music on Main Menu (specific trigger)

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#554]
_System_
Windows 7 (64bit)

_Version_
Game/Client: v754 [bf7da40]
Release/Server: v475 [2c5287b] 

_Repro_
1) Launch Game. 
2) From the Main Menu, Multi player -> Host game. 
3) From the Lobby, Press `Esc` to leave the lobby and head back to the Main Menu.

_Expected_
Game music should begin to play

_Result_
Music does not begin to play

_Additional notes_
Currently only happens when 'surrendering'(exiting the game instance).

**Comment by josefnpat** [comment]
Fixed in 502c93723846094c924ae98a69a7f44a2cb46294
