### ISSUE TITLE
Asteroid Update

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#555]
Some new asteroids, please remove all the old ones.

![asteroid1](https://user-images.githubusercontent.com/1772703/46047142-64737000-c0e9-11e8-95a4-ac9351e6e7de.png)

![asteroid2](https://user-images.githubusercontent.com/1772703/46047143-65a49d00-c0e9-11e8-8e1b-dcc4c8f6a0c8.png)

![asteroid3](https://user-images.githubusercontent.com/1772703/46047144-663d3380-c0e9-11e8-9bc0-f537647631b4.png)

![asteroid4](https://user-images.githubusercontent.com/1772703/46047147-676e6080-c0e9-11e8-8e00-4dd1cc056633.png)

**Comment by josefnpat** [comment]
These seem very familiar with the original assets:

![image](https://user-images.githubusercontent.com/646162/46060348-a079f580-c128-11e8-8ca3-2899a402411d.png)

**Comment by softsound** [comment]
darn
