### ISSUE TITLE
Prepare Platform Release (2)

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#558]
- [x] Steam - need to start setting that up (@snowschu)
- [x] Itch - need to set that up (@snowschu)
- [x] HiB - reach out to joseph (@josefnpat)

**Comment by josefnpat** [comment]
Maybe @snowschu will take care of steam?

**Comment by snowschu** [comment]
what is HiB? I'm not familiar with this acronym

**Comment by josefnpat** [comment]
Humble Indie Bundle from Humble Bundle - https://www.humblebundle.com/

**Comment by snowschu** [comment]
_This comment will be updated or edited over time._
- [ ] STEAM
new login account 
steamworks
screenshots
video
copy
- [ ] Humble Store

- [ ] itchi.io

- [ ] game jolt

- [ ] GoG.com

**Comment by josefnpat** [comment]
related to #453 and #312

**Comment by snowschu** [comment]
Humble Store has been prepped. Contact was not available for referencing.

Working on Steam set up.

**Comment by snowschu** [comment]
Created an actionable ticket for @josefnpat, #625.

**Comment by josefnpat** [comment]
This ticket is blocked by #86

**Comment by snowschu** [comment]
![untitled](https://user-images.githubusercontent.com/34079393/51627116-c6f94300-1f06-11e9-8a32-b90226bdab6d.png)

**Comment by josefnpat** [comment]
icon: https://github.com/josefnpat/roguecraft-squadron/issues/308#issuecomment-454582466

**Comment by snowschu** [comment]
![screen shot 2019-01-23 at 11 57 57 pm](https://user-images.githubusercontent.com/34079393/51657548-eb870680-1f6a-11e9-8161-5691aae1ac92.png)

**Comment by snowschu** [comment]
@josefnpat please review technical requirements and technical options for Steam setup. Most likely contained to `Edit Steamworks settings`.

**Comment by softsound** [comment]
#656

**Comment by josefnpat** [comment]
Everything is up, game (and hopefully demo) is now under review

**Comment by softsound** [comment]
Game is ready for release this is done.
