### ISSUE TITLE
Implement Campaign

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#559]
- [x] Create raw script
- [x] Transpose raw script to script
- [x] Send script to artist, and throw money at them for art
- [x] Write Campaign System
- [x] Clean up script
- [x] Coordinate Images into game
- [x] Perform Voice Acting
- [x] Coordinate lines into game
- [x] Final Cleanup

**Comment by softsound** [comment]
#520 for Coordinate Assets into game

**Comment by softsound** [comment]
This is blocked by assets? Where is this ticket now?

**Comment by josefnpat** [comment]
blocked by #858

**Comment by josefnpat** [comment]
No longer blocked.

Level 5 still needs survival component

**Comment by josefnpat** [comment]
- [ ] Computer lines need to be re-recorded so they say Miho Takeda correctly

These lines need to be fixed to match the audio:
- [ ] ![image](https://user-images.githubusercontent.com/646162/65379262-1f960100-dc8b-11e9-8380-27099a740332.png)
- [ ] ![image](https://user-images.githubusercontent.com/646162/65379314-ba8edb00-dc8b-11e9-9727-d59b7e02a4aa.png)
- [ ] ![image](https://user-images.githubusercontent.com/646162/65379350-34bf5f80-dc8c-11e9-84f4-2877736167d5.png)
- [ ] ![image](https://user-images.githubusercontent.com/646162/65379353-4143b800-dc8c-11e9-8379-500b88dfae84.png)
- [ ] ![image](https://user-images.githubusercontent.com/646162/65379364-5882a580-dc8c-11e9-9d0c-e1e3fcc70617.png)
- [ ] ![image](https://user-images.githubusercontent.com/646162/65379374-8831ad80-dc8c-11e9-8263-0b96c4291eb5.png)
- [ ] ![image](https://user-images.githubusercontent.com/646162/65379379-a1d2f500-dc8c-11e9-8cd6-e7addf3119ff.png)


- [ ] Recrop this wallpaper to not be on the character's face:

![image](https://user-images.githubusercontent.com/646162/65379293-84e9f200-dc8b-11e9-932b-72c38ed775aa.png)

**Comment by josefnpat** [comment]
- [ ] hook up audio level system to vnjson
