### ISSUE TITLE
Make custom research icons

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#56]

**Comment by softsound** [comment]
Can we have more info on this ticket? Such as research types/ icon ideas?

**Comment by josefnpat** [comment]
Here are all the current research upgrades:

https://github.com/josefnpat/roguecraft-squadron/blob/master/src/states/mission.lua#L336

here is the current icon for all of them:

https://github.com/josefnpat/roguecraft-squadron/blob/master/src/assets/actions/upgrade.png

**Comment by softsound** [comment]
ideas for icons:
science tube/magnifying glass/wheels turning/atoms

refining metals/beakers

upgrade types 

- speed
- better ai
- increase of y rates
- increase efficiency

**Comment by josefnpat** [comment]
we said I was doing this

**Comment by josefnpat** [comment]
we now have upgrade icons. Could do with a redo, obviously, so pulling out of milestone, and assinging to @softsound

**Comment by josefnpat** [comment]
![image](https://cloud.githubusercontent.com/assets/646162/24825736/b528ca72-1bea-11e7-9e4d-ba01946620fd.png)
![image](https://cloud.githubusercontent.com/assets/646162/24825739/bf082d80-1bea-11e7-8e21-1f83ed64437a.png)
![image](https://cloud.githubusercontent.com/assets/646162/24825742/c8128d80-1bea-11e7-8242-9df05a11bc71.png)
![image](https://cloud.githubusercontent.com/assets/646162/24825744/d31c0da0-1bea-11e7-819e-f0de8dc56c49.png)
![image](https://cloud.githubusercontent.com/assets/646162/24825747/df916e0e-1bea-11e7-882b-d2e7206a2cf5.png)
![image](https://cloud.githubusercontent.com/assets/646162/24825749/e9af0df6-1bea-11e7-979e-1fbaeac5e925.png)
![image](https://cloud.githubusercontent.com/assets/646162/24825750/f1c2eda0-1bea-11e7-8b9a-dab89d5bf2ff.png)
![image](https://cloud.githubusercontent.com/assets/646162/24825752/fb41da08-1bea-11e7-905f-a7cdd35e1151.png)

**Comment by softsound** [comment]
Icons have been updated. Closing
