### ISSUE TITLE
Create new difficulty levels

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#562]
Help, I am obviously not qualified to do this.

Current difficulty levels:

* Chew Toy (easiest)
* Scrub
* Awkward
* Bananas
* Ragequit
* No Ice Cream (hardest)

**Comment by VividReality** [comment]
They could just be named after the ranks in the lore.
- Private
- Adjudant
- Luitanant
- Sergeant
They could also be similar to Divinity
- Explorer
- Classic
- Tactician
- Honor
They could also be jokes from first perspective as in DOOM
- I'm just here for the story!
- Be careful!
- I would like a challenge! 
- Bring it on!
- Give me all you got!
They could be called after the value of materials in the lore.
- Rock
- Metal
(wait are these music genres, 
(Black Metal) 
(Death Metal)
- Diamond
- Mithril

Let me know what you think I got more

**Comment by softsound** [comment]
If you don't know the ranks others won't either.

Why don't we just keep it simple?
Newbie
Experienced 
Veteran 
Sage

**Comment by snowschu** [comment]
@softsound's suggestions would be more universally understood. I think we should continue brainstorming a bit longer.  

I would still like to urge we associate a number with these difficulty titles, though.

**Comment by josefnpat** [comment]
To chime in with numbers, we could use the NATO code from the RAF officer ranks:

* OF-1: Flying Officer
* OF-2: Flight Lieutenant
* OF-3: Squadron Leader
* OF-4: Wing Commander
* OF-5: Group Captain
* OF-6: Air Commodore

Not only are these the ranks we're using in game, but they're also numbered.
