### ISSUE TITLE
Be able to access different stages of the campaign

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#564]
When a player finishes a part of the campaign, they should be able to continue where they left off with the current research.

- [x] Save and load current campaign
- [x] Save and load current stage in campaign
- [ ] Save and load current research spendings

**Comment by snowschu** [comment]
**_Chapter Selection: Look and Flow_**
![campaign-select-mode-01](https://user-images.githubusercontent.com/34079393/64135147-27a90200-cdab-11e9-9b35-38ce95f3bdeb.png)
_Players select `Campaign` from the list, then press `Start`_

![campaign-lobbyscreen-01](https://user-images.githubusercontent.com/34079393/64135040-19a6b180-cdaa-11e9-84ab-b531882adb43.png)
_Players will enter the lobby. They can either a) Select `Ready` and continue where they left off or b) select 'Chapter Selection'_ **_Note: Consider adding a `Start from beginning` button to allow players to start over without having to go to the selection screen._

![chapterselection-01](https://user-images.githubusercontent.com/34079393/64135193-7c4c7d00-cdab-11e9-940c-c9f42cc166f8.png)
_Chapter selection is in a 4x3 grid, which allows for 12 chapters. Current design has a thumbnail for each chapter, a number to identify the chapter, and a chapter title. Fonts on screen are `Expletus Sans, Bold` at a size of 28px._

_When chapter is unlocked, it should show the numbnail, chapter number and title. 
When a chapter has been selected, a glowing stroke should appear around the box, to identify that it has been selected._
Locked chapters should be visible with the chapter number and a lock, to indicate that players are unable to select them yet. 

_You will notice that some of the locked chapters have variants in how 'chapter' is shown. This was to show how much space each possible combination could take up. IMHO, the one labeled `Chapter 5` and `Chapter 10` look the best. I recommend going with that._

**Comment by josefnpat** [comment]
lolol u suck the major peen seppi

**Comment by josefnpat** [comment]
Simply set research to cumulative research amounts - it's lazy, but it works?
