### ISSUE TITLE
Add Day 1 DLC that is Halloween themed

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#567]
Maybe just put a witch hat on all the characters. I'm thinking $99.99 is reasonable.

**Comment by josefnpat** [comment]
Be sure to contact kotaku.

**Comment by softsound** [comment]
Very confused on this ticket, but okay, maybe this is how you could get started? [Contact support](https://kinja.desk.com/customer/portal/emails/new) and ask about ask about promotional material.

Also Kotaku is owned by[ Kinja](https://kinja.desk.com/customer/en/portal/articles/2137882-what-is-kinja-) so maybe just [setup a blog account there first.](https://kinja.desk.com/customer/en/portal/articles/1199004-how-do-i-create-a-blog-)

[Make sure you make an account first!](https://kotaku.com/?startTime=1538947080826#)

Unless you mean, actually contact particular people?

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/46628879-a72f4200-cb04-11e8-833c-fdd2de086d51.png)

**Comment by softsound** [comment]
Joke ticket
