### ISSUE TITLE
Implement new website for RCS

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#571]
Since @softsound closed #462 (and rightfully so) I will make this ticket, as it represents what we need to do.

We need a new site for RCS, preferably a one page lander.

**Comment by softsound** [comment]
I suggest we go with a simple free blogger website with a free [one page template](https://gooyaabitemplates.com/bolt-blogger-template/).

Just something simple for now. We can use the same account we do for survey's.

**Comment by softsound** [comment]
#335

**Comment by softsound** [comment]
What about this one? It's very easy to modify.

_example of quick editing in roughly 30 mins_
![image](https://user-images.githubusercontent.com/1772703/47095488-ff480180-d1f2-11e8-8eb1-1cfbdb31830d.png)

[colid-colorlib.zip](https://github.com/josefnpat/roguecraft-squadron/files/2487996/colid-colorlib.zip)

**Comment by josefnpat** [comment]
I will look into the HTML5 template to see if it's appropriate.

**Comment by josefnpat** [comment]
@snowschu will get back to before the 24th of october

**Comment by josefnpat** [comment]
@snowschu play with this a bit: https://www.strikingly.com/
