### ISSUE TITLE
Add game loader

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#579]
```
SheepolutionToday at 2:31 PM
Just require a file every x milliseconds while the intro plays
```

e.g. when the game first starts:

![image](https://user-images.githubusercontent.com/646162/46792736-a4ea0500-cd09-11e8-9cf8-7f0471d05d27.png)

**Comment by josefnpat** [comment]
Since I've added the shaders for the game, I need to know if this ticket needs to happen. Please test on a low end machine, @snowschu !

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/46960406-11e00080-d064-11e8-9795-2bad7404ac12.png)

**Comment by snowschu** [comment]
The loader is great and is definitely needed. It's needed not only for lower end machines but even up-to-date machines. It lets the player know that 'something his happening', even if it's just for a brief moment.

Ticket is closed already.
