### ISSUE TITLE
Test on latest update of win10

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#580]
![image](https://user-images.githubusercontent.com/646162/46725473-de573d80-cc41-11e8-941e-fd495518b9ec.png)

I see that 0.11.x doesn't work on the latest version of win10, but we should test to make RCS runs on win10, as we are using 0.10.2.

**Comment by josefnpat** [comment]
1809 got delayed

https://blogs.windows.com/windowsexperience/2018/10/09/updated-version-of-windows-10-october-2018-update-released-to-windows-insiders/

**Comment by josefnpat** [comment]
@softsound What makes you think it doesn't need to be tested?

**Comment by snowschu** [comment]
Update Win10 build 1809 is has been delayed (by Microsoft). Until they send the update, this ticket isn't actionable.
