### ISSUE TITLE
Tooltip Icons

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#581]
I have added tooltip icons remastered from #71 for #491

@softsound please review the icons in  `src/assets/hud/tooltip_icons` and tell me what you think.

Here's a preview:

![image](https://user-images.githubusercontent.com/646162/46800410-3151f300-cd1d-11e8-871c-1aac4d54e511.png)

**Comment by softsound** [comment]
I reviewed the icons in the folder I think they are good. The ticket will be closed, if we need to update later we can reopen.


I think I need to have capacity mention something about command points now in regular UI. Will make a ticket.
