### ISSUE TITLE
Crash at start of demo match

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#582]
_Operating System_
Windows 7 (64bit)

_Version_
client v822[9972d01]
server v475[2c5287b]

_Repro_
1. Run RCS. On main menu, click on `Multi Player`
2. Host Game
3. Add 2 AI, Change mode to `demo`, change capacity to `medium`
4. Click 'not ready' to begin

_Expected_
Game begins

_Result_
Game crashes.

![untitled](https://user-images.githubusercontent.com/34079393/46908183-9ad02e00-cee4-11e8-9a15-0368032e970a.png)

_Additional notes:_
- Happens with or without AI added

**Comment by snowschu** [comment]
Update: only happens when Demo is enabled.

**Comment by josefnpat** [comment]
`researchrenderer` needs to read current preset from `mppresets`
