### ISSUE TITLE
Paused game has too much VO

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#587]
I know we can't really pause but, having the game constantly ask me what it can do for me while "paused" and while I'm not giving commands feels like unexpected pushy behavior. What actually triggers the VO? I thought it only triggered when I moved the ships or they were full of x resource.

Definitely a bit of randomness mixed in there because you can just leave it running in the background and every few minutes it will bring something up.

Not sure how to solve but I thought I'd point it out anyway. Perhaps we should dim the sound effects on pause?

Actions

- [ ]  Don't have VO when paused? Or quiet the VO?

**Comment by snowschu** [comment]
As of v844 [aea7e6c], this issue is no longer present in the full game or demo.

Related to #596
