### ISSUE TITLE
Add stats, hp, etc to the side bar

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#589]
![image](https://user-images.githubusercontent.com/646162/47058639-8497cb80-d18b-11e8-9c19-43fa99886f56.png)

**Comment by josefnpat** [comment]
```
> I wish I could see my used command point out of max command points
> If I select a ship it should show the tool tip on the left from when before you build it, so you can see how many command points it is taking up
```

**Comment by softsound** [comment]
In my original design I had the tooltip moved over onto the main panel. #287 

I had also thought about having Quick Actions (Delete, Follow, Attack cloest) be in their own panel. Something that could be moved around the screen. We currently don't have any UI that addresses that.

**Comment by softsound** [comment]
Might be able to rework building or actions into their own panel as another way to address this. #592
