### ISSUE TITLE
Update Marketing Video with new assets

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#59]
pizza

**Comment by softsound** [comment]
Notes please make video with and without title on front to switch for different websites, it looks funny to have the logo multiple times on a website.

![image](https://cloud.githubusercontent.com/assets/1772703/24825731/8ff248b4-1bea-11e7-8b47-6a901f1d01a4.png)

**Comment by josefnpat** [comment]
pizza

**Comment by snowschu** [comment]
Summary of meeting:
We have two types of videos we'll want to have:
- Demo video (which we've had): This is a longer video, showing off the gameplay, mechanics, and a bit of story.
- Trailer: This is a shorter video (roughly 30s - 1min30s) that is shows the highlights of the game in quick succession and "pumping up" the user.

Once we have more of the updated/revamped MP fleshed out, I'll start working on the demo.
