### ISSUE TITLE
Set up JR demo

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#60]
April 6!!!

**Comment by softsound** [comment]
‘indie alley’ section - we need to be a part of that. contact@juegosrancheros.com

Read http://juegosrancheros.com/faq/ for more info

**Comment by softsound** [comment]
"Me and my programmer have been working on a new game and we were hoping to show it at the April 6th meeting. We would like to use our own steam machine and other equipment.       

If you would like to check out our RTS and rogue-like game, have a look here:
www.roguecraftsquadron.com 

It's still in development. 

If you need anymore info please drop me a line @ bytedesigning@gmail.com 
or 512-985-8019

Thank you, hope you have a good day"

This was the email sent.

I realized I forgot to greet them in my haste to get out the door this morning. Oh well, at least it ends friendly.

**Comment by josefnpat** [comment]
Greetings!

My name is Josef, and my Artist and I have been to the North Door for the JR meetups quite a few times!

We have a game that we made for the Love Game Jam (Second Place!) and that we showed off with the IGDA. We would love the opportunity to show it off at the next JR.

If you would like to check out our hybrid Rogue-Lke and Real Time Strategy game, please visit http://roguecraftsquadron.com/

The game is still in development, but we feel it's in a strong place, and would love some feedback from the JR community!

You can email me here, or contact me at XXX XXX XXXX

You can also email my artist, Ashley, at bytedesigning@gmail.com, or contact her at XXX XXX XXXX.
Thank you for your time!

-Josef "Seppi" Patoprsty

**Comment by josefnpat** [comment]
Hi there Josef -- we have a section upstairs for folks to bring in their own games & this should be fine! Our boilerplate guidelines are below!

IF YOU'RE BRINGING A GAME TO OUR INDIE ALLEY:

- Plan to show up around 6:30. Someone from JUEGOS RANCHEROS should be at the venue already. If they are not, please wait in front of the venue for one to arrive.

- Bring everything you will need to display your game, including display, controllers, etc.

- Bring a power strip! Those are in the shortest supply at the venue. If you have an extension cable, it wouldn't be a bad idea to bring that as well.

- We typically ask that folks who bring games set up on the 2nd floor balcony, to keep the main floor clear for any games that JUEGOS RANCHEROS itself is installing. However, this may change on any given month due to the needs of the games JUEGOS RANCHEROS are exhibiting, so please wait for someone from the group to advise before beginning your setup.
