### ISSUE TITLE
Have mouse cursor change when depressed

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#600]
Have mouse change to reflect when it clicks, it's actually super hard to tell just watching a video.

Inverting the image for a second would probably get the idea across...

Also have mouse icon change when held down.

**Comment by josefnpat** [comment]
While the title makes me laught at how poorly it's written, I actually do think this is a very good FEATURE.

e.g. see Maple Story 2:

![ms2_mouseclick](https://user-images.githubusercontent.com/646162/47368456-4b89ba80-d6a7-11e8-95f7-ce60de5fb5cb.gif)

By adding this FEATURE, it's almost a cheat honestly - we get all the UX that the mouse is working, without having to animate everything that exists.

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/47368547-7542e180-d6a7-11e8-8a61-f30677179283.png)

**Comment by josefnpat** [comment]
Take current cursor, and make a "depressed" version

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/63303394-57351600-c2a5-11e9-87ab-b4a682492c37.png)

**Comment by josefnpat** [comment]
help nothing is transparent

**Comment by josefnpat** [comment]
I've used the old player.png for left mouse depressed:
![player](https://user-images.githubusercontent.com/646162/64409941-8e4e4a00-d04f-11e9-99e0-37dff3fffc70.png)

and the neutral.png for right mouse depressed:
![neutral](https://user-images.githubusercontent.com/646162/64409936-8bebf000-d04f-11e9-8e50-03369e0bf502.png)

**Comment by softsound** [comment]
![cursor](https://user-images.githubusercontent.com/1772703/64502621-bd9dca80-d28c-11e9-9def-fad4ea870287.png)

This is transparent.
