### ISSUE TITLE
Get new graphics for VN

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#61]
See if Laura will make enemy and commander graphics?

**Comment by josefnpat** [comment]
Maybe less anime?

**Comment by softsound** [comment]
![charactera2](https://cloud.githubusercontent.com/assets/1772703/25163978/98e0c1ce-2493-11e7-885e-60dd58a40508.png)

hmmm... Will think about restyling to baby cat version later on

**Comment by josefnpat** [comment]
#MaybeMoreAnime

**Comment by josefnpat** [comment]
related to #559 - noyemik will be handling this

**Comment by josefnpat** [comment]
Assets were done 2018-11-15!
