### ISSUE TITLE
VO Triggered While in Research Box

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#610]
_Operating System_
Windows 7 (64bit)

_Version_
client n/a
server n/a

_Repro_
1. Begin a Multiplayer match (no specific parameters needed)
2. Have any ship selected
3. Open up the `Research` window (press `r` or click the icon)
4. Click on the different ship icons available.

_Expected_
SFX related to clicking on buttons (confirmed or denied) plays.

_Result_
VO is triggered as if your are commanding a ship to do an action.

_Additional info_
- No action is taking place. Only the VO is triggered.
- This can also happen with T
- This may be related to #608 and #604 and may be resolved already.

**Comment by snowschu** [comment]
Updated 2019-03-16

_Operating System_
Windows 7 (64bit)

_Version_
Game: v969 [72ce355]
Release: v925 [77df05d]

_Repro_
1. Begin a Single Player, Survival match (no specific parameters needed)
2. Have any ship selected
3. Open up the `Research` window (press `r` or click the icon)
4. Click on the different ship icons available.

_Expected_
SFX related to clicking on buttons (confirmed or denied) plays.

_Result_
VO is triggered as if your are commanding a ship to do an action.

_Additional info_
- No action is taking place. Only the VO is triggered.

**Comment by josefnpat** [comment]
This bug effects all game modes.
