### ISSUE TITLE
UX: Research gathering speed too fast

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#611]
Playtesting with the current Research feels very quick. Confirmed by @josefnpat that it would take approx. 10mins to accumulate enough research to unlock everything.

We may need to get more feedback on research from more experienced RTS players, but I feel that research gathering is rather boring and unfulfilling. 

Furthering this, the fast Research could affect our Campaign mode negatively. (I say could, since we don't have a Campaign mode to test with).

My proposed action would be that we slow down the accumulation of Research from 1pt per 1 second to 1 point per 5 seconds. (I'm not sold on 5 seconds but it's just a number to test with). In addition, I would also propose we put a cap on total Researched accumulated (similar to the Command Capacity cap we have).

**Comment by softsound** [comment]
@josefnpat what do you think?

1) slow down research from 1 pps to 5 pps (points per second or whatever measurement you are using)
2) cap total research.

I think it sounds fine for now and I would not imagine that tough to change. I'm for it, though I feel it's sorta a band-aid for a system not well understood. I don't have any better suggestions though so let's try this for now.

**Comment by josefnpat** [comment]
I have quadrupled the amount of materials now that we have BSP on the server. Tell me what you think about it!

https://github.com/josefnpat/roguecraft-squadron/commit/926b59f2ec1b76799d8221ce83c8bf1793fd9116

**Comment by snowschu** [comment]
> I have quadrupled the amount of material/ore in each pocket (now that we have BSP on the server!). Tell me what you think about it!
> 
> [`926b59f`](https://github.com/josefnpat/roguecraft-squadron/commit/926b59f2ec1b76799d8221ce83c8bf1793fd9116)

1. I tested it, but I can't really tell the difference from previous to current resource pockets. I don't see a visual difference and I don't notice my ships gathering items faster or longer.
2. How is this relevant to the Research gathering speed?

**Comment by josefnpat** [comment]
1. The number of objects have not increased, the quantity that they supply have. You'll notice that AI doesn't expand as much. Not sure if this is a good thing.
2. It's not.

**Comment by josefnpat** [comment]
Removed unrelated comments

**Comment by snowschu** [comment]
More player feedback from March 2019 about Research going too fast.
Quote from player:
`"Research goes so quick it feels like pointless busy work. Almost like the first time I build a ship it takes twice as long as normal."`
