### ISSUE TITLE
UX: Research Window Closing Button

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#612]
The `Research` window should have a button on screen to close the window.

Right now we have: 
- Open - Click icon in upper left corner
- Open - Press `r` on keyboard
- Close - Press `r` on keyboard

Two options to address this issue (A is one we should have, B is a bonus):
- A. Adding a closing button to the upper left corner of the window (Keeping it in line with our current UI of actionable buttons).
- B. Clicking outside of the window closes the window and brings you back to the game/map.

**Comment by josefnpat** [comment]
Fix by 937c6c06
