### ISSUE TITLE
"Enemy Engaged" VO is louder then the rest of the VO

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#614]
_Operating System_
Windows 7 (64bit)

_Version_
client n/a
server n/a

_Repro_
1. Begin a Multiplayer game and add at last one AI (or play with a human)
2. Build military ships (any ship that can shoot)
3. Engage an enemy ship.

_Expected_
When VO is triggered for enemy engagement, VO level is the same as all other VO.

_Result_
The VO for "enemy engaged" is much louder than the current VO level.

_Additional Notes_
VO for this sounds like it might be tied to SFX.

**Comment by josefnpat** [comment]
Enemy notifications was leveraging `playSFX` and `loopSFX` from the old single player system.

The old code as been refactored to use the `sfx` module and `[play|loop]SFX` system has been removed.
