### ISSUE TITLE
Demos: Players don't care about headphones

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#618]
During demos, I often see players not bother with the headphones. Mostly dude to wanting to be able to interact with their demo partner on the other machine and also possibly to listen to booth watcher explain things.

While we want them to hear the music, the VO, the Sfx, I propose we stop automatically attaching the headphones to the machine and make it available as an option if people ask. The monitor's already have speakers included and we can pump up the volume enough so people can hear them.

Bonus: Some people find sharing headphones gross and unsanitary. We can allow people to attach their own headphones/earphones if they wish.

**Comment by softsound** [comment]
Okay, seems fine.

**Comment by softsound** [comment]
@josefnpat any input? 

If not I say I agree with this ticket and it can probably be closed as it's not actionable.

But we should agree first of course.

**Comment by snowschu** [comment]
Advertising and marketing tickets don't get closed the same way as an actionable ticket in code or UI. 

This ticket exists to establish concern for a process that won't be fully tested until the next demo (and/or the demo after that).

This ticket will remain open until the end the the project.

**Comment by josefnpat** [comment]
Yes, let's see how loud these speakers can get!

Let's find out if this works well :)
