### ISSUE TITLE
Minimum/Ideal System Requirements to Run the Game

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#620]
_I did a search but didn't find any tickets related to this. If we have this posted already, please reference it in the comments._

Write down/list out possible minimum requirements for our game. Use _Structure_ list as guide.

Our game is able to run on Windows, Mac, and Linux, but now we need to add some extra information.
My computer isn't the worst RCS could play on, but I'll start this out with mine as the baseline.
____
**_Structure_**
OS:
Processor:
Memory:
Graphics:
Storage:
Sound Card*:
Network Connection:
____
*I am unsure if we really need to mention sound card.

Additional assistance:
We can use the [love2d curated STEAM page](https://store.steampowered.com/curator/32659238-L%C3%96VE-Games/) to help us. Find the games that look similar to ours and use their minimum requirements.

**Comment by snowschu** [comment]
OS: Windows 7 (64bit)
Processor: Intel Core i3 @ 3.10GHz
Memory: 8GB
Graphics: 1GB - NVIDIA GeForce GTX 650 Ti

**Comment by josefnpat** [comment]
The steam machine specs:

OS: Windows 10 (64 bit)
Processor: Intel i7 4785 @ 2.2GHz
Memory: 8 GB
Graphics: [tweaked nVidia GTX 850m](https://www.geforce.com/hardware/notebook-gpus/geforce-gtx-850m/specifications)
Storage: SSD (Sata III @ Gb/s)
Sound Card*: on board
Network Connection: on board ethernet and wlan

RCS info:

* Current build idles at about ~455MB
* I know for a fact that love will die at 2GB
* 1280x720 minimum resolution, 1920x1080 suggested

Consider looking at the most popular love game on steam, [Move or Die](https://store.steampowered.com/app/323850/Move_or_Die/)

Their minimum reqs look pretty good.

I'll be on the lookout for even crappier machines to test on.

**Comment by snowschu** [comment]
I think your laptop might be a good candidate for a low-end machine to test with.

**Comment by josefnpat** [comment]
Good idea - I'll set that up.

**Comment by josefnpat** [comment]
Get this info to @snowschu

**Comment by snowschu** [comment]
my macbook model: a1286

**Comment by snowschu** [comment]
Possible mac os minimum specs
```OS Version: 10.10.5
Processor: 1.3 GHz Intel Core i5
Memory:  4GB
Graphics: Intel HD Graphics 5000
Network:   Broadband internet connection
Disk Space:  1GB

**Comment by josefnpat** [comment]
I have tested on my Lenovo laptop.

```
Lenovo Ideapad 100S-14IBR

https://www.notebookcheck.net/Lenovo-Ideapad-100S-14IBR-80R9003MSP.190095.0.html
![image](https://user-images.githubusercontent.com/646162/51366022-f6dcbc80-1aa8-11e9-93c7-f592ad2e8f3d.png)

Starts out on a 1v1 at 30FPS, but chugs along end game at ~20 FPS with backgrounds off and low quality FoW.

@snowschu Can we come up with some testing parameters so we can get a better idea of suggested specs and min specs? Or maybe we can relate this to #540 ?

**Comment by snowschu** [comment]
https://docs.google.com/document/d/1MxgnK9V05TeaOHmo1JiPUldlnyeHuw9ONYYAI_Hm738/edit?usp=sharing

**Comment by josefnpat** [comment]
MacOS

* Operating System Version: 10.7 or newer
* Processor: Intel Core i5
* Memory: 4GB
* Graphics: Intel HD 5000
* Network: Broadband internet connection

Windows:

* Operating System Version: XP or newer
* Processor: Intel Core i5
* Memory: 4GB
* Graphics: Intel HD 5000 or better
* Network: Broadband internet connection

Linux:

* Operating System Version: Ubuntu 16.04 and newer
* Processor: Intel Core i5
* Memory: 4GB
* Graphics: Intel HD 5000 or better
* Network: Broadband internet connection
