### ISSUE TITLE
Rally point feedback

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#621]
#595 I saw this and your list of things of why it would not work.

_So I know it's not my place but I wanted to offer suggestions but you know me I will anyway._

I would move this unto the ticket but I'm not sure if that would make you mad.

1) how buildqueue unqueues work  (esp when there's two)

_After_ a ship is built, it should check for a rally object (much like for a nearby enemy). If a rally point is found it should move towards that point (again much like trying to go after an enemy OR much like how the follow ability works) 

I think for now we should stick to have them move towards last built rally point or have only rally point on screen.

(Granted having multiple rally points/ follow points could be kind of cool) 

_Rally points could work like pings._ They could show for a brief amount of time.

2) the units stack
I didn't really understand this one.

3) the UX doesn't make sense

Yes, our UX is very limited I agreed. 

We can not control a crowd of units like you naturally can in most games. Considering tooth and tail, pikimin, overlord, etc all have the same rally ability, it's nice to be able to use

In many games, you can move and split between units quickly and set the rally point on the fly. Granted, you don't need to micromanage as much when you have a rally point, which is the point.  

4) the graphics renderer wont draw rally points for ships that are not on screen

Does it need to? The rally point should be it's own object. There should only be one rally point for ships on screen anyway. I mean we might be able to add more later but just see if you can get one working. 

I envision them as little flag like pings you stick in the world.

![image](https://user-images.githubusercontent.com/1772703/48536501-67324c00-e874-11e8-8aa6-de5ed1539899.png)

Like here, you can see the rally point, and maybe if you could see also a line connecting the ship. But you don't need that, it's extra. The behavior matters more than the UI.

![image](https://user-images.githubusercontent.com/1772703/48536310-d0658f80-e873-11e8-84a9-5dd068ebee7f.png)

5) there's no check to see if things that can build have rally

Can you do a check if they are following anything?

**Comment by josefnpat** [comment]
This ticket is very confusing; what is going on, and why isn't it on #595?

**Comment by snowschu** [comment]
Bumping this as it was recent feedback.
