### ISSUE TITLE
Steamworks sign up

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#625]
_Related to #558_
Joining the Steamworks distribution program requires some legal info that I only @josefnpat can work on.

- Log on to https://partner.steamgames.com using MSS's login info. 
- Read through and fill out all the paperwork carefully. 
- Entering the program requires a signed NDA, SDA _(I dont know what that is)_, and paying the sign up fee _(I am unable to see ahead for what the cost is)_.

If there are questions, please message me in telegram.

**Comment by josefnpat** [comment]
Blocked until this can complete:

![image](https://user-images.githubusercontent.com/646162/49492494-1cc24080-f81e-11e8-8ed0-cc6022f1ff0e.png)

**Comment by josefnpat** [comment]
KYC required further information. It has been sent.

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/49894503-b1770080-fe13-11e8-921e-952b2b41deeb.png)

Ok, I think this is complete, as we are now ready to start filling the data in.

https://partner.steamgames.com/home
