### ISSUE TITLE
LoveJam game mode

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#626]
- [x] Visual Novel
- [x] Levels
- [x] Spread out resources
- [ ] Add as unlockable
- [x] Update description so that players know that this version is in essence the original game jam, but it uses the new engine.

**Comment by softsound** [comment]
I suggest we call it LoveJam Reboot.

It's based on some of the original concepts but has been updated for better gameplay. 

"Play the lovejam reboot to experience some of the original story and level based gameplay."

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/49354815-54987f00-f68a-11e8-990d-623628d8a313.png)

**Comment by josefnpat** [comment]
blocked by #858
