### ISSUE TITLE
Game might not be optimized for laptops

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#634]
This issue current affects the following keys:
_[Delete]_ - self-destruct ships

and also has issues with using the trackpad mouse. RMB clicks become complicated, as well as moving the camera with ease.

We'll need to move the self-destruct button to another key. As for the mouse and camera, I'm unsure if there's a solution. More testing is needed.

**Comment by josefnpat** [comment]
1. Delete key for macintosh is `FN+Backspace` - but mapping this to backspace as well makes sense.
2. Very few gamers will elect to play an RTS with a trackpad - I think it's fair to assume our target audience has a mouse somewhere. We could consider adding a rmc/lmc button, perhaps on `,` and `.` - but I've never seen any game do that before.
