### ISSUE TITLE
Menu is confusing

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#637]
Currently:
Title screen > Play Game >(Lobby) Host Game > Choose the game type
Title screen > Play Game >(Lobby) Host Game > Wait how do I add players?

I feel like it should be:
Title Screen > Play > Choose Game Type > Lobby (Set up host) **_or_** Start game (if single player)

**Comment by josefnpat** [comment]
Please don't add things to the milestones without talking about it beforehand.

I imagine that this UX polish would make things a bit easier, but considering the amount of work it would require to do so, would be tricky.

**Comment by softsound** [comment]
I think this has been fixed. Thank you.
