### ISSUE TITLE
Ensure that press and users can differentiate between lovejam version and release (1)

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#643]
I don't want folks using old videos when there are new ones.

**Comment by softsound** [comment]
We might just change the name a little or add a subtitle

Rouguecraft Squadron The Extended Edition
Rouguecraft Squadron Extended
Rouguecraft Squadron 2.0
Rouguecraft Squadron Chronicles 
Rouguecraft Squadron Multiplayer Edition
Rouguecraft Squadron The Finale
Rouguecraft Squadron Unlimited

**Comment by josefnpat** [comment]
Add tagline to main menu

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/51722170-209e6200-201a-11e9-8e7c-74553144cd34.png)
