### ISSUE TITLE
Add checkmark to ready/not ready

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#651]

**Comment by softsound** [comment]
Do you need assets for this? 

I think I told you to create programmer assets as it will fit your style so please create a checkmark.

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/51650585-71488900-1f4e-11e9-88f9-857cb6f498e8.png)
![image](https://user-images.githubusercontent.com/646162/51650599-773e6a00-1f4e-11e9-8b7a-d2de523c52df.png)
