### ISSUE TITLE
Add tooltips to all UI elements in lobby (1.5)

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#652]

**Comment by softsound** [comment]
- [ ] Write a list of UI elements

- [ ] Please let me review once to see if "regular" people will understand your terms/ offer feedback

- [ ] Implement

**Comment by josefnpat** [comment]
From top to bottom:
- [ ] Full Game / Demo - Change what ships are available in the game.
- [ ] Network - Change the update time per player. Raise this if your game has issues.
- [ ] AI Count - Change how many computers you want playing in the game.
- [ ] Build Mode - Change how long it takes to build ships.
- [ ] Research - Determine if all ships are unlocked in the game.
- [ ] Command Cap - Determine how many ships can be made in a game by choosing a command capacity.
- [ ] Map Type - Choose what kind of map the game will use.
- [ ] Map Size - Choose the size of the map for the game.
- [ ] Resources - Choose how many resources are available on the map.
- [ ] Resource Pockets - Choose among how many pockets the resources are spread out on. Only works for Map Type Spaced Pockets.

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/51806974-59bb1a00-2246-11e9-8ba6-9ecd02afd983.png)
