### ISSUE TITLE
Add world building image to lobby (0.5)

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#653]
5. Add image in lower right with offset of chat box
* Use to describe mode and world build
  * Image
  * Text
  * Chat box is 320x240 with padding of 32, which means you have:
  * Max width: 320
  * Max height: 720 - 240 - (32*2) = 416

Once this is complete, add asset and assign to me

**Comment by snowschu** [comment]
[lobby_art.zip](https://github.com/josefnpat/roguecraft-squadron/files/2790480/lobby_art.zip)

First pass. If adjustments are needed, in addition to commenting on it here, please link ticket and @ me in discord.

**Comment by josefnpat** [comment]
Two problems:

1. Embedding the text means that i18n will be harder.
2. We are not using one of the fonts from the game. (Or if you are, I cannot recognize which one it is. It doesn't seem to be expletus, nova or yantramanav.)

Please supply me with the graphic and the text separately as requested in the OP

**Comment by snowschu** [comment]
[lobby_art.zip](https://github.com/josefnpat/roguecraft-squadron/files/2790702/lobby_art.zip)

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/51725175-74af4380-2026-11e9-834e-6a0a63876943.png)
