### ISSUE TITLE
Create game build for steam (0.5)

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#656]
Please finish your other tickets before this - #643, #653, #652 and #376 before you tackle this build release.

**Comment by josefnpat** [comment]
Blocked by #652

**Comment by josefnpat** [comment]
waiting on game review

**Comment by softsound** [comment]
Review is good, please continue

**Comment by josefnpat** [comment]
Builds for v920 have been built and PM'd to @softsound

**Comment by josefnpat** [comment]
Need to rebuild for #665

**Comment by josefnpat** [comment]
Builds for v921 have been built and PM'd to @softsound

**Comment by josefnpat** [comment]
Need to rebuild v924

**Comment by josefnpat** [comment]
Release Candidate 3 (RC3) is v924

Builds for v924 have been built and PM'd to @softsound

**Comment by josefnpat** [comment]
Need to rebuild v925

**Comment by josefnpat** [comment]
Release Candidate 4 (RC4) is v925

Builds for v925 have been built and PM'd to @softsound
