### ISSUE TITLE
Research button is confusing

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#660]
Blue means you can use it even though you don't have enough research. 

![image](https://user-images.githubusercontent.com/1772703/51796776-ed94d380-21bd-11e9-81de-e8aafae80584.png)
This good. On hover it shows you can unlock it.

![image](https://user-images.githubusercontent.com/1772703/51796785-08ffde80-21be-11e9-8faa-c1fa6709624f.png)
This is bad. This should be red and say need points, or maybe have text under it saying not enough research, or just be gray until you have enough points and say need x points.

Also
![image](https://user-images.githubusercontent.com/1772703/51796765-c9d18d80-21bd-11e9-840e-ebcf4bc8e5f1.png)
Should say unlocked not unlock

**Comment by josefnpat** [comment]
This has been fixed!
