### ISSUE TITLE
Play menu is overwhelming / confusing

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#669]
Feedback:

> The play sub-menu felt a little overwhelming, as a brand new player. I wasn't really sure which option would lead to a simple vs AI match where I could learn to play. To me, Host Game sounds like I'm going into an online PvP match. I would also consider a deeper sub-menu structure separating things into a bit more fine grained categories And also the "Change User Name" option is just kinda sandwiched in there and feels out of place.

This is a common complaint - we need a way to get folks into a game right off the bat.

I would like to suggest we figure out a better name for "Host Game" and then default the AI Count to 1.

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/51860177-96e2e300-22fe-11e9-8933-d111cd7924f9.png)

**Comment by softsound** [comment]
#637 
#659
