### ISSUE TITLE
Clean up ship descriptions

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#671]
Feedback:

> I didn't know what any ships did before I researched them. The research text is mostly just flavor - I'd like to see more mechanics in there. You already have some basic info in the tooltip when you select an already built ship in game, but I'd like to know what it does before then (and maybe in more detail than what that other tool tips gives too).

**Comment by snowschu** [comment]
- [ ] Update human ships
- [ ] Review MW ships
- [ ] Update Dojeer ships (as race selection)

**Comment by snowschu** [comment]
[mp_objects.zip](https://github.com/josefnpat/roguecraft-squadron/files/3562929/mp_objects.zip)

Updated files of human, dojeer, mw, and non-ship descriptions.

**Comment by snowschu** [comment]
Alien_ folders will be handled by @josefnpat

**Comment by snowschu** [comment]
Errors with Dojeer_ files (and misc human files). Error is with saving via TextEdit. Human files were saved with Notepad++.

**Comment by snowschu** [comment]
Updated mp_objects folder with Pirate descritpions
[mp_objects.zip](https://github.com/josefnpat/roguecraft-squadron/files/3563089/mp_objects.zip)

**Comment by josefnpat** [comment]
- [ ] check for spelling
- [ ] Update alien from humans
