### ISSUE TITLE
Make Research more Relevant

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#672]
Feedback:

> Research management was pretty brainless, I didn't time it exactly, but on the default settings, it took like  <5 minutes to have everything researched, which means you don't really need to think too much about what you research. I liked how you started with full research and got to pick out your sort of starting set of ships. I would like to see that leaned into more to make that initial decision matter more. Research was too fast for that.

We should consider having research take longer, or at least help the player believe they are making informed decisions.

**Comment by softsound** [comment]
Research time does not affect if players believe they are making informed decisions. Research time only gives them more expected value. If you want them to feel more valuable make them take longer. 

If you want them to not just be mindless clicks have more requirements before you can unlock the research. Like x ship requires ship A & ship b to be unlocked and cost 500 materials in research but x ship is worth more than ship A & ship B. 

If they were organized by cost factors that might influence players too.

But I think being able to compare stats and functions is really what players want.

It's like do I need this ship? It has better stats then my older ships, so yes.

Adding in other ship upgrades like "new tech" that allows all ships to move faster, have highr rate of fire or deal more damage etc would be cool too.

**Comment by softsound** [comment]
#671

**Comment by snowschu** [comment]
related to ticket #611

**Comment by josefnpat** [comment]
bump
