### ISSUE TITLE
Update Steam Screenshots

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#687]
4th screenshot on steam is not in game:

![image](https://user-images.githubusercontent.com/646162/52365266-b966b180-2a0c-11e9-9ebe-24657c693ba4.png)

**Comment by softsound** [comment]
Let's get some new screenshots, my screenshots are dated. @josefnpat

**Comment by josefnpat** [comment]
Ticket for making new screenshots: #691

**Comment by josefnpat** [comment]
fixed
