### ISSUE TITLE
Update website to use white background 

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#695]
We don't have a background for the website so just have it be a clean white like the presskit.

- [ ] Change background to white

- [ ]  Change header to white

**Comment by josefnpat** [comment]
Can you please clarify? I'm not sure white is a good choice. DIdn't you say black? and what is the "header"?

**Comment by softsound** [comment]
I was just going to have it match the presskit it and have the design be white and simple since we don't have a good background for it.

If you made it black though... Could you overlay the stars from RCS?

**Comment by josefnpat** [comment]
Should I use the stars from in game, or will you provide me with some?

**Comment by softsound** [comment]
Using a real website now.
