### ISSUE TITLE
Please upload website content

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#705]
#335 

https://softsound.github.io/Portfilo/#portfolio

https://github.com/softsound/Portfilo

**Comment by josefnpat** [comment]
Website is missing some stuff:

Need:

- [ ] Clickable screenshots with properly resized thumbnails
- [ ] Youtube Channel Link
- [ ] Screenshots is missing a header
- [ ] Link to presskit
- [ ] [favicon](https://en.wikipedia.org/wiki/Favicon)

Want:

- [ ] image for top background needs to have UI disabled
- [ ] Link to devlog 
- [ ] Link to missing sentinel software
- [ ] Download section needs to be cleaned up. Perhaps:

Download now!

([steamicon] Steam) ([itchioicon] Itch.io)
