### ISSUE TITLE
Better UX for research window

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#709]
Players have trouble knowing that the research window exists.

**Comment by softsound** [comment]
Icon needs to be bigger and light up when research can be used. Honestly would be better if I keep the window to the side and not have it be in the way,

**Comment by josefnpat** [comment]
WIP:
![image](https://user-images.githubusercontent.com/646162/53679525-17e12180-3c93-11e9-8ca3-378ede21a1a6.png)

need new icons @ 32x32

**Comment by josefnpat** [comment]
wip2:

![rcs_blink](https://user-images.githubusercontent.com/646162/53706705-31987b00-3df1-11e9-8f01-5577a3a88831.gif)

dont need icons anymore
