### ISSUE TITLE
make icons for resources

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#71]

**Comment by josefnpat** [comment]
This ticket is for small icons that would represent the resources in the games.

for example:
![image](https://cloud.githubusercontent.com/assets/646162/24741061/ee7c6e64-1a69-11e7-84ba-1b48c2f42e62.png)

**Comment by softsound** [comment]
![personicon](https://cloud.githubusercontent.com/assets/1772703/24742114/84427494-1a6e-11e7-92ab-6c6b66e09b8b.png)
crew icon

**Comment by softsound** [comment]
![materialicon](https://cloud.githubusercontent.com/assets/1772703/24742125/8f4637e0-1a6e-11e7-8fba-06bcaec6f54f.png)
material icon

**Comment by softsound** [comment]
![oreicon](https://cloud.githubusercontent.com/assets/1772703/24742322/7168a748-1a6f-11e7-8649-4a75163a3a5b.png)
Ore icon

**Comment by josefnpat** [comment]
@softsound why is this in this milestone?

**Comment by softsound** [comment]
24x24 brighter and bigger

**Comment by softsound** [comment]
![people icon](https://cloud.githubusercontent.com/assets/1772703/24927529/e34a8954-1ec4-11e7-9c04-2fe9c365bdcb.png)

**Comment by softsound** [comment]
![material icon](https://cloud.githubusercontent.com/assets/1772703/24928061/ad2ea6b4-1ec6-11e7-91b1-f56fab897b43.png)

**Comment by softsound** [comment]
![material icon](https://cloud.githubusercontent.com/assets/1772703/24928197/33e48fac-1ec7-11e7-980f-1b833e8c7a0a.png)

**Comment by softsound** [comment]
![material icon](https://cloud.githubusercontent.com/assets/1772703/24928579/858cb27a-1ec8-11e7-817b-fd071454724b.png)

**Comment by softsound** [comment]
![material icon1](https://cloud.githubusercontent.com/assets/1772703/24928631/b0ab9746-1ec8-11e7-8174-f4d0613d519b.png)

Idea A for material

![material iconb](https://cloud.githubusercontent.com/assets/1772703/24928909/b087d576-1ec9-11e7-8aea-99b0418cddc7.png)


Idea B for material

**Comment by softsound** [comment]
![asteroid icon](https://cloud.githubusercontent.com/assets/1772703/24929383/5a6af72a-1ecb-11e7-9888-321c5fb4ad7b.png)

Asteroid icon
