### ISSUE TITLE
Add matchmaking

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#711]
> And friends-only pvp is pretty limiting

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/53985027-3fdfe300-40e0-11e9-84ee-f0595e3a74b5.png)

**Comment by josefnpat** [comment]
a1a3d2d3ebb5d095825c8cab362eafcb27c02846
d6c9b163d9b9a5f35bd85d1c70eede8f51271f55
19d2467316a8e0d83e2ac0a214c7582ffeb19d39
c7d5f493d70d57657501a203077caddfd0a6301d
158046d045c16d0494d68a9bcb57022f9892609e
8edd3e2391012d84edb70b0501fa93c15b754bea

**Comment by josefnpat** [comment]
Design:

![photo_2019-03-09_09-47-44](https://user-images.githubusercontent.com/646162/54073749-691f8100-4250-11e9-9829-80d5334cd393.jpg)

**Comment by josefnpat** [comment]
![image](https://user-images.githubusercontent.com/646162/54073793-e2b76f00-4250-11e9-94ca-a87dad04ff34.png)
