### ISSUE TITLE
Fix Steam Demo

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#714]
> Failure:
> Your store page has failed our review because the capsule images have the product name obscured by the green Demo banner. It is important for capsule images to have a clear logo or product name because they appear in many places throughout the Steam store that may not also display your product's name. Please update the following capsule images:
- [x] Header Image (header.jpg)
- [x] Large Capsule (capsule_467x181.jpg)
- [x] Small Capsule (capsule_231x87.jpg)

Please also perform sanity check:

- [x] check tags
- [x] matching presskit
- [x] check description
- [x] check system requirements (compare to main page)

**Comment by josefnpat** [comment]
Please also perform sanity check:

- [ ] check tags
- [ ] matching presskit
- [ ] check description
- [ ] check system requirements (compare to main page)

**Comment by snowschu** [comment]
Pushed for review.
Once its been reviewed and page active, it'll need a second pass through.

Note: Tags are user generated and won't be defined until the page shows up.

**Comment by snowschu** [comment]
Demo is fixed.
Images that needed to be fix do not appear on the store page, but in search results when using the STEAM program.
No other information needed to be adjusted.
![demo on steam](https://user-images.githubusercontent.com/34079393/57651652-66fcda00-7593-11e9-9424-71d5eb78afb4.PNG)

The demo also appears in the Newest search for Demos.
![Capture2](https://user-images.githubusercontent.com/34079393/57651844-dffc3180-7593-11e9-904d-47dcca175f72.PNG)
