### ISSUE TITLE
On research window highlight what is going on.

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#716]
Please make the UI faster.
White - Available to unlock (You have enough points)
Yellow - Currently selected (This is the ship you are looking at)
Gray - Not available to unlock
Green - bought

![image](https://user-images.githubusercontent.com/1772703/53677461-d0986800-3c75-11e9-9636-84ac40a89f33.png)

**Comment by softsound** [comment]
Anyway, we can condense and add more info? 

![image](https://user-images.githubusercontent.com/1772703/53677572-c8412c80-3c77-11e9-93cf-827dcc288a86.png)

**Comment by josefnpat** [comment]
Please tell me if corrects the original ticket.

As for the follow up request, please make a new ticket - we don't have two tickets in one.

**Comment by josefnpat** [comment]
Typo in commit - I mean this commit: 15861a7c1fcfaea505973a969b13d994665fda4d (v942)

**Comment by softsound** [comment]
Please update itch.io so I can test it

**Comment by softsound** [comment]
Can we add a yellow so we can tell what ship we are looking at?
I tested it and did not see a yellow like what is below.
![image](https://user-images.githubusercontent.com/1772703/53912351-689fa400-401e-11e9-9f57-75934ecf01d8.png)

**Comment by softsound** [comment]
Can I please request the ship selector/highlighter be yellow?

The white vs gray contrast is getting to me.

Also white feels like I need to buy it, it feels open like I need to do something with the icon.

Generally:
gray = not available
white = available (I can buy it now)
