### ISSUE TITLE
Condense Research Menu + Add ship build requirements + ship function

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#719]
Anyway, we can condense and add more info? Research is too big a window and hurts gameplay.

Players want to make a quick informed decision for a strategy game and the descriptions are not helpful. Some sort of basic stats and three-word ship description would allow players to select ships faster.
Also condensing the buttons closer together would make select faster and easier to compare choices.

Ships example types can be:

- Collects Material
- Repairs Ships
- Mid-grade Combat Ship
- Builds Advanced Combat Ships
- Repairs Ships
- Defensive Small Turret

I feel like people at a glance should understand what the ship does and make better decisions.

So ticket requirements:

- [ ] Condense Menu

- [ ] Show Build Requirements

- [ ] Show Battle Stats

- [ ] 3-4 Word Ship Description

- [ ] Bonus: - Show what the keyboard shortcut for research is below the close button and use that to toggle open/closed (Ultra UX)

![image](https://user-images.githubusercontent.com/1772703/53826988-96fa8200-3f3f-11e9-8b3b-76d6fc6f7a0a.png)

**Comment by josefnpat** [comment]
Design:
![photo_2019-03-09_09-47-44](https://user-images.githubusercontent.com/646162/54073762-7e94ab00-4250-11e9-9e3e-163409c6155d.jpg)

**Comment by josefnpat** [comment]
Implementation:
![image](https://user-images.githubusercontent.com/646162/54073766-953b0200-4250-11e9-8342-56c603d15e53.png)

**Comment by josefnpat** [comment]
a1a3d2d3ebb5d095825c8cab362eafcb27c02846
d6c9b163d9b9a5f35bd85d1c70eede8f51271f55
02f6c34c848aa8a59b0e2f055cf7a3dabe064d6a

**Comment by softsound** [comment]
Can I please request the ship selector/highlighter be yellow?

The white vs gray contrast is getting to me.

**Comment by josefnpat** [comment]
Wrong ticket.
