### ISSUE TITLE
Make scrap less colorful so it's easier to see enemies.

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#739]
Update enemy sprites so they're easy to see among everything else.

Maybe a gray-green sheen?

**Comment by softsound** [comment]
- [ ] Change scrap material to only be a yellow/brown color

**Comment by softsound** [comment]
old 

![image](https://user-images.githubusercontent.com/1772703/59816859-4f77e600-92e3-11e9-9476-c3158f760826.png)

new

![image](https://user-images.githubusercontent.com/1772703/59816852-49820500-92e3-11e9-8446-38c0495fc360.png)
