### ISSUE TITLE
Tiny Turret

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#746]
Add these to some ships
![miniBase](https://user-images.githubusercontent.com/1772703/54773817-59048b80-4bd8-11e9-828f-c87b4cf74fdb.png)
![miniNozzle](https://user-images.githubusercontent.com/1772703/54773818-599d2200-4bd8-11e9-8746-ab14b0c87db4.png)

![image](https://user-images.githubusercontent.com/1772703/54773853-6f124c00-4bd8-11e9-9fae-312ba5853df2.png)

![image](https://user-images.githubusercontent.com/1772703/54973195-e63f3b80-4f5c-11e9-92c2-44318ec715bd.png)

**Comment by josefnpat** [comment]
Need dojeer version for balance?

**Comment by josefnpat** [comment]
![1](https://user-images.githubusercontent.com/646162/54852898-39df2a00-4cbc-11e9-96ee-fc9f8b0bf47c.png)
![1](https://user-images.githubusercontent.com/646162/54852906-3c418400-4cbc-11e9-884a-2586fdb89649.png)

**Comment by josefnpat** [comment]
We'd like to get some legs on the human mini turret so it doesn't just seem like a small floating horn.

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/54973506-294dde80-4f5e-11e9-8620-8a08ff3ffd75.png)
