### ISSUE TITLE
Why does the command ship have a green hue when habit ship is collecting?

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#748]

**Comment by josefnpat** [comment]
What the hell are you talking about?

**Comment by josefnpat** [comment]
So the command ship generates research. It has nothing to do with the habitat.

![image](https://user-images.githubusercontent.com/646162/54842991-5ae65180-4ca1-11e9-89ad-231ad4f0bdf1.png)

**Comment by josefnpat** [comment]
working as intended
