### ISSUE TITLE
I don't play RTS - But I do play Mushroom Wars (RTS)

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#749]
Some players are confused by our system when they are used to other RTS systems like Mushroom Wars.

She said our game was too complicated and she felt dumb. Had about 5 people say they couldn't follow what they were supposed to do.

(I would classify that game as tower defense just looking at the video)

[link](https://youtu.be/t_4RllNACjk)

**Comment by josefnpat** [comment]
https://www.galcon.com/classic/history.html
