### ISSUE TITLE
Tutorial mode/Prelude

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#755]
Create a tutorial that holds the players hand through the game like in Undertale.

[Link](https://youtu.be/XWYNKyDuRwk)

The game starts with the backstory right away then goes to the main menu. _Maybe having a short video talking about earth's history before the aliens would help? Instead of our regular demo video_

(world building before you start the game)

In Undertale it goes like:
backstory video > Menu > start game > your story > name character > begin with video > Start with only way way you can go, left.

Then show the game piece by piece and walking you through it.

Have cases for success and failure of each step. 

We should do something similar with RCS

Backstory [example -
A long time ago we were happy and healthy. (smiling people)
Then the invaders came. (Fire and burning buildings)
We have been fighting them ever since! (ships are fighting in space)]

Backstory video (1-3 slides) > Menu > story opening > tutorial (should be the starting option and upon finishing opens up all other modes)

Characterstory [example -
My family was hurt by the invaders.
I enlisted to make my family proud.
Today is my final example exam. I can lead a crew if I pass. I know I will succeed.
]

Tutorial mode > 
"Welcome to the official exam for team Alpha RedBird" - dark silhouette announces over speaker

"Today we will be testing your skills against the dojeer, successful applicants will be rewarded a command certificate and a full crew. Only the best commander will succeed good luck on your exam and may the best team win." 

Commandship will be in a fenced in area with only a left opening leading to a small maze. 

"To begin we need to ensure our teams are able to show mastery of their ships. Select your ship with LMB and move by clicking elsewhere with the RMB. You must show mastery by getting through this coming obstacle."

Players then will need to practice getting through ships through a small obstacle course/maze. Once players reach the end the tutorial will continue.

"Congrats, not all teams have been able to pass the first course, let's see if you can pass then next course. We require teams to show they can survive in tough environments. Now we require you to collect enough resources to slow you understand survival skills. As you can see there are other ships in the area, we are giving you these ships for demonstration purposes. You will need to select them and then select the appropriate resource, so they can then go to collect the resource. Once they understand what to collect they will continue to collect anything similar nearby"

The player will see in this area there is a miner and habitat ship and much further away is a pile of scrap and a space station. They will need to click on the miner and then the scrap to start the scrap collecting process, the same for the habitat crew. Once the resources are filled up the ships will stop collecting and the speaker will pop up.

"Your ships stop collecting when your resources are full. We have enough to start the build process. Click on your command ship. This ship is large enough to construct many types of ships. You will see to the far left the build options and build queue. We will need you to build 3 fighters. By clicking on a build action it will be sent to the build queue. Click the scouts button three times to start building. A loading ring on the command ship will slow the amount of time left before the build is complete"

The player will then need to build 6 scouts total.

"You have successfully built a small crew of scouts. Scouts are fast and have the power to attack other ships and objects automatically but have very low defensives.   Click RMB and drag a square around all your scouts and move them together. Use them to destroy an obstacle in this area. " 

Bring all your scouts to destroy a large dummy box in the area, allowing you to explore a new area.

"You can see on the upper left a map, the rectangle being your current viewspace or camera. As you explore your map will show you where enemies and items are. Use your scouts to uncover the enemy and also look for a hidden bonus on the play field. Use your mouse to control the camera, as well as WASD. Spacebar will have the camera center on the commandship. You can also set your scouts anywhere on the map by RMBing on the map."

The player will need to send their scouts out to find the hidden item (cat box) and find the enemy.  
They can use the map but it's not required. Scouts will destroy the cat box to get the cat unit. The player can use it as a faster scout. (Will need cat scout unit asset)

Once the player find the enemy and engages they will trigger the speaker to pop up.

"You have found the enemy. return back to your command ship for further instruction."

Upon the scouts are back in range of the command ship the speaker will pop up again.

"Now is the ulimate test of skill. We will need you to destroy the enemy you found. We request though you build 1 tank and 1 battlestar to complete the exam successfully. To destroy the enemy you need only get nearby and hold shift to attack whatever is closest. Wipe all the enemies off the field to finish this exam."

**Comment by softsound** [comment]
#730

**Comment by softsound** [comment]
https://app.conceptboard.com/board/0fk1-52qg-cs2z-radk-8rap

**Comment by josefnpat** [comment]
Documented from minefaire:

https://docs.google.com/document/d/1-EMOqavauTgBSB7612GosOn2EFODiI_D1pDshjktxdk/edit?usp=sharing

**Comment by josefnpat** [comment]
design: https://docs.google.com/document/d/195kkih4MOpre5twcJRXvEjGN-CEFFA_Ilm1IKkQ3_Eg/edit#

**Comment by josefnpat** [comment]
bc4335f470a5d078e7ee71d197bee8d27f0f934a
51b7a1bcc65a8126b2570d689950d79495c743ff
0c7a9f7023c9d0f026a18936f43af2d314c7d391
