### ISSUE TITLE
UI: When multiple ships are selected, keep Radial visible

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#765]
A player mentioned how it was hard to tell how many ships they had selected in an area. They suggested possibly keeping the radial visible could help.

During the March 27th meeting, @josefnpat mentioned why they're hidden but, at the time I'm writing this, I can't remember. Lol.

**Comment by softsound** [comment]
You could also change the color of all selected ships to make it easier to understand at a glance.

**Comment by josefnpat** [comment]
We don't agree with this ticket, or we do not understand it.
