### ISSUE TITLE
Bug: [Survival] Player spawns out of bounds of map

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#768]
_Operating System_
Windows 10 (STEAM demo machines)

_Version_
v980

_Repro_
1. Begin a Survival mode match. Leave configuration default.

_Expected_
Ships spawn randomly inside the map/play area

_Result_
Ships spawn out of the map/play area.

_Additional notes:_
- Players can move ships to be inside the map/play area
- Ships built outside of the play area move to be inside the map/play area when built (unsure about mini turret) 
- Ships spawn a large % of the time at the edges of the map/play area.

Images:
![1553440954 - Copy](https://user-images.githubusercontent.com/34079393/55453568-09dc3480-55a2-11e9-8d5c-f18622b24398.png)
![1553437521 - Copy](https://user-images.githubusercontent.com/34079393/55453601-25dfd600-55a2-11e9-8b40-c8f13eb62ad2.png)

**Comment by josefnpat** [comment]
They player may still on occasion spawn outside the bounds, but the distance in which they do should be much less notable than before. If this is still an issue, we can reopen this ticket.
