### ISSUE TITLE
[Skirmish] UI animation disappears for ship building

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#769]
_Operating System_
Windows 10 (STEAM demo machines)

_Version_
v980

_Repro_
_Steps are currently difficult to repro. However, I can say that this tends to happens relatively early in the match._
1. Begin a `Skirmish` mode match. No special configurations needed
2. Play normal

_Expected_
Build ship shows that it is currently in the process of building a ship. (The ship's build radial and in the HUD display)

_Result_
UI elements that show players a ship is building are no longer displayed.
- Command Ship, Civilian Drydock and Military Drydock Build radial animation
- Build Queue loading animation [where it says `ready` or % to go.]

_Additional notes:_
- The ships are still building the ships they were told to build. The only thing that isn't happening is the animation to show it.
- Also noting that in the image below, the only ship selected is the Command Ship, to which is should also be showing a normal selection radial, which is absent.

![1553458044 - Copy](https://user-images.githubusercontent.com/34079393/55454035-edd99280-55a3-11e9-852b-07f4ccef0d1f.png)

**Comment by josefnpat** [comment]
* Whole game locks up for movement

**Comment by josefnpat** [comment]
We think we fixed this. Reopen if it happens again.
