### ISSUE TITLE
Make rest of alien ships

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#770]
- [x] Get list of missing ships
- [x] Work on missing ships

**Comment by josefnpat** [comment]
https://docs.google.com/spreadsheets/d/1otRe8Hlf3k4RxwzUNpd2hRYuN96tAC0rZSxm7SzY-48/edit#gid=0

**Comment by softsound** [comment]
A few updates

Repair Barge
![Repoko_RENDER](https://user-images.githubusercontent.com/1772703/60532253-862a0500-9cc2-11e9-87d2-738f76c8fa4d.png)

Mine (Bomb)
![Domi_RENDER](https://user-images.githubusercontent.com/1772703/60532284-9641e480-9cc2-11e9-8d2d-89000c0f62f5.png)

Mine layer
![Lacomi_RENDER](https://user-images.githubusercontent.com/1772703/60532307-a1951000-9cc2-11e9-9044-134b7a9a1c95.png)

**Comment by softsound** [comment]
![radarDojeer3_RENDER2](https://user-images.githubusercontent.com/1772703/61158903-efc6c200-a4bf-11e9-990e-0c77d7c54601.png)

**Comment by softsound** [comment]
Done
