### ISSUE TITLE
Update feedback form

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#772]
Current one is from SXSW2018

**Comment by snowschu** [comment]
updated form (newlink): 
https://docs.google.com/forms/d/e/1FAIpQLSeGfXQ69jSe652sD_kO8W1EqgUBH6pDgA3AnAKDcoOu3UW5fQ/viewform

**Comment by josefnpat** [comment]
Now works in game via roguecraftsquadron.com

**Comment by snowschu** [comment]
Confirming that feedback form does pre-populate the section for 'game version'
