### ISSUE TITLE
Marketing and Business Plan

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#778]
add to airtable

**Comment by josefnpat** [comment]
#774

**Comment by softsound** [comment]
Currently, the plan is simple.

Announce the game updates August 31th.

Social media graphics can be prepared with [Canva](https://www.canva.com/)

We should announce one week in advance that we have the game coming out on Twitter, Facebook, and Instagram. 

We can announce can on these sites:
Reddit (Multiple options)
And the standard social media sites...

It's a simple plan but considering our timeframe not sure if it will happen.

**Comment by softsound** [comment]
Marketing plan update

_Canva_ for creating appropriately sized images for social media. 
_Pixlr_ for further photo correction

Hootsuite or buffer for marketing automation. (Buffer preferred) 

_These Reddits are options_

1. RTS
2. indiedev
3. indiegames
4. strategy
5. steam
6. spaces/sci-fi
7. pcgames
8. multiplayer
9. voiceactors
10. game visual novels
11. gameart
12. love
13. lua
14. lua games
15. linux games
16. mac games
17. windows games
18. building games
19. marketing games

Messaging will be like

Hey guys check out this game I've been working on
Check out the final release of this games

thrown in pitch, keep it causal

etc.
