### ISSUE TITLE
Either explain difficulty better or remove wolf3d joke

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#78]

**Comment by josefnpat** [comment]
@softsound any chance I can get some cute portraits of the commander/adjutant?

![image](https://cloud.githubusercontent.com/assets/646162/24326438/572eccfa-117c-11e7-9174-891e8a04b9cb.png)

**Comment by josefnpat** [comment]
This ticket can also be cleaned up while doing #42

**Comment by softsound** [comment]
I vote remove... Personally, since that game came out literally the day before I was born. I think the younger audience won't understand the reference. 

If you want to keep it, we can test how many players know the reference. I suppose...

**Comment by softsound** [comment]
Let's just make it plain for now:

Normal 
Pretty Hard
Impossible 
Beyond Impossible

You could also play different "ranks"

 Private (Easiest) to General (Hardest), someone did this with 1st person shooter...

Perhaps create your own ranks.
