### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#79]
# MVP

- [x] Add lovernet
- [x] Add client state
- [x] Add server state
- [x] Add movement system
- [x] Add player ownership
- [x] Add bullets
- [x] Add health and bullet impact
- [x] Add targeting system
- [x] Debug create ship
- [x] add move animation
- [x] Add starting command ship
- [x] Add ship interface
- [x] Add ships
- [x] Add neutral assets (black hole, cat, cloud, scrap, asteroid, station)
- [x] Add neutral interactions
- [x] Add enemies
- [x] Add enemy AI
- [x] Add music
- [ ] Add sfx
- [x] Add minimap
- [x] Add resources
- [x] Add selected units
- [x] Add ship info
- [x] Add build ship actions
- [x] Add pause menu
- [x] Add planets
- [x] Dyson sphere
- [x] Add IP trickery
- [x] add connecting info
- [x] explosions
- [x] Auto attack
- [ ] lshift + singleSelected does not work correctly
- [x] player can change target of units it does not own
- [ ] minimap is buggy, probably camera offset
- [x] make objects spin
- [x] make object edge bounce when selected
- [x] add throttling
- [x] don't show objects not in fow
- [x] objects' fow does not work
- [x] gather effect
- [x] make debug create only work in debug

 # Beyond MVP

- [ ] add ship interactions (e.g. troopship)
- [ ] Add remaining ship actions
- [ ] Disclaimer
- [ ] hook up options
- [ ] add upgrades
- [ ] Add tech tree
- [ ] Add tutorial
- [ ] Add warnings
- [x] Add fog of war(s)
- [ ] Add research
- [ ] Add a alliance menu
- [ ] score
- [ ] drop scrap on death
- [ ] remove ships on disconnect
- [ ] add in options to client state
- [ ] check for display_info for objects' names
- [ ] figure out why it doesn't run on macOS 10.13.4 (PFO)
- [ ] disconnect on death
- [ ] make map size a variable and sync map size with client
- [x] don't allow players to attempt to move other player's objects
- [ ] Add cursor colors

**Comment by softsound** [comment]
Muliplayer:
pvp
team mode vs ai
capture the fortress/flag
