### ISSUE TITLE
Tutorial: Players have a hard time seeing what ships to build in Research screen

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#799]
Players are overwhelmed by the choices for in unlocking ships for Research. 

We should consider using the colored arrow that we've been using in the tutorial to point to the ships they need to unlock on the Research screen.

**Comment by snowschu** [comment]
_Based on build v1009 [e4e6c8d]_
Consider using an arrow to also point to the `unlock` button

**Comment by josefnpat** [comment]
@snowschu wants to review this
