### ISSUE TITLE
Pirate Set --Done

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#824]
#454

**Comment by josefnpat** [comment]
See 454 for a start

**Comment by softsound** [comment]
Hoping to use old art 

![DryDock_RENDER](https://user-images.githubusercontent.com/1772703/63303249-e4c43600-c2a4-11e9-84f8-01d38f65b84e.png)

**Comment by softsound** [comment]
![Mine](https://user-images.githubusercontent.com/1772703/63644802-7c1af600-c6b6-11e9-8bb5-c26b94157651.gif)
![Doomuku_RENDER](https://user-images.githubusercontent.com/1772703/63644811-bd130a80-c6b6-11e9-9034-23595082c6c3.png)

**Comment by softsound** [comment]
artillery
![artillery_RENDER](https://user-images.githubusercontent.com/1772703/63645062-1b8eb780-c6bc-11e9-9aa3-075b397e0516.png)

**Comment by softsound** [comment]
5 left

**Comment by josefnpat** [comment]
using random pirate ship as troopship
