### ISSUE TITLE
NAGN Review Copies

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#827]
Contact via discord

**Comment by josefnpat** [comment]
> X responded to the preview build signup form. If you'd like to send him a build to test playtesting. Check the response spreadsheet for more info.

**Comment by snowschu** [comment]
https://docs.google.com/spreadsheets/d/12ozSmJShw_SP4q4Ctl55w7p69atVFX75eEv1DM9wZ6I/edit?usp=sharing 

Spreadsheet should be private.
