### ISSUE TITLE
More variety of planets

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#828]
Add suns too!

Moons!

**Comment by softsound** [comment]
k

![bigSun](https://user-images.githubusercontent.com/1772703/63206011-ee665780-c072-11e9-98dd-89f044ab6626.png)
![blueplanet](https://user-images.githubusercontent.com/1772703/63206012-ee665780-c072-11e9-8770-7832edab0088.png)
![littlePlanet](https://user-images.githubusercontent.com/1772703/63206013-ee665780-c072-11e9-8261-3a7a720dc014.png)
![moon](https://user-images.githubusercontent.com/1772703/63206014-ee665780-c072-11e9-9eb8-82dfd658aaa5.png)
![sun](https://user-images.githubusercontent.com/1772703/63206015-ee665780-c072-11e9-96ae-59b2cd75a59a.png)
![sun2](https://user-images.githubusercontent.com/1772703/63206016-eefeee00-c072-11e9-90e7-265bf4d041ce.png)
![sunBlue](https://user-images.githubusercontent.com/1772703/63206018-eefeee00-c072-11e9-9e50-5b9f863d2e75.png)
![white](https://user-images.githubusercontent.com/1772703/63206019-eefeee00-c072-11e9-8394-7fb729071397.png)
![yellowPlanet](https://user-images.githubusercontent.com/1772703/63206020-eefeee00-c072-11e9-838d-26a1b26494ea.png)

**Comment by softsound** [comment]
This might need further testing once they are in-game

**Comment by josefnpat** [comment]
I have cropped with a zero threshold. A few of these planets do not have auras, and look very strange. Some planets are not properly aura'd at all, and look really awful. The rock one didn't make sense astronomically, so I didn't include it.

Please review the assets in game. If you need to update an asset, please use `src/assets/planets/*` as source

**Comment by softsound** [comment]
I tried to make the rock one look more like a "moon" but I'm happy to make it fit the rest!
