### ISSUE TITLE
Create Business Cards

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#83]
I want business cards with a QR code so I can just grab a card and show people how easy it is to use.
I want them to see the site and sign up for future updates.

**Comment by josefnpat** [comment]
![static_qr_code_without_logo](https://cloud.githubusercontent.com/assets/646162/24462689/3f53714e-146a-11e7-8317-8fb384107371.jpg)

**Comment by josefnpat** [comment]
We should re-scope this ticket as "make business cards"

**Comment by softsound** [comment]
Okay

**Comment by softsound** [comment]
Business cards have been made.
