### ISSUE TITLE
Imgur is deleting photos from the tutorial

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#838]

**Comment by josefnpat** [comment]
https://github.com/josefnpat/roguecraft-squadron/wiki/Cygwin-Setup

keep everything on github wiki

**Comment by softsound** [comment]
done

**Comment by softsound** [comment]
https://docs.google.com/document/d/104igiaZupLUfBc_NVqZQpdvbli663CN7t10Z8z2QISE/edit?usp=sharing
