### ISSUE TITLE
Alien race set (lovejam) -- done

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#840]

**Comment by softsound** [comment]
#770

**Comment by softsound** [comment]
note extra leftover ships on #824

**Comment by softsound** [comment]
repair
![repairShip_RENDER_](https://user-images.githubusercontent.com/1772703/64087538-1e645a80-cd03-11e9-837c-55c80d702301.png)

**Comment by josefnpat** [comment]
Aliens now known as Hybrid
