### ISSUE TITLE
Review and Update Credits

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#846]

**Comment by josefnpat** [comment]
please attach desired logo @snowschu

**Comment by snowschu** [comment]
330px x 330px logo, saved as png with transparency.
if issues, please message asap.
[ashschu-logo-rcs.zip](https://github.com/josefnpat/roguecraft-squadron/files/3567895/ashschu-logo-rcs.zip)

**Comment by snowschu** [comment]
Verbal documentation by @josefnpat 
>Blocked. Waiting on Jmm

**Comment by josefnpat** [comment]
John McKinnon (@jmckinnonmusic) — Sound Design
