### ISSUE TITLE
We need an email subscription list and social media options

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#85]
I want people who are interested in the game able to subscribe to email or social media accounts for our business. I've had a lot of people want to check out the game and they seem interested in following it, but we don't currently have easy ways to do that.

**Comment by josefnpat** [comment]
We can use https://mailchimp.com/ for email stuff. I also have these accounts:

* https://www.facebook.com/MissingSentinelSoftware/
* https://twitter.com/missingsentinel
* https://plus.google.com/117038046271367772992

**Comment by softsound** [comment]
[link to a site breakdown](https://docs.google.com/presentation/d/13lmIytFt4CC7AOqOPbZ5-WhuwwH5XvSdWwt9qpDwnCI/edit?usp=sharing)

This is what I want to copy style wise.

**Comment by josefnpat** [comment]
* Add emails from survey

**Comment by softsound** [comment]
link to subscribe to the the newsletter :http://eepurl.com/ddrrdv

**Comment by snowschu** [comment]
We will be adding them manually after SXSW. There will an option to sign up for the newsletter in the survey. And we'll have paper versions of the survey available, incase the ipad fails. 

I have things handled but our focus for the milestone should be the game and its features ^.^

**Comment by josefnpat** [comment]
Excellent - reassigning to @snowschu so that she can set up the iPad

**Comment by snowschu** [comment]
Email sign up has been included with the survey. [Ref ticket 295](https://github.com/josefnpat/roguecraft-squadron/issues/295).

We will move the set up of mailchimp and newsletter until after SXSW.

**Comment by josefnpat** [comment]
roguecraftsquadron.com/list
