### ISSUE TITLE
Make a Presskit (1)

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#86]
http://dopresskit.com/

**Comment by softsound** [comment]
This will be moved into a presskit feature request and closed.

**Comment by josefnpat** [comment]
@softsound the presskit has not been made (and therefore is not a "repeatable" thing for demo events). Unless this is a duplicate ticket, it needs to stay open.

**Comment by softsound** [comment]
#622 
#623

**Comment by josefnpat** [comment]
This ticket is blocked by:

#453 #620 #622 #623 #643

**Comment by softsound** [comment]
Blocks left until ready for work:

- [ ] 453

- [ ] 620

- [ ] 622

- [ ] 623

- [ ] 624

- [ ] 643

**Comment by softsound** [comment]
@josefnpat Please set up the server to handle this ticket and if possible create the presskit when #643 is done.

**Comment by josefnpat** [comment]
There seems to be some confusion as to what a press kit needs to include and how it should be formatted.

While dopresskit works for a company (e.g. Missing Sentinel Software) there is no documentation on how to actually add a project to it - or make a presskit for a game as opposed to a company.

It is my opinion that the information we have collected, while it will be helpful, doesn't fit into what we're looking for in a presskit.

Moving forward: we need to centralize all of our information regarding a presskit (e.g. images, logos, icons, text, company info, screenshots, etc) and then identify what information we require in a presskit. (either by looking up howtos or at other presskits.)

We then need to build the presskit from that information.

This ticket was entirely underscored as `dopresskit` is not a good solution and the materials we have are not prepared.

I will assign it back to @softsound so we can figure this out.

**Comment by softsound** [comment]
This has been updated.
https://github.com/josefnpat/roguecraft-squadron/issues/622

This has been updated
https://github.com/josefnpat/roguecraft-squadron/issues/623

Presskit will need to be reformatted for RCS but should be useable for MSS.

I will try and figure out a way to reformat presskit.

**Comment by softsound** [comment]
It's been decided for now to just focus on #623 for now so I'll call this closed.
