### ISSUE TITLE
Update Tagline

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#865]

**Comment by josefnpat** [comment]
deadline of sept 16

**Comment by josefnpat** [comment]
Final Reckoning

**Comment by josefnpat** [comment]
Assigning to @snowschu to make asset and deliver by Sunday!

**Comment by josefnpat** [comment]
![tagline](https://user-images.githubusercontent.com/646162/65343695-352bfd80-db9b-11e9-9763-f0506251c86f.png)

Adding a placeholder version. Getting this done earlier will improve the chance that it will get into the marketing videos and game.

**Comment by josefnpat** [comment]
I need this done asap for everyone else that is using this asset.

**Comment by snowschu** [comment]
[final-reckoning.zip](https://github.com/josefnpat/roguecraft-squadron/files/3639122/final-reckoning.zip)

**Comment by josefnpat** [comment]
Some notes:

* The graphic is cut on the edge, and won't look right here: ![image](https://user-images.githubusercontent.com/646162/65379958-9e446b80-dc96-11e9-9e9e-7f012fe4cbcb.png)
* It's very dark, and will be awfully hard to read

Can we get a revision? If not, we can just close the ticket.

**Comment by snowschu** [comment]
That's odd. That doesn't show up on my version. I will investigate.

**Comment by snowschu** [comment]
[final-reckoning-02.zip](https://github.com/josefnpat/roguecraft-squadron/files/3639161/final-reckoning-02.zip)
Try this adjust for the smoke effect. Then, upload a screenshot of the whole please. I will make adjustments

**Comment by snowschu** [comment]
[final-reckoningvs2.zip](https://github.com/josefnpat/roguecraft-squadron/files/3639435/final-reckoningvs2.zip)
updated tagline graphic

**Comment by josefnpat** [comment]
I love it, awesome job
