### ISSUE TITLE
VN text needs checking

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#867]
The dialog needs to be checked for correct grammar, punctuation, and context (this one is optional. Some lines have odd idiom choices).

If there is a preferred way to mark dialog updates, add a comment please.
Other wise, for the time being, this is how I'll be notating:

- Chapter
- Who's speaking (full name)
- The exact line and how it appears in the game
- Suggested update
- Additional info (if requested)

I have it set in this way so that I can read it in context to how it appears in the game.

This has been assigned to everyone, as it is helpful to have multiple eyes on this. However, please remove yourselves if you have no time for this task. No comment is needed.

**Comment by josefnpat** [comment]
To keep this in perspective, we'll be recording lines very soon, so this needs to happen asap.

**Comment by snowschu** [comment]
@josefnpat please post when first recording will happen. I have begun working on this ticket and could have this ready to go by the time you're ready to record, but I need dates.

**Comment by josefnpat** [comment]
@VividReality will record wed morn (GMT+1)
Candice will record with me either friday or saturday.

The script must be finalized tuesday night.

**Comment by snowschu** [comment]
adding link to current script to find it easier in the future:
https://github.com/josefnpat/roguecraft-squadron/blob/master/src/release/assets/mp_gamemodes/campaign/en.md

**Comment by josefnpat** [comment]
Miho - Fleet Commander 
Grace, Ruby, Valentina - Squadron Commander
Rosa - eXecutive Officer

**Comment by snowschu** [comment]
[markdown file for script](https://github.com/josefnpat/roguecraft-squadron/files/3598883/en.md.zip)

========
[My Working Doc](https://docs.google.com/document/d/1pDdemkcIzgZf5RDbd_I2vR-hn_7kKMiNaa0LrYmBLOo/edit?usp=sharing) if needed. (should be set in comment mode and invite only)

**Comment by snowschu** [comment]
Bug found.
UTF-8 decoding error.
Forgetting that google docs uses smart quotes and converts `...` into ellipses. 

Fixing file now, recompressing, and reuploading into previous post. 

As a sidenote: it is super cool how reflowprint works. Due to how its printing the text, it helped me narrow down the issue.

uploading screenshot for context:
![Screen Shot 2019-09-11 at 12 05 34 AM](https://user-images.githubusercontent.com/34079393/64670249-faeb8f00-d429-11e9-959c-282d2d9ad47f.png)
