### ISSUE TITLE
VN: Restrict buttons for story progression

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#868]
Right now any button presses on the keyboard or mouse progress the VN. This is frustrating, as occasionally, I, as a player, occasionally want to defocus the game and go to a webpage or another program. Pressing `alt+tab` progresses the story in an unwanted way.

We have a couple options:
- A) Consider binding progression to `spacebar`, `enter` ,`RMB`, and  `LMB`.
- B) Exempt certain keys or keybindings from progressing the story. Examples: `alt+tab`, windows key/command key, `shift+esc`, `ctrl+alt+esc`, `Print Screen`, Function Keys 1-12
- C*) No physical buttons at all and code in buttons people have to press to progress forward or backward

I'm under the impression that option A might be easier to deal with but I leave it to you to decide which will be easier.

* _C is mostly a joke because that might take longer than what we have to implement. On a serious note, though, adding on-screen buttons and allowing for forward and rewind options would be awesome for UX and accessibility._

**Comment by josefnpat** [comment]
I have added a drop down menu that allows users to choose what action they want to take.

To return, there is a radial select box.
