### ISSUE TITLE
Campaign Command Ships (done- pls review)

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#872]
Need command ships for:

* Miho
* Ruby
* Grace
* Valentina

add flag/emblem and hue shift

This feature request will help fix a bug #860

**Comment by softsound** [comment]
Wip
![flag1_RENDER](https://user-images.githubusercontent.com/1772703/64582095-28650980-d352-11e9-8e46-277e3580fda3.png)
![flag1_RENDER2](https://user-images.githubusercontent.com/1772703/64582096-28650980-d352-11e9-9ab8-79cc10a771d2.png)
![flag1_RENDER3](https://user-images.githubusercontent.com/1772703/64582097-28650980-d352-11e9-8338-e99c6d4295bc.png)
![flag2_RENDER](https://user-images.githubusercontent.com/1772703/64582103-2b5ffa00-d352-11e9-825b-c55379d630ff.png)
![flag3_RENDER](https://user-images.githubusercontent.com/1772703/64582105-2c912700-d352-11e9-8d62-eb658828940e.png)
![flag4_RENDER](https://user-images.githubusercontent.com/1772703/64582107-2ef38100-d352-11e9-9611-c894506bd24d.png)
![flag5_RENDER](https://user-images.githubusercontent.com/1772703/64582111-3024ae00-d352-11e9-876e-61e7e5fa1276.png)
![flag6_RENDER](https://user-images.githubusercontent.com/1772703/64582114-31ee7180-d352-11e9-8758-47697756ec3e.png)

**Comment by josefnpat** [comment]
Need ships for:

* Ruby
* Valentina
* Miho
* Grace

**Comment by josefnpat** [comment]
[command ships.zip](https://github.com/josefnpat/roguecraft-squadron/files/3639325/command.ships.zip)

**Comment by josefnpat** [comment]
![valentina](https://user-images.githubusercontent.com/646162/65382022-78cd5700-dcc2-11e9-9a8f-7320181423fb.png)
![grace](https://user-images.githubusercontent.com/646162/65382023-78cd5700-dcc2-11e9-85fc-70cb62ce74d2.png)
![miho](https://user-images.githubusercontent.com/646162/65382024-7965ed80-dcc2-11e9-9501-01b1364b115a.png)
![ruby](https://user-images.githubusercontent.com/646162/65382025-7965ed80-dcc2-11e9-9418-8e6bc812307e.png)
